WIP DOC-2843 Add CA doc for Conditional Module Studio UI
openedx-unsupported/edx-documentation pull request #1230
Opened 2016-09-07 22:14 UTC by catong

## [DOC-2843](https://openedx.atlassian.net/browse/DOC-2843)

This PR adds course author documentation for creating a conditional module in Studio.
Based on OSPR-1177 and https://github.com/edx/edx-platform/pull/11710

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2016-09-08 15:52 UTC, srpearce commented on en_us/shared/exercises_tools/conditional_module.rst
> +the **Advanced Module** List on the **Advanced Settings** page. Be sure to
"to the **Advanced Module List** policy on the **Advanced Settings** page"

Reasons:

- The name of this policy in the UI is "Advanced Module List", so we can't just say **Advanced Module** list"
- Saying "to the **Advanced Module List**" would be like saying "to the **Add Unsupported Problems and Tools**" or "to the **Allow Anonymous Discussion Posts**" (i.e., we need a noun) (note: In a perfect world, this item would probably be labeled **Advanced Modules** so we could just say "**Advanced Modules** list")
- The warning at the top of the page says "Do not modify these *policies* unless you are familiar with their purpose" (i.e., apparently these items are called policies)

2016-09-08 15:55 UTC, srpearce commented on en_us/shared/exercises_tools/conditional_module.rst
> +      automatically generated in your message.
"your message automatically contains a link to that component"

- Gets rid of "it" (pronouns are tough for machine translation)
- Avoids passive voice

2016-09-08 15:58 UTC, srpearce commented on en_us/shared/exercises_tools/conditional_module.rst
> +Example: Conditional Module Dependent on Poll Being Answered
I'd add something to differentiate this heading from the one in line 80

2016-09-08 15:58 UTC, srpearce commented on en_us/shared/exercises_tools/conditional_module.rst
> +      that is used to determine whether a learner is shown the content of this
typo: that that

2016-09-08 16:02 UTC, srpearce commented on en_us/shared/exercises_tools/conditional_module.rst
> +      be shown the content of this conditional module.
I'm not clear on this. Possible revisions:

The value of the conditional attribute that is specified in the **Conditional Attribute** field. (? This seems redundant.) The value of the **Conditional Attribute** field must be **true** for a learner to be shown the content of this conditional module. 

Or

The same value that is specified in the **Conditional Attribute** field. If the value of the **Conditional Attribute** field is **true**, the content of this conditional module is visible to learners.

2016-09-08 16:03 UTC, srpearce commented on en_us/shared/exercises_tools/conditional_module.rst
> +    * **Display Name**: This name appears in the horizontal navigation at the
For consistency: The name that appears... (this is the only item in this list that starts with a complete sentence)

2016-09-08 16:04 UTC, srpearce commented
A few comments.

2016-10-14 19:01 UTC, catong commented on en_us/shared/exercises_tools/conditional_module.rst
> +the **Advanced Module** List on the **Advanced Settings** page. Be sure to
I chose this wording to be consistent with many (most?) of the other problem types that need enabling in the same way, e.g. Annotation Tool, Word Cloud. I'd prefer not to introduce new variations in how we word these basic step. If in future we want to update, we should update the wording for all problem types.

2016-10-17 19:46 UTC, andy-armstrong requested changes
This is looking great, @catong. I have a few comments, in particular around the missing steps for configuring the list of sources.

2016-10-17 19:46 UTC, andy-armstrong commented on en_us/shared/exercises_tools/conditional_module.rst
> +To enable the conditional module in Studio, you add the `"conditional"` key to
Note that this won't work on prod until we declare the conditional module's support level:

https://openedx.atlassian.net/browse/TNL-5779

2016-10-17 19:46 UTC, andy-armstrong commented on en_us/shared/exercises_tools/conditional_module.rst
> +#. In the unit where you want to create the problem, select **Advanced** under
Maybe this should be "create the module" rather than "create the problem", because this isn't necessarily going to represent a problem.

2016-10-17 19:46 UTC, andy-armstrong commented on en_us/shared/exercises_tools/conditional_module.rst
>  "Yes" to a poll question see a different block of text from the learners who
I found this wording confusing, as it implies that learners have to see a different block of text. Maybe something like, "learners who answer... can be shown a different block of text..."

2016-10-17 19:46 UTC, andy-armstrong commented on en_us/shared/exercises_tools/conditional_module.rst
> +#. In the list of problem types, select **Conditional**.
Should say "In the list of advanced component types," not "problem types".

2016-10-17 19:46 UTC, andy-armstrong commented on en_us/shared/exercises_tools/conditional_module.rst
> +#. In the component that appears, select **Edit**.
This is missing the step for configuring the list of sources.

2016-10-17 19:46 UTC, andy-armstrong commented on en_us/shared/exercises_tools/conditional_module.rst
> +#. In the component that appears, select **Edit**.
This is the step I'm thinking of:

![image](https://cloud.githubusercontent.com/assets/5985072/19452873/b3534c82-9480-11e6-8769-2582bbf1cecc.png)

2016-10-25 19:19 UTC, catong commented on en_us/shared/exercises_tools/conditional_module.rst
> +#. In the component that appears, select **Edit**.
@andy-armstrong Isn't configuring the list of sources part of what you do in the component editor? I thought you only saw this message if you did not complete the config in the component editor. (I'm not able to test this on stage)

2019-08-09 14:33 UTC, feanil commented
Closing due to age, inactivity, and lack of resourcing.

2019-08-09 14:33 UTC, closed without merging