Add documentation about switching from ShoppingCart to E-Commerce.
openedx-unsupported/edx-documentation pull request #1247
Opened 2016-09-16 15:35 UTC by vkaracic

In order to use the Otto ecommerce service, after it's installation the user needs to switch from the old ShoppingCart. This is a very rough documentation but it's enough to get the ball rolling.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2016-09-16 15:35 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=1247&repo=edx%2Fedx-documentation

2016-09-16 16:06 UTC, lamagnifica commented
@srpearce

2016-09-18 16:55 UTC, lamagnifica commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
> +     The default is `/basket/single-item/` and if you change
put two pairs of ` marks around /basket/single-item/ for mono font

2016-09-18 16:59 UTC, lamagnifica commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
> +#. In your LMS Django admin panel, create a new Commerce configuration.
is the name of the section "Commerce" not "Ecommerce"? ugh.
Maybe be more explicit?
In the Commerce section, next to {name}, select Add.

2016-09-18 17:02 UTC, lamagnifica approved these changes
Thanks @vkaracic . I made a couple of suggestions.
I have a request: would you also add a DOC story in JIRA to outline what you think is still missing?

2016-09-19 11:42 UTC, vkaracic commented
@lamagnifica there isn't really anything missing, I just need someone to take check my wording. I can create a JIRA ticket if necessary?

2016-09-19 11:46 UTC, lamagnifica commented
ah, ok. Let me provide a few more suggestions. The way I read the description this seemed super urgent, and just the first of maybe a lot more additions!

2016-09-19 11:46 UTC, vkaracic commented
No, not urgent. It's something an open source user pointed out.

2016-09-19 11:48 UTC, lamagnifica commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
> +Switching from ShoppingCart to E-Commerce
Switching --> Switch 
(our standard is to use the imperative for procedure topics, and the gerund for conceptual topics)

2016-09-19 11:48 UTC, lamagnifica commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
> +Switching from ShoppingCart to E-Commerce
Switchin --> Switch 
(our standard is to use the imperative for procedure topics, and the gerund for conceptual topics)

2016-09-19 11:49 UTC, lamagnifica commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
> +In order to enable the E-Commerce service to handle your ecommerce-related tasks
I'd change the order here:
By default, the ShoppingCart service is enabled when you install an Open edX instance. To use the E-Commerce service to handle ecommerce-related tasks instead of ShoppingCart, follow these steps.

2016-09-19 11:52 UTC, lamagnifica commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
> +#. In your LMS Django admin panel, in the Commerce section add a new Commerce
bold "Commerce"
I'd suggest following the same pattern for steps here as is already used by [other topics](http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/static_replace/cdn.html) that have you adding things in Django admin.

2016-09-19 11:52 UTC, lamagnifica commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
> +#. Check the ``Enabled`` checkbox.
Check --> Select
strike "the" and "checkbox"
Use bold rather than mono font to identify UI controls

2016-09-19 11:52 UTC, lamagnifica commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
> +#. Check the ``Checkout on ecommerce service`` checkbox.
Check --> Select
strike "the" and "checkbox"
Use bold rather than mono font to identify UI controls

2016-09-19 11:54 UTC, lamagnifica commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
> +#. Fill in the ``Single course checkout page`` path value.
Use bold rather than mono font to identify UI controls

2016-09-19 11:58 UTC, lamagnifica commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
> +     that you need to change all the code that relies on that path.
This seems like it would be a significant amount of work. Maybe rewrite the step and the note on lines 291-295 to make this seem more optional?

#. (Optional) In the **Single course checkout page** field, override the default path value of ``/basket/single-item/`` with your own path value. 

   .. important:: If you override the default path value, you must also change all of the code that relies on that path.

2016-09-19 11:59 UTC, lamagnifica commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
> +#. Set the ``Cache Time To Live``.
Use bold rather than mono font to identify UI controls
Is this value obviously seconds, hours, minutes? Might users need guidance as to what type of value they're entering here?

2016-09-19 12:00 UTC, lamagnifica commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
Is there a **Save** step?
Do you repeat this entire procedure, or part of it, for each site that you want to enable E-Comm?

2016-09-19 12:02 UTC, lamagnifica requested changes
OK, @vkaracic here are my copy edits. Question: is this procedure also necessary in Eucalyptus (as of mid-July) as well as in the latest version of master?
(FYI @nedbat )

2016-09-19 12:24 UTC, vkaracic commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
Yes on both questions.

2016-09-19 12:24 UTC, vkaracic commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
> +#. Set the ``Cache Time To Live``.
It's set in seconds.

2016-09-19 12:24 UTC, vkaracic commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
> +     that you need to change all the code that relies on that path.
You are right!

2016-09-19 12:25 UTC, vkaracic commented
@lamagnifica comments addressed!

2016-09-19 13:03 UTC, lamagnifica commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
> +#. In the Commerce section, next to **Commerce configuration**, select **Add**.
bold "Commerce"

2016-09-19 13:04 UTC, lamagnifica approved these changes
tyvm! one nit, otherwise, let's do it!

2016-09-19 13:07 UTC, vkaracic commented on en_us/install_operations/source/ecommerce/install_ecommerce.rst
> +#. In the Commerce section, next to **Commerce configuration**, select **Add**.
Updated!

2016-09-19 13:07 UTC, vkaracic commented
@lamagnifica thank you very much for the review!

2016-09-19 13:07 UTC, merged

2021-01-08 12:06 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! I've created [OSPR-5330](https://openedx.atlassian.net/browse/OSPR-5330) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->