Update add_post.rst
openedx-unsupported/edx-documentation pull request #1268
Opened 2016-09-26 07:46 UTC by ayushin78

## [DOC-2003](https://openedx.atlassian.net/browse/DOC-XXXX)

Added maximum file upload size limit in Discussions.

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2016-09-26 07:46 UTC, edx-webhook commented
Thanks for the pull request, @ayushin78! I've created [OSPR-1471](https://openedx.atlassian.net/browse/OSPR-1471) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-documentation/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2016-09-26 16:35 UTC, gsong commented
@ayushin78 Thank you for your PR. We appreciate you taking the time to make the contribution.

Please submit a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf) to us so we can review this pull request. We realize it's additional work for a simple change in this case, but you only have to do this *once* and we're hoping you would make future contributions as well.

2016-09-26 17:39 UTC, lamagnifica commented
Hi @ayushin78 ,
I'd like to move forward with your work, but we will need a contributor's agreement from you. Please comment if you have difficulty completing it.
Alison

2016-09-28 20:56 UTC, ayushin78 commented
Hi @lamagnifica!, I have emailed the required agreement.

2016-10-14 18:23 UTC, lamagnifica requested changes
Thanks for your patience, @ayushin78 . I have a few suggestions.

2016-10-14 18:23 UTC, lamagnifica commented on en_us/shared/students/sfd_discussions/add_post.rst
> +      not currently display added formatting or images.
it's not your error, but would you take the opportunity to remove the second "currently" in this sentence?

2016-10-14 18:23 UTC, lamagnifica commented on en_us/shared/students/sfd_discussions/add_post.rst
>     .. note:: Any text formatting or images that you add are only visible when
To avoid note overload, I suggest that you remove the ".. note::" here and just make this an indented paragraph. Otherwise, everyone will see a step, then a note or tip, and then another note... too many notes!

2016-10-14 18:23 UTC, lamagnifica commented on en_us/shared/students/sfd_discussions/add_post.rst
>     .. note:: Any text formatting or images that you add are only visible when
ditto request to make this an indented paragraph rather than a note.

2016-10-14 18:23 UTC, lamagnifica commented on en_us/shared/students/sfd_discussions/add_post.rst
> +       If having trouble with uploading file, please make sure that the
missing subject (If ^you are)

2016-10-14 18:23 UTC, lamagnifica commented on en_us/shared/students/sfd_discussions/add_post.rst
> +       size of file is smaller than 1 MB as there might be a maximum size limit.
missing direct object (^the file)

2016-10-14 18:23 UTC, lamagnifica commented on en_us/shared/students/sfd_discussions/add_post.rst
> +       size of file is smaller than 1 MB as there might be a maximum size limit.
It occurs to me that regardless of what the maximum size is set to be, the system does give an error message when you try to upload something that's too big. 
So maybe recast to something simpler, but with a little wiggle room as far as the exact size goes... something like one of these alternatives.

- The maximum size for an uploaded file is typically 1 MB. 
- The files that you upload must typically be no larger than 1 MB.
- Most systems limit the size of uploaded files to 1 MB.

2016-10-14 18:23 UTC, lamagnifica commented on en_us/shared/students/sfd_discussions/add_post.rst
> +       size of file is smaller than 1 MB as there might be a maximum size limit.
see above

2016-10-18 23:13 UTC, ayushin78 commented
Hi @lamagnifica, I have made some changes. Please review it.

2016-10-19 18:27 UTC, lamagnifica approved these changes

2016-10-19 18:28 UTC, lamagnifica commented
👍 thanks @ayushin78! please squash your commits and I will merge.

2016-10-19 21:15 UTC, ayushin78 commented
I am not so sure about squashing. please check if it is okay or not.

2016-10-20 14:52 UTC, shaunagm commented
Hi @ayushin78, it looks like something did go wrong with the squashing.  I think you may have accidentally squashed in one of Alison's commits along with your own commits which you meant to be squashing?

The best way to fix this is probably a hack workaround.  We could use reflog, but that seems like it might be needlessly complicated.  I recommend:

1)  Copy n_us/shared/students/sfd_discussions/add_post.rst to a separate file to save your changes.
2)  Reset the status of your local directory by typing **git reset --hard commit_hash** where the commit hash is something from git log before you made your changes.  You can find this via **git log**.
3)  Pull the most recent version of the repository.
4)  Apply your changes that you saved from the separate file.
5)  Push back to your fork.  You'll have to add the --force flag to overwrite the repo.  It should update the PR.

Let me know if you have any questions/need any help.

2016-10-21 13:33 UTC, lamagnifica commented
Congratulations @ayushin78 ! Merging.

2016-10-21 13:34 UTC, merged