[DOC-3236] - For people learning about XBlocks, test and correct directory location statements
openedx-unsupported/edx-documentation pull request #1273
Opened 2016-09-27 01:26 UTC by mehulsr

## [DOC-3236](https://openedx.atlassian.net/browse/DOC-3236)

Added a note, informing the user which directory they are currently in.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc

FYI: @shaunagm @lamagnifica 

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### Details About the Commit

I completed all the steps in these pages:
3.2 - SetUp XBlock
http://edx.readthedocs.io/projects/xblock-tutorial/en/latest/getting_started/setup_sdk.html
3.3 - Create XBlock
http://edx.readthedocs.io/projects/xblock-tutorial/en/latest/getting_started/create_first_xblock.html
3.2
At the end of third step, we are here:
xblock_development
+----- venv
+----- xblock-sdk current
The 4th (last) step in 3.2.3 is:
"Run the following command to return to the xblock_development directory, where you will perform the rest of your work."
I think that this line has no errors as the further steps in 3.3 are indeed triggered from 'xblock_development' directory itself (which we have told the user to navigate to, at the end of 3.2.3)
At this point, we are:
xblock_development current
+----- venv
+----- xblock-sdk
3.3
The first command to be run in 3.3.1 is 'xblock-sdk/bin/workbench-make-xblock'
This command is run from 'xblock_development' directory only. After successfully running this command and providing the short name and Class name, our directory structure looks like this:
xblock_development current
+----- myxblock
+----- venv
+----- xblock-sdk
3.3.2 i.e Install XBlock 'pip install -e myxblock' also works from 'xblock_development' folder and so does the further steps 3.3.3 and 3.3.4

2016-09-27 01:26 UTC, edx-webhook commented
Thanks for the pull request, @mehulsr! I've created [OSPR-1474](https://openedx.atlassian.net/browse/OSPR-1474) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-documentation/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2016-09-28 15:21 UTC, lamagnifica requested changes

2016-09-28 15:21 UTC, lamagnifica commented on en_us/xblock-tutorial/source/getting_started/setup_sdk.rst
> +
The more I read through what your research uncovered, @mehulsr , the more I think that the reported problem might have been the result of the reporter taking an unexpected path through this tutorial (maybe the person tried a few things after completing this set up your SDK section and starting the create an XBlock section). In which case, I imagine it would be easy to get lost and need more explicit information about where you are and then where you're supposed to be.
So here are my thoughts.
It seems like too much detail to reiterate the number of the step they just completed, and the section of the guide that they are currently in, here. 
Maybe just combine this sentence with the information in the previous sentence?
"When the requirements are installed, you are in the ``xblock_development`` directory which contains the ``venv`` and ``xblock-sdk`` subdirectories. You can now :ref:`create your first
 XBlock <Create Your First XBlock>`."

Then, maybe rewrite the first step in the getting_started/create_first_xblock.rst file to be more explicit?

#. Change to the ``xblock_development`` directory, which contains the ``venv`` and ``xblock-sdk`` subdirectories.

then a separate step to run the make-xblock command.

2016-09-30 11:22 UTC, mehulsr commented on en_us/xblock-tutorial/source/getting_started/setup_sdk.rst
> +
@lamagnifica Thanks for the review!
This is the approach I thought of at the beginning, but decided against it as I wasn't sure if I should alter the text at all! :smile: 
I've made a new commit with this change.

2016-09-30 12:29 UTC, mehulsr commented on en_us/xblock-tutorial/source/getting_started/setup_sdk.rst
> +
I created another PR to change the first step in the getting_started/create_first_xblock.rst file. Please find it [here](getting_started/create_first_xblock.rst).

2016-09-30 15:03 UTC, lamagnifica reviewed
Were you also going to add something to the first step in the getting_started/create_first_xblock.rst file?

2016-09-30 15:03 UTC, lamagnifica commented on en_us/xblock-tutorial/source/getting_started/setup_sdk.rst
> +When the requirements are installed, you are in the ``xblock_development`` directory which contains the ``venv`` and ``xblock-sdk`` subdirectories. You can now :ref:`create your first XBlock <Create
add comma after directory:
"...the ``xblock_development`` directory, which contains..."

2016-09-30 19:36 UTC, mehulsr commented on en_us/xblock-tutorial/source/getting_started/setup_sdk.rst
> +When the requirements are installed, you are in the ``xblock_development`` directory which contains the ``venv`` and ``xblock-sdk`` subdirectories. You can now :ref:`create your first XBlock <Create
I hadn't really thought about changing the reusable file, to be honest. :) 
I have made the change in a new commit.

2016-10-14 18:05 UTC, lamagnifica commented
👍 

Please squash your commits, and I will merge.

2016-10-21 21:44 UTC, mehulsr commented
I have squashed this commit.

2016-10-21 21:46 UTC, lamagnifica approved these changes

2016-10-21 21:52 UTC, merged