Analytics release notes for week of 2016-09-26
openedx-unsupported/edx-documentation pull request #1275
Opened 2016-09-28 18:14 UTC by thallada

Release notes for a deploy to insights and the analytics api this week.

### Date Needed (optional)

The release date for these changes is flexible, but we are aiming for within the next few days (this week).

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @dsjen 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review: @katymyw

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2016-09-28 18:23 UTC, lamagnifica requested changes

2016-09-28 18:23 UTC, lamagnifica commented on en_us/release_notes/source/2016/analytics/analytics_0928_2016.rst
> +- Add support for a "Download CSV" button to the learner roster.
Hmm. Problematic, since it is there but not turned on.

2016-09-28 18:23 UTC, lamagnifica commented on en_us/release_notes/source/2016/analytics/analytics_0928_2016.rst
> +- Bug fix: An issue with internalization prevented users with certain languages from loading graphs or tables.
sp: internationalization 
with --> of?

2016-09-28 18:23 UTC, lamagnifica commented on en_us/release_notes/source/2016/analytics/analytics_0928_2016.rst
> +- Add support for a Problem Response Report Download button.
ditto

2016-09-28 18:23 UTC, lamagnifica commented on en_us/release_notes/source/2016/analytics/analytics_0928_2016.rst
> +- New colors and alerts styles. Insights now uses some of the same UX patterns as in other edX applications.
Maybe just say that Insights now uses the pattern library?  It's not quite accurate to say it's the same as other apps, since we're all over the place with pattern library use right now.

2016-09-28 18:23 UTC, lamagnifica commented on en_us/release_notes/source/2016/analytics/analytics_0928_2016.rst
> +- Dynamically generated copyright year.
I'd strike this one since it applies only to the RTD versions of the Insights guide, and isn't really product-related

2016-09-28 18:30 UTC, thallada commented on en_us/release_notes/source/2016/analytics/analytics_0928_2016.rst
> +- Add support for a "Download CSV" button to the learner roster.
Yeah, I wasn't sure how to include these two. It's not relevant to edx.org insights users, but don't openedx installers also read these notes? I think it would be relevant for them because now they know they could enable those features. For what it's worth, I do mention these two in the github release notes, so perhaps that is enough.

2016-09-28 18:44 UTC, katymyw commented on en_us/release_notes/source/2016/analytics/analytics_0928_2016.rst
> +- Add support for a "Download CSV" button to the learner roster.
@lamagnifica how do we usually handle OSPRs that are feature-flagged off? Leave them out, or mention them and note they are feature-flagged?

2016-09-28 18:52 UTC, dsjen commented
I share @katymyw's question on whether to mention the items that are behind feature flags and not available.  Maybe we could add something to the description to say that it's not enabled.

Otherwise, LGTM!  👍

2016-09-28 19:00 UTC, lamagnifica commented on en_us/release_notes/source/2016/analytics/analytics_0928_2016.rst
> +- Add support for a "Download CSV" button to the learner roster.
Insights is unusual because we do not officially support its use (AFAIK, we've been talking about announcing it since Cypress). 
What do you all think?

2016-09-28 19:30 UTC, thallada commented on en_us/release_notes/source/2016/analytics/analytics_0928_2016.rst
> +- Add support for a "Download CSV" button to the learner roster.
I can mention that "This feature disabled by default on all installations, including edx.org."

2016-09-28 20:38 UTC, thallada commented
@lamagnifica I addressed your comments in 83f7979

2016-09-28 21:00 UTC, lamagnifica commented on en_us/release_notes/source/2016/analytics/analytics_0928_2016.rst
> +- Add support for a Problem Response Report Download button. This feature is disabled by default on all installations, including edx.org.
@katymyw  keep these two bullets?

2016-09-28 21:01 UTC, lamagnifica commented
@thallada the release can go ahead without these release notes being completed -- they will be published next week (we publish the release notes once a week).
Everything looks fine, though I'd like to get Katy's take on those two download buttons.

2016-09-28 21:43 UTC, katymyw commented on en_us/release_notes/source/2016/analytics/analytics_0928_2016.rst
> +- Add support for a "Download CSV" button to the learner roster.
@thallada I like that approach. That way the notes are more complete.

2016-09-28 21:47 UTC, katymyw commented on en_us/release_notes/source/2016/analytics/analytics_0928_2016.rst
> +- Add support for a Problem Response Report Download button. This feature is disabled by default on all installations, including edx.org.
I think it makes sense to include them, unless I'm missing a reason it would be bad to advertise them when they are currently disabled?

2016-09-28 21:58 UTC, katymyw commented on en_us/release_notes/source/2016/analytics/analytics_0928_2016.rst
> +- Accessiblity: title element updates on learner page change.
Typo: Accessiblity --> Accessibility

2016-09-29 15:21 UTC, lamagnifica approved these changes
a couple more nits (sorry!) and 👍

2016-09-29 15:21 UTC, lamagnifica commented on en_us/release_notes/source/2016/analytics/analytics_0928_2016.rst
> +- Add support for a "Download CSV" button to the learner roster. This feature is disabled by default on all installations, including edx.org.
please use bold (two asterisks) for the UI label
(sorry I didn't catch that before)

2016-09-29 15:21 UTC, lamagnifica commented on en_us/release_notes/source/2016/analytics/analytics_0928_2016.rst
> +- Add support for a Problem Response Report Download button. This feature is disabled by default on all installations, including edx.org.
what page did this get added to?
please use bold (two asterisks) for the UI label
(sorry I didn't catch that before)

2016-09-29 15:36 UTC, thallada commented on en_us/release_notes/source/2016/analytics/analytics_0928_2016.rst
> +- Add support for a Problem Response Report Download button. This feature is disabled by default on all installations, including edx.org.
No problem, addressed this and your other comment.

2016-09-29 15:42 UTC, merged