Documented the Site fields in Third Party Auth
openedx-unsupported/edx-documentation pull request #1290
Opened 2016-10-04 14:47 UTC by bdero

## [DOC-3367](https://openedx.atlassian.net/browse/DOC-3367)

This PR adds documentation for the new Site fields in light of [ENT-16](https://openedx.atlassian.net/browse/ENT-16), which is set to be in the 2016-10-04 release of edX.

The feature adds support for having different SSO providers show up on different Sites by allowing edX operators to choose which Site a given SSO provider shows up on.

### Date Needed

The merge deadline for this documentation update is October 7th, 2016.
Support for specifying the Site for TPA providers/SAML Configurations is set to be in the 2016-10-04 release of edX.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @douglashall 
- [ ] Doc team review (sanity check): @edx/doc

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.

2016-10-04 14:47 UTC, edx-webhook commented
Thanks for the pull request, @bdero! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=1290&repo=edx%2Fedx-documentation

2016-10-04 21:05 UTC, lamagnifica commented
@bdero I think we need to make sure that the information about third party authentication applying to individual sites is consistently presented throughout this section. For example, the index.rst opening paragraph reads:

> To enhance sign in options for your users, you can enable third party
> authentication between institutional authentication systems and your
> implementation of the edX platform. After you enable third party
> authentication, users can register and sign in to your Open edX site with their
> campus or institutional credentials.

If we revise (and improve!) the current wording to reflect the new concept of sites, it might read something like this:

> To enhance sign in options for your users, you can enable third party
> authentication between institutional authentication systems and the sites 
> that you define for your Open edX installation. After you enable third party
> authentication, users can register and sign in to your Open edX site with their
> campus or institutional credentials.

Similarly, the tpa_providers.rst file, 2nd sentence, might need to change to restate

> Your implementation of the Open edX platform is the service provider that allows
> the users access on the basis of credentials sent by an identity provider.

to 

> Your Open edX site is the service provider that allows the users access on 
> the basis of credentials sent by an identity provider.

etc. through all of the files in this section. Currently a mixture of "implementation", "installation", and "site" are all being used to mean (I think) the same thing: the one and only Open edX instance that used to be configured for third party auth, whereas now you must do the configuration site by site.

Does that make sense? I'm not entirely sure that I understand the site-specific configuration changes, but I think that they mean that the all of the files in this section need to be reviewed for the types of changes I suggest above.

2016-10-05 17:09 UTC, bdero commented
Thanks for your review @lamagnifica! That makes sense, I'll take a pass through and make sure it's clear that it's per-site, not installation. I also added made a new PR against this week's release notes about this change: https://github.com/edx/edx-documentation/pull/1291

2016-10-05 18:26 UTC, bdero commented
@lamagnifica I amended the commit to add the requested changes. Let me know this seems good!

2016-10-05 20:50 UTC, lamagnifica requested changes
I'v given you pretty much all nits, like capitalization changes and a couple of suggested rewordings. Thanks @bdero !

2016-10-05 20:50 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/index.rst
> +authentication between institutional authentication systems and the Sites you
please use sentence capitalization and make "sites" lower case throughout

2016-10-05 20:50 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_IdP.rst
> +   - **Site**: Choose which Open edX site this IdP will be usable with. Each
"will be usable with" is a bit awkward. Maybe,
"Select the site that you are configuring to use this IdP."

2016-10-05 20:50 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_SP.rst
> +Configuring your Open edX site as a SAML Service Provider
ok, funnily enough, in this case "Site" should have an initial capital

2016-10-05 20:50 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_SP.rst
> +Configure your Open edX site as a Service Provider
capitalize "Site"

2016-10-05 20:50 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_SP.rst
> +    provider, next to **SAML Configuration** select **Change**, and then
an existing service provider --> an existing site (?)

2016-10-05 20:50 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_SP.rst
> +    select **Update** for the provider that you want to configure.
provider --> site (?) though I'm not sure what the UI looks like -- does it list the site names?

2016-10-05 20:50 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_SP.rst
> +    Sites in Open edX, see :ref:`Configuring Open edX Sites`.
lower case service provider and sites (but not the name of the field, that's perfect!)

2016-10-05 20:50 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_SP.rst
> +  - **Site**: Choose which site this SAML Service Provider is for. There can
maybe,
Specify the site that you are configuring to be a SAML service provider. (?)

2016-10-05 20:50 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
> +institutions. When you configure the open edX site to be a service
oops, missed capitalizing "Open" (not your error)

2016-10-05 20:50 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
> +.. replace the following para with the above para when ready to add OAuth2
thanks for updating the comments!

2016-10-05 21:49 UTC, bdero commented on en_us/install_operations/source/configuration/tpa/index.rst
> +authentication between institutional authentication systems and the Sites you
Done.

2016-10-05 21:49 UTC, bdero commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_IdP.rst
> +   - **Site**: Choose which Open edX site this IdP will be usable with. Each
That seems much better, thanks. Done.

2016-10-05 21:49 UTC, bdero commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_SP.rst
> +Configuring your Open edX site as a SAML Service Provider
Done.

2016-10-05 21:49 UTC, bdero commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_SP.rst
> +    provider, next to **SAML Configuration** select **Change**, and then
Although technically "service providers" correlate with sites in this case, I think it makes sense to say "service provider" here because it's explicitly talking about service provider entries in the admin panel. Do you think it makes sense to leave it as-is?

2016-10-05 21:49 UTC, bdero commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_SP.rst
> +    select **Update** for the provider that you want to configure.
It does list the site names in one of the columns, but ultimately it's talking about configuring service provider entries, even though they're technically per-site. It seems like the least confusing thing is to leave it as-is here. Does that make sense?

2016-10-05 21:49 UTC, bdero commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_SP.rst
> +  - **Site**: Choose which site this SAML Service Provider is for. There can
I think your suggestion makes sense and is less confusing. It really brings the point home that there's a strict one-to-one relationship here. I've changed it to:

> Specify the site that you are configuring to be a SAML service provider.

Thanks!

2016-10-05 21:49 UTC, bdero commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
> +institutions. When you configure the open edX site to be a service
Done.

2016-10-05 21:50 UTC, bdero commented
Thanks for the continued review @lamagnifica - I've addressed all comments and this is ready for another pass!

2016-10-05 23:56 UTC, douglashall commented
👍 Thanks @bdero!

2016-10-07 12:43 UTC, bdero commented
@lamagnifica Does this look good to merge for you now? I'd like to merge it this week as it's in the current sprint.

2016-10-07 13:20 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_IdP.rst
> +URL of your metadata file, created when you :ref:`configured your Open edX Site
lower case "site"

2016-10-07 13:21 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_IdP.rst
> +     IdP can only belong to one Site at a time. For more information about
lc "site"

2016-10-07 13:21 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_IdP.rst
> +     Sites in Open edX, see :ref:`Configuring Open edX Sites`.
lc "sites"

2016-10-07 13:22 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_SP.rst
> +    provider, next to **SAML Configuration** select **Change**, and then
great, thanks

2016-10-07 13:22 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_SP.rst
> +    select **Update** for the provider that you want to configure.
good

2016-10-07 13:22 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_SP.rst
> +    information about Sites in Open edX, see :ref:`Configuring Open edX Sites`.
lc "sites"

2016-10-07 13:23 UTC, lamagnifica commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
> +edX Site is the service provider that allows the users access on the basis of credentials sent by an identity provider.
lc "site"

2016-10-07 13:23 UTC, bdero commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_IdP.rst
> +     Sites in Open edX, see :ref:`Configuring Open edX Sites`.
I thought this was supposed to be capitalized because it's a section title?

2016-10-07 13:24 UTC, lamagnifica commented
this looks great, @bdero . If you wouldn't mind taking the time to lower case (lc) "site" that would be the finishing touch!

2016-10-07 13:26 UTC, bdero commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_IdP.rst
> +URL of your metadata file, created when you :ref:`configured your Open edX Site
Done.

2016-10-07 13:26 UTC, bdero commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_IdP.rst
> +     IdP can only belong to one Site at a time. For more information about
Done.

2016-10-07 13:26 UTC, bdero commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_SP.rst
> +    information about Sites in Open edX, see :ref:`Configuring Open edX Sites`.
Done

2016-10-07 13:26 UTC, bdero commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
> +edX Site is the service provider that allows the users access on the basis of credentials sent by an identity provider.
Done

2016-10-07 13:26 UTC, bdero commented on en_us/install_operations/source/configuration/tpa/tpa_SAML_IdP.rst
> +     Sites in Open edX, see :ref:`Configuring Open edX Sites`.
I changed this in the meantime ;) Done.

2016-10-07 13:27 UTC, bdero commented
I lowercased all of the "Sites" you've caught and pushed @lamagnifica. This is ready for another pass. :)

2016-10-07 13:39 UTC, lamagnifica commented
Yeah, the cross references can be super confusing. The "anchor" should appear exactly the way it is defined (by the ..  _text: formatting above the actual section heading). If you want the section title to appear as the link, you just use that anchor in your :ref:, like, "For more information, see :ref:`Integrating with a SAML Identity Provider`." which renders as "For more information, see _Integrating with a SAML Identity Provider_."

BUT, if you want the link to look like it's just part of the sentence, you provide both the phrase you want to link and the anchor within the < > characters, like "created when you :ref:`configured your Open edX site as a SAML service provider<Configuring your Installation as a SAML Service Provider>`", which renders as "created when you _configured your Open edX site
 as a SAML service provider_"

Anyway, 👍 squash and I will merge and publish!

2016-10-07 13:40 UTC, lamagnifica commented
ok, you already squashed. I can't figure out how to make GitHub let me change my original review to "approved"...

2016-10-07 13:41 UTC, lamagnifica approved these changes

2016-10-07 13:41 UTC, merged

2016-10-07 13:55 UTC, lamagnifica commented
Live! http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/tpa/index.html

2016-10-07 16:00 UTC, bdero commented
@lamagnifica Thanks for the clarification on the titles as links + the merge. :)