Update enable_themes.rst
openedx-unsupported/edx-documentation pull request #1302
Opened 2016-10-12 20:15 UTC by saadataz

Added an example scenario to make things clear

2016-10-12 20:15 UTC, edx-webhook commented
Thanks for the pull request, @saadataz! I've created [OSPR-1505](https://openedx.atlassian.net/browse/OSPR-1505) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-documentation/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2016-10-13 12:39 UTC, gsong commented
@saadataz Thank you for your PR. We appreciate you taking the time to make the contribution.

Please submit a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf) to us so we can review this pull request. We realize it's additional work for a simple change in this case, but you only have to do this *once* and we're hoping you would make future contributions as well.

2016-10-17 17:47 UTC, saadataz commented
@gsong I have sent the contributor agreement to legal@edx.org
Do I need to do anything else?

Thanks,

2016-10-17 19:51 UTC, gsong commented
@saadataz Not currently. We'll let you know when you've been added to the potential contributor list.

2016-10-26 17:07 UTC, nedbat commented
@saadataz We haven't seen your agreement yet.  I'll check with people on this end, but are you sure it sent properly?

2016-10-26 17:21 UTC, saadataz commented
@nedbat I have signed the contributor agreement and received the confirmation from Lizzy Desrosiers (edX | Legal and Finance Coordinator). Do I need to sign anything else?

2016-10-27 17:35 UTC, nedbat commented
@saadataz thanks, I found the agreement, you are all set on that front.

2016-10-28 19:05 UTC, nedbat requested changes

2016-10-28 19:05 UTC, nedbat commented on en_us/install_operations/source/configuration/changing_appearance/theming/enable_themes.rst
> +----------------------------------------
This heading style makes a really deep heading ("4.3.1.4.1.1. Example Settings for Comprehensive Theme"). If you use the same heading style as is already in this file, it will stay a 5-level numbered heading.

2016-10-28 19:05 UTC, nedbat commented on en_us/install_operations/source/configuration/changing_appearance/theming/enable_themes.rst
> +  "COMPREHENSIVE_THEME_DIRS": [
This is a very minor nit, but if you can, please indent this code sample to a 4-space indent. Thanks.

2016-10-28 19:05 UTC, nedbat commented on en_us/install_operations/source/configuration/changing_appearance/theming/enable_themes.rst
> +.. code::
Use `.. code-block::` instead of `.. code:`, to get consistent styling with the rest of the page.

2016-11-04 00:21 UTC, saadataz commented
Thanks for the input @nedbat

2016-11-04 23:41 UTC, saadataz reviewed
fixed build failing due to incorrect code-block syntax

2016-11-08 10:22 UTC, merged

2016-11-08 10:22 UTC, nedbat commented
@saadataz Thanks for the fixes! Merged!