Add documentation for E-Commerce service receipt page
openedx-unsupported/edx-documentation pull request #1315
Opened 2016-10-17 16:21 UTC by srpearce

## [DOC-3436](https://openedx.atlassian.net/browse/DOC-3436)

Add documentation to enable the receipt page in the E-Commerce service.

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @marjev 
- [ ] Subject matter expert: @mjfrey 

@marjev and @mjfrey , I've taken a stab at adding documentation for the receipt page, but I'm missing some information. Please review this PR and add comments with the missing information, and let me know if the introductory sentence ("The E-Commerce service includes a receipt page that you can display to users after their orders are complete.") is accurate.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2016-10-18 08:44 UTC, marjev reviewed
@srpearce I've reviewed your changes.

Let me know if you need more context/screenshots or anything else that would help you with this PR.

2016-10-18 08:44 UTC, marjev commented on en_us/install_operations/source/ecommerce/enable_receipt_page.rst
> +   ``http://{your_URL}/admin``.
This document resides within ecommerce documentation, but we enable the ecommerce Receipt Page from the LMS Django Administration console. Perhaps we should make sure that's clear to anyone who's reading this.

Otherwise, users might go to the ecommerce Django Administration console, only to find out they are in the wrong place.

2016-10-18 08:44 UTC, marjev commented on en_us/install_operations/source/ecommerce/enable_receipt_page.rst
> +   **Change**.
Unfortunately, changing is not enabled. Users will only be able to Add new Commerce Configuration. Values will be imported from the previously created Commerce Configuration. By adding the new Configuration, a user is rendering previously created Configurations useless.

Here's a screenshot showing my current Configuration values:
<img width="670" alt="screen shot 2016-10-18 at 09 48 33" src="https://cloud.githubusercontent.com/assets/6833568/19468747/5eec240a-9518-11e6-8154-4f9db296694f.png">

2016-10-18 08:44 UTC, marjev commented on en_us/install_operations/source/ecommerce/enable_receipt_page.rst
> +#. On the **PAGE NAME** page, locate **Commerce**.
PAGE NAME is `Site Administration`. It's the page a user will be redirected to once logged into the system.

2016-10-18 08:44 UTC, marjev commented on en_us/install_operations/source/ecommerce/enable_receipt_page.rst
> +#. On the **PAGE NAME** page, locate **Site Configuration**, and then select
PAGE NAME is `Site administration`.
To be consistent with the text you wrote above, we should say:
```
locate **Site_Configuration**.
In the **Site_Configuration** section, next to **Site configurations**, select
 **Change**.
```
See the following screenshot:
<img width="579" alt="screen shot 2016-10-18 at 10 28 30" src="https://cloud.githubusercontent.com/assets/6833568/19469914/afda7074-951d-11e6-920c-d1073a85dc5f.png">

2016-10-18 08:44 UTC, marjev commented on en_us/install_operations/source/ecommerce/enable_receipt_page.rst
> +#. Select **Save**. You return to the **PAGE NAME** page.
PAGE NAME is `Site administration`.

2016-10-18 08:44 UTC, marjev commented on en_us/install_operations/source/ecommerce/enable_receipt_page.rst
> +
Should we mention that the value should be in JSON format?
See the following screenshot:

<img width="753" alt="screen shot 2016-10-18 at 10 30 39" src="https://cloud.githubusercontent.com/assets/6833568/19469974/f7053f9c-951d-11e6-9cff-2fda12584d59.png">

Notice the curly brackets.

2016-10-20 17:51 UTC, srpearce commented
Hi @marjev - I've made changes based on your feedback. Would you mind doing another tech review?

2016-10-21 07:35 UTC, marjev commented
Thanks @srpearce!
LGTM

2016-10-21 15:37 UTC, srpearce commented
Thanks, @marjev !

@edx/doc , this PR is ready for edit review. The feature is expected to merge in the next couple of weeks.

2016-10-25 07:25 UTC, marjev requested changes
@srpearce I know that I gave you an approval on this from the technical perspective, but we might make additional changes to our PR.

I'll let you know once our PR is merged so that we don't have to go back and forth between this PR and the one I'm working on.

Let's hold on a little longer before we merge this one.

2016-10-25 14:00 UTC, srpearce commented
@marjev OK, cool. I wasn't planning on merging this until the feature is released, so I'll keep my eyes open for changes.

2016-11-07 09:50 UTC, marjev commented on en_us/install_operations/source/ecommerce/enable_receipt_page.rst
> +
@srpearce: There's been a change in my PR so everything between the lines 26-37 (both included) is no longer needed. You can remove that.

A user will only need to configure Site Configuration by adding an `ECOMMERCE_RECEIPT_PAGE_URL`, for now. I'll let you know if any other changes are introduced.

2016-11-08 16:03 UTC, srpearce commented
@catong Can I get your eyes on this PR? The feature hasn't merged yet but should soon.

2016-11-08 20:40 UTC, catong commented on en_us/install_operations/source/ecommerce/enable_receipt_page.rst
> +To enable the default receipt page for the E-Commerce service, follow these
Elsewhere do we provide instructions to customize the default page? If we don't provide any options for customizing, I'd suggest striking "default" here so that hopes aren't raised. Otherwise, provide a sentence/xref pointing to doc for customizing or modifying the default receipt page.

2016-11-08 20:47 UTC, catong commented
@srpearce Just one question from me, but is there still one unaddressed review comment about clarifying that Django Admin should be accessed from the LMS? If there are further Dev changes to come pls tag me for final review.

2016-11-09 08:00 UTC, marjev approved these changes

2016-11-10 17:56 UTC, srpearce commented on en_us/install_operations/source/ecommerce/enable_receipt_page.rst
> +   ``http://{your_URL}/admin``.
Thanks, @marjev - I'm not sure exactly what you mean. Is the LMS Django admin console not located at ``http://{your_URL}/admin``? Can you suggest a revision of step 1 that would be more clear? For example, should this step read something like this?

Sign in to the LMS Django administration console for your base URL. For example, ``http://{URL_of_your_LMS_instance}/admin``.

2016-11-11 07:55 UTC, marjev commented on en_us/install_operations/source/ecommerce/enable_receipt_page.rst
> +   ``http://{your_URL}/admin``.
Yes, that's what I meant, making sure that a reader knows which admin site he has to visit.

Otherwise, since this is located in the ecommerce section of the documentation (notice the URL `ecommerce/enable_receipt_page.rst`), a reader might think he needs to add this in the ecommerce Django Admin and not the LMS one.

2016-12-19 08:58 UTC, marjev commented
@srpearce The receipt page PR has been merged, which means this can be merged as well.
Let me know if you need anything else here. Thanks!

2016-12-20 16:41 UTC, srpearce commented
Thanks, @marjev . @mjfrey , IIRC, since this feature didn't go out this week and there's not an official release next week, this feature will be live on January 4. Can you confirm?

2017-05-22 07:55 UTC, marjev commented
@mjfrey Should this PR be merged? Receipt page is live now, right?

2017-08-29 19:14 UTC, srpearce commented
@mjfrey Is the receipt page live, and is this information still accurate? If so, I can publish this.

2017-08-29 19:16 UTC, mjfrey commented
@srpearce Yes it is live and the default.

2017-08-29 19:17 UTC, merged