DOC-3479 - Ability to remove opt-out for proctored exams
openedx-unsupported/edx-documentation pull request #1338
Opened 2016-11-03 17:03 UTC by catong

## [DOC-3479](https://openedx.atlassian.net/browse/DOC-3479)

This PR adds a topic to the course author's guide to explain the new ability to remove opt-out options for proctored exams.

### Date Needed: Nov 8 release

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @andy-armstrong 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @srpearce 
- [ ] Product review: @marcotuts 

FYI
@jaakana, @dhixonedx, @jhendersonedx, @mmacfarlane

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2016-11-03 17:53 UTC, JAAkana commented on en_us/course_authors/source/course_features/credit_courses/proctored_exams.rst
> +
Some questions for product: I'd like to understand more about the secondary consequences of setting "Allow Option Out" = false. It seems like this option should only be toggled if a course is exclusively verified-only or prof-ed, otherwise the verified students encounter a block that audit students can work around.

+ Will verified, credit-eligible students be unable to complete the assignment if they don't do the proctoring, while audit students just take the exam as usual? 

+ If a verified, credit-eligible student doesn't take the proctored exam, but still passes the course based on other assignments, will they be dq'ed from the verified or credit?

2016-11-03 19:14 UTC, catong commented on en_us/course_authors/source/course_features/credit_courses/proctored_exams.rst
> +
@marcotuts Can you pls comment?

2016-11-07 14:52 UTC, marcotuts commented on en_us/course_authors/source/course_features/credit_courses/proctored_exams.rst
> +
A verified student will only be able to continue through to proctoring, and audit students will continue to see the exam as usual. This option eliminates the option to switch down to the audit visible / open exam for verified learners. 

In the second case, they can meet skip this proctored exam and still have a high enough grade for a verified certificate, but having not passed the proctored exam wouldn't meet the credit requirement.

2016-11-07 22:48 UTC, catong commented
@andy-armstrong Can you please review? Thanks!

2016-11-08 01:22 UTC, andy-armstrong requested changes
@catong this is excellent, but needs tweaking to distinguish the behavior for audit and verified track learners.

2016-11-08 01:22 UTC, andy-armstrong commented on en_us/course_authors/source/course_features/credit_courses/proctored_exams.rst
> +By default, learners in courses with proctored exams can opt out of taking
This section needs updating in light of the details from @marcotuts. This paragraph as written only applies to verified track learners. There probably needs to be an introduction describing how audit track learners are treated.

2016-11-08 01:22 UTC, andy-armstrong commented on en_us/course_authors/source/course_features/credit_courses/proctored_exams.rst
> +If you do not want to give learners in your course the choice of taking
This could be "If you do not want to give verified learners..."

2016-11-08 14:52 UTC, catong commented
@andy-armstrong Updated - please re-review.

2016-11-08 15:07 UTC, srpearce approved these changes

2016-11-08 15:07 UTC, srpearce commented on en_us/course_authors/source/course_features/credit_courses/proctored_exams.rst
> +To remove the option for verified learners to opt-out of proctored exams in
No hyphen

2016-11-08 15:07 UTC, srpearce commented on en_us/course_authors/source/course_features/credit_courses/proctored_exams.rst
> +proctored    exams without proctoring.
spacing?

2016-11-08 15:07 UTC, srpearce commented on en_us/course_authors/source/course_features/credit_courses/proctored_exams.rst
> +**Advanced Settings** in Studio.
... on the **Advanced Settings** page

2016-11-08 15:16 UTC, catong commented on en_us/course_authors/source/course_features/credit_courses/proctored_exams.rst
> +proctored    exams without proctoring.
I just fixed this line wrap, which was affecting numbering too.

2016-11-08 15:46 UTC, andy-armstrong approved these changes
👍  looks great, @catong. One minor nit that you can feel free to ignore.

2016-11-08 15:46 UTC, andy-armstrong commented on en_us/course_authors/source/course_features/credit_courses/proctored_exams.rst
> +By default, verified learners can opt out of taking proctored exams with
Nit: is there a way to use the word proctored fewer times in this paragraph. It makes it a little hard to parse, at least for me.

2016-11-08 15:52 UTC, catong commented on en_us/course_authors/source/course_features/credit_courses/proctored_exams.rst
> +By default, verified learners can opt out of taking proctored exams with
@andy-armstrong I wrestled with that too :-). It didn't seem accurate to just say "take exams with proctoring" because it is specifically proctored exams that have a proctoring requirement. Let me think about it and see what can be done.

2016-11-08 16:23 UTC, catong commented
Merging https://github.com/edx/edx-documentation/pull/1338

2016-11-08 16:23 UTC, merged