Update for Peer Rationale Reflection Tool
openedx-unsupported/edx-documentation pull request #1354
Opened 2016-11-23 20:12 UTC by jleong-openedx

## [DOC-3502](https://openedx.atlassian.net/browse/DOC-3502)

Update documentation for the 0.6 release of the Peer Instruction Tool, now known as the Peer Rationale Reflection Tool. Pull request for code changes [here](https://github.com/edx/edx-platform/pull/14041).

### Date Needed

Hopefully the documentation changes can be accepted along with the code changes by January 2017 in time for the start of term.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Doc team review (copy edit): @shaunagm, @catong 

FYI: @sstack22 

### Testing

- [x] Executed ./run_tests.sh without any errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.

Change name from Peer Instruction to Peer Rationale Reflection. Also
update screenshots and describe scenario with no correct answer.

2016-11-23 20:12 UTC, edx-webhook commented
Thanks for the pull request, @jleong-openedx! I've created [OSPR-1598](https://openedx.atlassian.net/browse/OSPR-1598) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-documentation/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2016-12-09 18:15 UTC, catong requested changes
@jleong-openedx Just minor edits. Thanks!

2016-12-09 18:15 UTC, catong commented on en_us/shared/exercises_tools/peer_rationale_reflection_tool.rst
> +concepts. The Peer Rationale Reflection Tool emulates this classroom experience for the
@jleong-openedx Lowercase for the name of tools: "The peer rationale reflection tool..."

2016-12-09 18:15 UTC, catong commented on en_us/shared/exercises_tools/peer_rationale_reflection_tool.rst
> +Assignments created with the Peer Rationale Reflection Tool present learners with a
Lowercase tool name throughout, please

2016-12-09 18:15 UTC, catong commented on en_us/shared/exercises_tools/peer_rationale_reflection_tool.rst
> + For more information about how learners experience Peer Rationale Reflection
No initial caps for "Peer Rationale Reflection"

2016-12-09 18:15 UTC, catong commented on en_us/shared/exercises_tools/peer_rationale_reflection_tool.rst
> +page. (Be sure to include the quotation marks around the key value.) For more
This was in the existing doc, but no need for parentheses and strike "the" before "quotation marks": "...on the **Advanced Settings** page. Be sure to include quotation marks around the key value."

2016-12-09 18:15 UTC, catong commented on en_us/shared/exercises_tools/peer_rationale_reflection_tool.rst
>  The Peer Instruction learning system provides students with in class
@jleong-openedx Should this intro still say "Peer Instruction learning system"?

2016-12-09 18:15 UTC, catong commented on en_us/shared/exercises_tools/peer_rationale_reflection_tool.rst
> +   .. image:: ../../../shared/images/peer_rationale_reflection_studio.png
@jleong-openedx This image seems very faint/greyed out. If you have a better image, please substitute it.

2016-12-09 18:15 UTC, catong commented on en_us/shared/exercises_tools/peer_rationale_reflection_tool.rst
> +Before you add the details of the assignment to a Peer Ratioanle Reflection
typo: "Rationale". (Also remove initial caps)

2016-12-09 18:39 UTC, jleong-openedx commented on en_us/shared/exercises_tools/peer_rationale_reflection_tool.rst
>  The Peer Instruction learning system provides students with in class
Yes, as that is the method that the Peer Rationale Reflection Tool (PRRT) is based upon, not our tool itself.

2016-12-09 18:57 UTC, jleong-openedx commented on en_us/shared/exercises_tools/peer_rationale_reflection_tool.rst
> +concepts. The Peer Rationale Reflection Tool emulates this classroom experience for the
This is now corrected.

2016-12-09 18:57 UTC, jleong-openedx commented on en_us/shared/exercises_tools/peer_rationale_reflection_tool.rst
> +Assignments created with the Peer Rationale Reflection Tool present learners with a
This is now corrected.

2016-12-09 18:58 UTC, jleong-openedx commented on en_us/shared/exercises_tools/peer_rationale_reflection_tool.rst
> + For more information about how learners experience Peer Rationale Reflection
This is now corrected.

2016-12-09 18:58 UTC, jleong-openedx commented on en_us/shared/exercises_tools/peer_rationale_reflection_tool.rst
> +page. (Be sure to include the quotation marks around the key value.) For more
This is now corrected.

2016-12-09 18:59 UTC, jleong-openedx commented on en_us/shared/exercises_tools/peer_rationale_reflection_tool.rst
> +   .. image:: ../../../shared/images/peer_rationale_reflection_studio.png
I don't believe we can generate a better image, but we will keep this in mind and replace it if we can.

2016-12-09 18:59 UTC, jleong-openedx commented on en_us/shared/exercises_tools/peer_rationale_reflection_tool.rst
> +Before you add the details of the assignment to a Peer Ratioanle Reflection
This is now corrected.

2016-12-09 19:00 UTC, jleong-openedx commented
Thank you @catong for the feedback and corrections; please see the latest commit.

2016-12-09 19:03 UTC, catong approved these changes

2016-12-09 19:04 UTC, catong commented
@jleong-openedx Thank you! This doc PR is now ready to be merged when the corresponding code PR merges.

2016-12-09 19:04 UTC, catong commented
Oh, please squash commits.

2016-12-09 19:07 UTC, jleong-openedx commented
Okay, thank you @catong ; should I keep the update to AUTHORS as a separate commit (as stated [here](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst))?

2016-12-09 19:16 UTC, catong commented
@jleong-openedx Sure, keep the AUTHORS update as a separate commit. Thanks!

2016-12-09 19:44 UTC, jleong-openedx commented
I have just squashed the commits, and kept the AUTHORS update as a separate commit. Thank you @catong!

2016-12-14 22:51 UTC, jleong-openedx commented
Hi @catong, I have just updated this to revert Peer Rationale Reflection to Peer Instruction, as a decision has been made to stay with the old name for now.

2016-12-15 15:35 UTC, catong commented
Thank you for the update, @jleong-openedx.

2017-02-07 19:39 UTC, gsong commented
Waiting for associated PRs to complete.

2017-02-24 17:04 UTC, gsong commented
@catong FYI, the corresponding PR edx/edx-platform#14041 will be merged soon, so you'll want to keep an eye out for it.

2017-02-24 17:07 UTC, catong commented
Thanks @gsong, will do.

2017-02-28 15:50 UTC, catong commented
Merging https://github.com/edx/edx-documentation/pull/1354

2017-02-28 15:50 UTC, merged

2017-02-28 20:56 UTC, jleong-openedx commented
Thank you @catong!