mattdrayer/ENT-141: Update TPA/SSO documentation
openedx-unsupported/edx-documentation pull request #1389
Opened 2017-01-13 15:28 UTC by mattdrayer

## [ENT-141](https://openedx.atlassian.net/browse/ENT-141)

This is a first-pass at incorporating the updated Third Party Authentication / Single Sign-On information provided by OpenCraft into the Installation and Configuration area of the Open edX documentation.  I'm assuming that the final cut will be significantly different than what is being submitted in the initial commit, so let the revising begin!

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @bradenmacdonald 
- [ ] Subject matter expert: @fredsmith 
- [ ] Subject matter expert: @kashifch
- [ ] Doc team consultant (sanity check, copy edit, or dev edit?): @edx/doc @srpearce 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2017-01-18 03:28 UTC, bradenmacdonald requested changes
Thanks for this, @mattdrayer! I left some suggestions. I believe all the technical content is accurate, so it's just a question of presentation and tone. I wrote this with a more informal voice since I assumed someone would be "translating" it. 

We may also want to document how to debug SAML integrations here, but that can be done separately.

2017-01-18 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +    These providers are part of the `external_auth` app, tend to be older and less robustly tested (each one was more or less put together for the use of one specific institution), and have a much mo
This sentence was not meant to be published in the docs - let's replace with "These providers are included in the source code but are not officially supported" or something like that?

2017-01-18 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +* The rest of this technical write-up will focus only on the OAuth2, SAML, and LTI providers.
Probably don't need the two final bullet points here ^ ("People..." and "The rest...")

2017-01-18 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +Part 1: Background / Notes
I think it makes sense to combine this information into `tpa_providers.rst` (http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/tpa/tpa_providers.html). Both describe what identity providers are supported. This one has more detail, while that one has a lot more context and actually explains what third party auth is.

2017-01-18 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +* The user information that is passed from the external authentication provider (e.g. Google) to Open edX varies depending on the provider (Google vs Facebook vs MIT SAML vs UBC SAML). Some providers
I'm not sure if mentioning MIT and UBC here as examples is clear. Thoughts?

2017-01-18 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +* When creating an account with SSO, the password field on the registration form is hidden. User accounts created via SSO will have a `random, highly secure password <https://github.com/edx/edx-platf
I don't think we should generally be linking to code from the published documentation, even if I personally find it helpful.

2017-01-18 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +* To be able to login with an external provider (e.g. Google), the user's Open edX account must be "linked" to that provider. e.g. if a user's account is linked to Google, then the uesr can click the
Replace "e.g." with "For example, " (?) and fix the typo ("uesr")

2017-01-18 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +   * For "Application type", select "Web application".
There's an rst formatting issue here, and these sub-bullets are not showing up as an indented list. Same thing in many places below.

2017-01-18 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +SAML provider setup is `already well-documented <http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/tpa/index.html>`_.
This part was not meant to be published. The various OAuth2 examples should be moved to their own file(s), this "Part 4" section should be removed ("4.17.3. Configuring your Open edX Site as a SAML Service Provider" in `tpa_SAML_SP.rst` and 
and "4.17.4. Integrating with a SAML Identity Provider" in `tpa_SAML_IdP.rst` cover it), and "Personal Information Using SAML" should be its own rst file ("4.17.5 Personal Information Using SAML")

2017-01-18 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +Here is some information regarding how Personal Information is involved when using SAML, and how universities can manage that.
How about something more like: "Universities and businesses that use SAML to integrate their identity providers with Open edX need to understand what personal information is provided to Open edX when users login using SAML."

2017-01-18 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +* The user ID will be saved as it is required to match future login attempts to the correct user account. The full name ("John Smith") and email ("jsmith@school.edu") will be pre-filled on the regist
There should be a comma after "saved" - "The user ID will be saved, as it is..."

2017-01-18 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +* The user ID will be saved as it is required to match future login attempts to the correct user account. The full name ("John Smith") and email ("jsmith@school.edu") will be pre-filled on the regist
Also needs a period at the end of the parenthetical sentence.

2017-01-18 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +* For universities that wish to avoid sending any personally identifiable information to Open edX during the SAML login/registration process, we recommend that the university configure their SAML ide
Stray round bracket at the end of this line.

2017-01-18 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +Part 6: Advanced SSO Features
This should also become its own .rst file

2017-01-18 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +The full behavior is somewhat complicated. Here's an explanation of the parameters than can be included:
Not sure it's useful to say "The full behavior is somewhat complicated."

2017-01-18 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +Here is Pan Luo's description of that feature, from `the original pull request <https://github.com/edx/edx-platform/pull/9842>`_:
We should just incorporate this text into the documentation, rather than quoting it, if that's ok with @xcompass

2017-01-18 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +Third Party Auth ID mapping API
I think this section should be in its own file, or move to the edX API docs (with a link from here to there).

2017-01-18 05:21 UTC, xcompass commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +Here is Pan Luo's description of that feature, from `the original pull request <https://github.com/edx/edx-platform/pull/9842>`_:
Sounds good. :)

2017-01-18 17:36 UTC, srpearce commented
@mattdrayer @bradenmacdonald Thanks for the work on this so far! I'll be working on it this afternoon and tomorrow and will let you know if I have any questions.

2017-01-18 19:09 UTC, mattdrayer commented
Excellent -- I'm happy to make any necessary revisions or structural changes, just let me know what they should be

2017-01-18 20:22 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +Part 1: Background / Notes
@bradenmacdonald by "this information" do you mean the entire document or just Part 1?

2017-01-19 18:43 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/sso.rst
> +Part 1: Background / Notes
@mattdrayer  Just Part 1

2017-01-25 22:56 UTC, srpearce reviewed
@bradenmacdonald and @mattdrayer : Here's my stab at reorganization. To make reviewing in context easier, I created a built version of this section at http://draft-enterprise-sso.readthedocs.io/en/latest/configuration/tpa/index.html. 

I've included several questions and comments inline. A couple of global things:

* I moved all of the contents of the original sso.rst file into different files.

* This is a structural edit; I haven't gone through and done a formatting or copy editing pass yet. You'll probably see a decent amount of clunky text and formatting problems. These will be fixed in the next pass, which I'll probably do tomorrow while you're looking over the overall structure.

* I'm not sure what to do with the "Configuring your Open edX Site as a SAML Service Provider" topic. If you can see where it logically fits, please let me know.

2017-01-25 22:56 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/enable_tpa_open.rst
> -.. _Enable the Third Party Authentication Feature:
The contents of this file moved.

2017-01-25 22:56 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_advanced_features.rst
> +Intro text
Any suggestions for intro text here?

2017-01-25 22:56 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +****************************
This was originally "Part 5: In depth: Personal Information using SAML". I didn't change the text, but I moved it to the "Eliminating PII" topic. Please let me know if that makes sense.

2017-01-25 22:56 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/index.rst
> +.. _Integrate TPA in Open edX:
Please let me know if the organization of this file and the two "set up a provider" files is effective.

2017-01-25 22:56 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +.. _Integrating with an OAuth2 Identity Provider:
Please comment on the organization of this file, especially. I tried to get rid of a lot of the repetition from the original instructions. The basic structure is:

* Integrate with an edX supported provider (also, please suggest something better than "edX supported provider")

  1. Create the provider app
       * Google
       * Facebook
       * LinkedIn
       * Azure

  2. Configure the LMS (please suggest a better description for this step - "Configure the Open edX instance", maybe?)

* Integrate with Other Providers

    (steps)

2017-01-25 22:56 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +:ref:`Other Providers`.
Feel free to suggest improvements to this introduction.

2017-01-25 22:56 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +EdX Supported Providers
I don't want to imply that other providers *aren't* supported, but this is all I could come up with on the fly—please suggest a better heading here.

2017-01-25 22:56 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +Configure the LMS
Again, this is probably inaccurate—please suggest a better heading that describes this set of steps.

2017-01-27 03:11 UTC, bradenmacdonald commented
@srpearce Awesome, thanks! I likely won't get to this until early next week but I'm looking forward to reading through then :)

2017-01-31 01:18 UTC, xcompass commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +Here is Pan Luo's description of that feature, from `the original pull request <https://github.com/edx/edx-platform/pull/9842>`_:
Do you need to reference the original PR? This sentence seems a little bit odd here. If you need a reference, maybe just a simple link at the end of section.

2017-01-31 20:33 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +Here is Pan Luo's description of that feature, from `the original pull request <https://github.com/edx/edx-platform/pull/9842>`_:
+1, and I think this should be converted to paragraphs, not bullet points.

2017-01-31 20:45 UTC, bradenmacdonald requested changes
@srpearce This looks awesome! I replied to your questions, and had just one change request. Thanks!

2017-01-31 20:45 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +Secondary Providers
"Secondary Providers" and "SAML attribute requirements" have nothing to do with "Third Party Auth ID Mapping API". So those two should be moved to "Advanced Third Party Authentication Features"

2017-01-31 20:45 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_advanced_features.rst
> +Intro text
"The Open edX Third Party Authentication feature offers many advanced configuration options and integration points that can be used to customize the login experience for learners using specific third party providers. None of these are required for a typical installation, but they may be useful. Here is an overview of some of those advanced features."

2017-01-31 20:45 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +****************************
That makes total sense. Thanks.

2017-01-31 20:45 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/index.rst
> +between the two?*
The differences are explained in "tpa_providers.rst" so you could just reference that. Basically, SAML is usually used by institutions (Universities and Corporations), whereas OAuth2 is generally used by websites like Google, Facebook, LinkedIn, etc. that allow anyone to register. Which one you use depends on what third party you want to integrate with.

2017-01-31 20:45 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/index.rst
> +.. _Integrate TPA in Open edX:
Seems good to me.

2017-02-08 23:37 UTC, bradenmacdonald commented
@srpearce Please let me know if/when this is ready for another review.

2017-02-09 18:53 UTC, srpearce reviewed
@mattdrayer and @bradenmacdonald, I've finished a copy editing pass. I have a couple of questions inline.

If you want to see a draft HTML version of this section, go to http://draft-enterprise-sso.readthedocs.io/en/latest/configuration/tpa/index.html.

2017-02-09 18:53 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +      `AWS template file`_ file in GitHub.
This confuses me—we've just told the user to add the appropriate setting to the list, but now we're telling them not to?

2017-02-09 18:53 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +   will have to be hosted elsewhere.)
I'm not sure what to do about this.

2017-02-10 18:19 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
>  After you have configured third-party authentication at an edX site, the edX
"After you have configured a third-party authentication profile for an Open edX site, the site's Sign In screen will display a button for users to access your identity provider (IdP) service.  Learners will access your IdP service and authenticate using their institution credentials.  Your IdP service will direct learners back to the Open edX site's Sign-In screen with an authentication token..."

2017-02-10 18:19 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +When a learner uses third-party authentication to sign into an edX site for the
"sign into" -> "sign-in to"  (sign-in is the action, not sign)

2017-02-10 18:20 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +When a learner uses third-party authentication to sign into an edX site for the
Could say "sign-in at"

2017-02-10 18:21 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
>  Universities and businesses that use SAML to integrate their identity providers
identity provider services  (or identity provisioning services)

2017-02-10 18:22 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +When a user uses SAML or Shibboleth to sign in to edX, the provider (the
Shibboleth is an implementation of SAML, so I think we can just say SAML

2017-02-10 18:23 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +When a user uses SAML or Shibboleth to sign in to edX, the provider (the
"the identity provider (IdP)"

2017-02-10 18:24 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +When a user uses SAML or Shibboleth to sign in to edX, the provider (the
Also, where we say "edX" we should always say "Open edX".  edX is our organization, Open edX is the software.

2017-02-10 18:26 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +university's system, called the "Identity Provider" or IdP) authoritatively
It's not always a university that we are dealing with -- enterprise customers are also utilizing this documentation both for integration with our Open edX installation (edx.org) as well as their own Open edX installations.

2017-02-10 18:28 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +   * - Name
I wish I knew how to do a table like this back when I formatted the individual table -- much nicer!

2017-02-10 18:28 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +When a new user uses SAML to sign in to edX, the identity provider sends
edX -> Open edX

2017-02-10 18:28 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +When a new user uses SAML to sign in to edX, the identity provider sends
Identity Provider (IdP)

2017-02-10 18:29 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +attributes are used to pre-fill the registration form, but Open edX usually
are -> can be

2017-02-10 18:30 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +does not record attributes other than the user ID.
@bradenmacdonald what do we mean when we say "Open edX usually does not record attributes other than the user ID"?  If the attributes are used to populate the form, they will be recorded?

2017-02-10 18:31 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +edits those, Open edX saves only the new changed version. (For example, if the
AH, @bradenmacdonald I see what you meant above -- I think for the earlier statement we should just state that the values are used to populate the form fields and stop there.

2017-02-10 19:09 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +Open edX can accept any set of attributes sent by a SAML identity provider, as
This doesn't seem right to me?  Open edX only recognizes a specific set of SAML attributes -- User ID, Full Name, First Name, Last Name, Username, and Email.

2017-02-10 19:10 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +long as the attributes contain some sort of unique, permanent identifier for
I think we are trying to say here "As long as one of the attributes sent is a unique, permanent identifier for the user being authenticated"

2017-02-10 19:12 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +each user. The URN or OID of this identifier must be specified in the SAML
must be specified in the Open edX "Provider Configuration (SAML IdPs)" profile for the institution

2017-02-10 19:13 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +provider settings (part of the Open edX Django administration console) in the
I think we can just say "administration console" and not "Django administration console" -- I'd bet that no one cares that it's Django other than the people writing the software.

2017-02-10 19:13 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +**User ID Attribute** field. By default, Open edX will expect the standard User
I'd move his "by default" statement further up -- ahead of the "if you need to send a custom version" statement.

2017-02-10 19:14 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +This setting causes all the attributes to be saved in the
TIL!!!  😄

2017-02-10 19:15 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +For universities that want to avoid sending any personally identifiable
universities -> institutions

2017-02-10 19:16 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +recommend that the university configure their SAML identity provider to only
university -> institution

2017-02-10 19:16 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +This should be a number that uniquely identifies any student or staff, but is
the User ID value does not have to be a number

2017-02-10 19:17 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +This should be a number that uniquely identifies any student or staff, but is
any learner or staff member

2017-02-10 19:17 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +different from their student ID or any other identifier they may have.
student ID -> institution ID

2017-02-10 19:17 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +university can use the :ref:`Third Party Auth ID Mapping API` to convert Open
university -> institution

2017-02-10 19:18 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +edX user IDs found in reports or analytics back to these opaque university user
university -> institution

2017-02-10 19:18 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +identifiers.  University partners can then convert each opaque user identifier
University -> institution

2017-02-10 19:18 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +back to the official student ID.
learner ID

2017-02-10 19:19 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
> +types of identity providers. The Open edX platform provides full support for
let's just say "support" instead of "full support" -- I'm not sure what "full" entails.

2017-02-10 19:20 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
> +types of identity providers. The Open edX platform provides full support for
I also might say "currently provides"

2017-02-10 19:20 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
> +three types of identity providers, and provisional support for several other
again, not sure what is meant by "provisional" here -- are we saying it sort-of works?

2017-02-10 19:21 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
> +Fully Supported Identity Providers
Is there a definition for "Fully Supported" somewhere?

2017-02-10 19:22 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
>  providers are included in the source code but are not officially supported.
what does it mean to be "officially supported"?

2017-02-10 19:23 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
> +Regardless of the standard that the identity provider you want to integrate
Here we can say "For all identity provider types, begin by..."

2017-02-10 19:23 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
> +feature<Enable the Third Party Authentication Feature>` for your site.
"Open edX site" --> @bradenmacdonald is this an installation-wide feature flag or is it site-specific?

2017-02-10 19:24 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
> +At an institution that has a partner membership with edX, you can :ref:`enable
This seems like an odd thing to include in the Open edX documentation

2017-02-10 19:27 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +   will have to be hosted elsewhere.)
It's going to be up to each Open edX operator to decide which images to include for these buttons.  If we want to provide a standard image reference that's fine, but we should point to a publicly-available version of it, such as https://upload.wikimedia.org/wikipedia/commons/2/24/%22Microsoft%22_written_in_Segoe_UI_font_(not_a_Microsoft_logo).svg  

^^ not the best example...

2017-02-10 19:29 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +.. _Integrating with an OAuth2 Identity Provider:
I think the overall structure of this file makes sense -- I've left individual comments throughout

2017-02-10 19:32 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +:ref:`Other Providers`.
Open edX supports OAuth2 integrations with Google, Facebook, LinkedIn, and Azure Active Directory providers.  For more information on how to set up one or more of these integrations, see [link]

Integrations with alternative OAuth2 providers are also supported by the system.  Please refer to [link] for more information.

2017-02-10 19:45 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +EdX Supported Providers
How about "Available OAuth2 Providers"?  As with my other comments, I'm a little leery of saying that things are "supported", which insinuates some level of responsibility that has not yet been defined or agreed-upon.

2017-02-10 19:46 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +Integrating with an edX supported OAuth2 IdP has three steps.
"consists of the following steps"

2017-02-10 19:47 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +EdX supported OAuth based providers include Google, Facebook, LinkedIn, and
Available OAuth2 providers include

2017-02-10 19:47 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +Configure the LMS
"Configuring Open edX"?

2017-02-10 19:48 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +#. In the ``lms.env.json`` file, make the following changes.
Make the following changes to the `lms.env.json` file:

2017-02-10 19:49 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +   #. Ensure that ``FEATURES`` > ``ENABLE_THIRD_PARTY_AUTH`` is ``true`` (it is
Change the value of FEATURES to true (it is false by default)

2017-02-10 19:50 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +   #. If you have customized the ``THIRD_PARTY_AUTH_BACKENDS`` list, add the
Add the pertinent OAuth2 providers to the THIRD_PARTY_BACKENDS list:

2017-02-10 19:50 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +      `AWS template file`_ file in GitHub.
Sorry this isn't clear.

If `THIRD_PARTY_AUTH_BACKENDS` appears in `lms.env.json`, then users must make changes to it as described here.

If `THIRD_PARTY_AUTH_BACKENDS` does not appear in `lms.env.json`, then no changes are necessary. I believe this would be the more common case.

2017-02-10 19:53 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +      `AWS template file`_ file in GitHub.
We should note prior to L206 that Google, Facebook, and LinkedIn backends are available by default (@bradenmacdonald, what about AD?)  So it is not necessary to specify THIRD_PARTY_BACKENDS in order to support these.  If a custom backend needs to be configured then this parameter would need to be specified, and I'm assuming that G/F/LI/AD would need to be included along with the custom backend if that is the case.

2017-02-10 19:54 UTC, mattdrayer commented
@srpearce I have taken a run through the latest changes and left some more suggestions -- I think we are almost there!

2017-02-13 21:48 UTC, srpearce reviewed
@mattdrayer and @bradenmacdonald, I've completed another pass. Let me know what you think.

2017-02-13 21:48 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +When a learner uses third-party authentication to sign into an edX site for the
"Sign-in" is the adjective and noun form (they prepared the forms for resident sign-in; the sign-in sheet was empty), and "sign in" is the verb. Also, we made a style decision to leave hyphens out wherever possible, as long as the meaning is clear. :-) But yeah, it should be "sign in to" instead of "sign into".

2017-02-13 21:48 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +   * - Name
And way easier, too. I didn't think to tell you about our [style guide](http://draft-edx-style-guide.readthedocs.io/en/latest/index.html), but it has an example .rst file with [instructions for tables](http://draft-edx-style-guide.readthedocs.io/en/latest/ExampleRSTFile.html#tables).

2017-02-13 21:48 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +**User ID Attribute** field. By default, Open edX will expect the standard User
I'm not sure exactly where this is, but I moved the sentence so that it's now the second one in the paragraph. LMK if that's what you had in mind.

2017-02-14 01:25 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/index.rst
> +Edge` topic describes procedures for members of the DevOps and IT teams at an
All of the "Edge" information really does not belong in the Open edX docs -- not that I can think of a better place for it right now -- unless @grantgoodmanedX has an idea.

2017-02-14 01:26 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +UBC contributed an API to Open edX that can be used to retrieve the association
UBC -> The University of British Columbia?

2017-02-14 02:01 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +When an edX course is used in an on-campus environment, and SAML, LTI, or other
edX -> Open edX

2017-02-14 02:04 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +When an edX course is used in an on-campus environment, and SAML, LTI, or other
I think the wording here needs to be less academic-sounding -- it should read more like a third-party integration guide

2017-02-14 02:05 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +When an edX course is used in an on-campus environment, and SAML, LTI, or other
"universities" -> "institution" or "organization"
"students" -> "learners"

2017-02-14 02:05 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +This new API can be used for mapping between the edX user ID and the ID
The API isn't really "new" anymore -- we can probably stop referring to it this way.

2017-02-14 02:06 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +are using the edX course. It also allows grade information coming from edX to
edX -> Open edX

2017-02-14 02:06 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +This API is supposed to be consumed by on-campus middleware, which combines the
supposed -> intended

2017-02-14 02:07 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +information from an on-campus system. The middleware communicates with the
wherever we say "on-campus" we could instead say "on-premise"

2017-02-14 02:08 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +addresses and cannot activate their accounts, and then cannot sign in to edX
edX -> Open edX

2017-02-14 02:08 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +through Shibboleth because of the inactive accounts. With this API, on-campus
through Shibboleth -> via SSO

2017-02-14 02:08 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +addresses and cannot activate their accounts, and then cannot sign in to edX
sign in to -> authenticate with

2017-02-14 02:09 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +course support staff or instructors can provide edX support the student's real
is "edX" here actually edX, Inc.?  If so it should be removed -- we could refer to this entity as the "Open edX operator"

2017-02-14 02:09 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +edX username instead of the ID that Shibboleth passed over to edX, so that edX
Shibboleth -> the identity provider

2017-02-14 02:10 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +between the Shibboleth ID and the edX username.
Shibboleth --> source system

2017-02-14 02:10 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +between the Shibboleth ID and the edX username.
edX -> Open edX

2017-02-14 02:13 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +Using the API
Using the Third Party Auth ID Mapping API

2017-02-14 02:13 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +To use the API, follow these steps.
API -> Third Party Auth ID Mapping API

2017-02-14 02:19 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_advanced_features.rst
> +Make sure you are signed out of edX (or use an incognito window), then click on
edX -> Open edX

2017-02-14 02:19 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_advanced_features.rst
> +The intended use case of this feature is for universities that wish to provide
universities -> institutions or organizations

2017-02-14 02:19 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_advanced_features.rst
> +a link from some on-campus system (or a course in another LMS like Canvas) to a
some on-campus -> an on-premise

2017-02-14 02:20 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_advanced_features.rst
> +course in Open edX. In that case, they will want students to sign in using
who is 'they' here?

2017-02-14 02:20 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_advanced_features.rst
> +their universities' SAML provider. By using hinted links, the sign in and/or
universities' -> organization's

2017-02-14 02:21 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_behavior.rst
> +* When a user logs in with SSO for the first time, their account is not
with SSO -> via SSO

2017-02-14 02:22 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_behavior.rst
> +  user could also cancel the registration process at this point, and no account
user -> learner?

2017-02-14 02:22 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_behavior.rst
> +  (for example, Google) to Open edX varies depending on the provider. For
I think you can drop (for example, Google) here

2017-02-14 02:24 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +When a learner uses third-party authentication to sign into an edX site for the
TIL!

2017-02-14 02:25 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/index.rst
> +By default, third party authentication is not enabled on edX installations. To
edX -> Open edX

2017-02-14 02:26 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/index.rst
> +For information about enabling third party auth on Edge, see :ref:`Enabling
Stated earlier, but I think the "Edge" information does not belong in the Open edX documentation

2017-02-14 02:27 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_behavior.rst
> +* After a user submits the registration form, their user account is created and
user -> learner

2017-02-14 02:27 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_behavior.rst
> +* When a user creates an account with SSO, the password field on the
with SSO -> using SSO, via SSO, etc.

2017-02-14 02:27 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_behavior.rst
> +  account is always created for the new user, with a copy of the user's
account -> learner account

2017-02-14 02:38 UTC, mattdrayer commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +**User ID Attribute** field. By default, Open edX will expect the standard User
I'd make it the first sentence in the paragraph.

2017-02-15 03:00 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +      `AWS template file`_ file in GitHub.
> We should note prior to L206 that Google, Facebook, and LinkedIn backends are available by default (@bradenmacdonald, what about AD?) So it is not necessary to specify THIRD_PARTY_BACKENDS in order to support these.

Azure AD is enabled by default too: https://github.com/edx/edx-platform/blob/31f178ea59b02930d2b6c3230ce2cf33088128b4/lms/envs/aws.py#L657-L667

> f a custom backend needs to be configured then this parameter would need to be specified, and I'm assuming that G/F/LI/AD would need to be included along with the custom backend if that is the case.

@mattdrayer  Yes that is the case.

2017-02-15 03:04 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +   will have to be hosted elsewhere.)
Maybe we should just leave out any instructions about a microsoft logo. I cannot find any official / legal / public version of the logo we could point to that looks OK on this page (i.e. is white and one color), and we should not be re-distributing the image we are using.

2017-02-15 03:05 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +university's system, called the "Identity Provider" or IdP) authoritatively
How about "the external organization's system" then?

2017-02-15 03:08 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +Open edX can accept any set of attributes sent by a SAML identity provider, as
Well, by default it only uses those six attributes, true. However, additional attributes can be sent by the IdP and won't cause any problems. In addition, the `"EXTRA_DATA": [ "attributes" ]` setting will save into the database *all* the attributes that get sent, even if they don't get used.

The main point of this sentence though was to communicate that the only required attribute is a unique user identifier - some other attributes are useful, but none of the others are required.

2017-02-15 03:08 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +long as the attributes contain some sort of unique, permanent identifier for
Yes.

2017-02-15 03:09 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +provider settings (part of the Open edX Django administration console) in the
Sure. Django themselves refer to it as the "admin site", which may be a better term than "admin console"?

2017-02-15 03:10 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +For universities that want to avoid sending any personally identifiable
Or "organization" instead of institution? To me "institution" still sounds academic. I don't think your typical silicon valley startup would refer to themselves as an "institution" for example.

2017-02-15 03:11 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
> +three types of identity providers, and provisional support for several other
We could just remove them from the document. Short answer is I do not know to what extent those other systems work.

2017-02-15 03:11 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
> +Fully Supported Identity Providers
Let's remove the word "Fully"

2017-02-15 03:11 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
>  providers are included in the source code but are not officially supported.
If you ask on the ML, people will try to answer your question rather than telling you not to use that feature :-p

2017-02-15 03:15 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
> +feature<Enable the Third Party Authentication Feature>` for your site.
I think the overall flag to enable third party auth or not is installation-wide. If White Label sites are set up, then individual providers (e.g. Google) get enabled on a per-site basis.

2017-02-15 03:15 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_providers.rst
> +At an institution that has a partner membership with edX, you can :ref:`enable
I think there is a way to annotate sections of the doc so that they show up in the edx partner documentation and not the open edx documentation, right?

2017-02-15 03:16 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +UBC contributed an API to Open edX that can be used to retrieve the association
Yes

2017-02-15 03:16 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +UBC contributed an API to Open edX that can be used to retrieve the association
Though we don't necessarily need to mention its provenance within the docs, if that's something we're not doing in other places.

2017-02-15 03:20 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_behavior.rst
> +  example, Google, Facebook, MIT SAML, and UBC SAML may all provide different
We may want to change the "MIT SAML" and "UBC SAML" examples here to "a university's SAML provider, and a corporate SAML provider"

2017-02-15 03:20 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_behavior.rst
> +  providers, such as UBC, may pass only an opaque "user token" that can be used
Remove "such as UBC" here.

2017-02-15 03:25 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +Create a Google App
This phrasing of "Create a Google App" and other "Create...App" mentions in this file is not really accurate - a better way to describe it would be "Register the Open edX Instance with Google".

In other words, from the perspective of Google, Facebook, etc., the Open edX site is the App (web application), and we are not creating it in this step (it already exists) - we are simply letting Google know about it.

2017-02-15 03:28 UTC, bradenmacdonald commented on en_us/install_operations/source/configuration/tpa/tpa_advanced_features.rst
> +``https://courses.edx.org/courses/course-v1:McGillX+Body101x+1T2016/courseware/3eddbb5919544c229d34b3175debc6d6/f9900289d2d0474096d20d23a1eeed81/?tpa_hint=oa2-google-oauth2 <https://courses.edx.org/c
This is not appearing correctly on Read the Docs and is not line wrapping.

2017-02-15 23:40 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/index.rst
> +Edge` topic describes procedures for members of the DevOps and IT teams at an
Yeah, we don't really have a place for this. I don't know how many partner institutions use/have used it or even know about it, either. But is it OK to leave it here for now, until we figure out something else? I don't know how else partner institutions would find this information.

2017-02-15 23:40 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_IDmap_api.rst
> +UBC contributed an API to Open edX that can be used to retrieve the association
We haven't done this elsewhere, so I'll take it out here.

2017-02-15 23:40 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_behavior.rst
> +  user could also cancel the registration process at this point, and no account
I'd prefer to keep this and other instances as "user", since "learner" isn't always an accurate substitute and I'm not familiar enough with this to navigate the gray areas. (E.g., "When a learner signs in by using SSO for the first time, their account is not normally created automatically. Instead, the user (learner?) information sent by the provider is used"...)

2017-02-15 23:40 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_eliminating_pii.rst
> +provider settings (part of the Open edX Django administration console) in the
We call this the "Django administration console" most of the time in the ICR guide, though we're not completely consistent, unfortunately (mutter mutter _resources_ grumble _time_ mutter)...

2017-02-15 23:40 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +   will have to be hosted elsewhere.)
OK, I removed this step.

2017-02-15 23:40 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +      `AWS template file`_ file in GitHub.
I rewrote this step based on these comments; let me know what you think.

2017-02-15 23:40 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_advanced_features.rst
> +
In this section, I changed the live URLs (which didn't work for me) to example URLs and rewrote the text accordingly.

2017-02-15 23:40 UTC, srpearce commented on en_us/install_operations/source/configuration/tpa/tpa_integrate_open/tpa_oauth.rst
> +#. If necessary, make sure that the correct backend is specified.
I rewrote this step based on the comments from @mattdrayer and @bradenmacdonald - let me know what you think.

2017-02-15 23:43 UTC, srpearce commented
@mattdrayer and @bradenmacdonald , here's another draft. I'm willing to let some copy editing stuff slide in the interest of getting this out (e.g., "organization" vs. "institution", since "institution" appears on a UI button that's mentioned in a couple of files). Let me know what you think.

2017-02-17 21:55 UTC, bradenmacdonald approved these changes

2017-02-17 21:56 UTC, bradenmacdonald commented
@srpearce Great work, thanks for slogging through this! Let's 🚢  it.

2017-02-17 22:46 UTC, mattdrayer commented
Oh wow this is looking great now -- thank you so much @srpearce!!!  Time to 🚀

2017-02-18 01:59 UTC, merged

2017-02-18 03:01 UTC, srpearce commented
@mattdrayer @bradenmacdonald This is now live! 

http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/tpa/index.html

If it needs any updates, well—I'll just need a drink or two before I dive in again.

2017-02-18 03:10 UTC, mattdrayer commented
:1st_place_medal:

2017-02-19 01:13 UTC, bradenmacdonald commented
🎉