Updated documentation for email opt-in file.
openedx-unsupported/edx-documentation pull request #1394
Opened 2017-01-16 11:42 UTC by jareerahsan

ECOM-2963

## [DOC-XXXX](https://openedx.atlassian.net/browse/DOC-XXXX)

Add a description of your changes with links to any relevant material.

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2017-01-16 19:22 UTC, jareerahsan commented
@stroilova @schenedx Kindly tag people to review this change. Particularly someone to review the doc language itself.

2017-01-17 15:00 UTC, stroilova commented on en_us/data/source/internal_data_formats/institution_data.rst
> +the ``auth_user.id`` :ref:`column<auth_user>`.
Should we use the same language as in other parts of the research guide? E.g.:
http://edx.readthedocs.io/projects/devdata/en/latest/internal_data_formats/sql_schema.html#id6
The learner’s ID in auth_user.id.

2017-01-17 15:10 UTC, stroilova commented on en_us/data/source/internal_data_formats/institution_data.rst
> +The unique username supplied by the student while registering. For more
Again, for documenting "username" should we use the same language as in other parts of the edX research guide, if available?

See comment for user_id above.

2017-01-17 15:12 UTC, stroilova commented
@jareerahsan Thanks for starting this PR. I've tagged @catong  as well.

Couple of notes:
- Perhaps use consistent language with how user_id and username are referenced elsewhere in the documentation (see inline comments for more details)
- Perhaps add some "History" notes about when these two columns were added? This helps data czars know when exactly the format changed, as they work with older data deliveries.

Thanks.

2017-01-17 16:29 UTC, schenedx commented
@stroilova When you say add some "History" notes, can you provide some example? Or reference us to the line where you think we should make the change on?

2017-01-17 16:30 UTC, stroilova commented
@schenedx Some examples are throughout the research guide, including the User Info page. E.g.:
http://edx.readthedocs.io/projects/devdata/en/latest/internal_data_formats/sql_schema.html#is-superuser

2017-01-17 18:29 UTC, catong reviewed
Agree with @stroilova to keep wording consistent with other instances where the same fields are doc'd.

History could be as simple as "This column was added on (date)". (@stroilova do you agree?)

2017-01-17 18:29 UTC, catong commented on en_us/data/source/internal_data_formats/institution_data.rst
> +the ``auth_user.id`` :ref:`column<auth_user>`.
Agree with @stroilova that wherever possible, let's use existing language. 
If you want to add the cross-reference link, add an extra sentence: "For more information, see ```:ref:`auth_user` ```.

2017-01-17 19:54 UTC, stroilova commented
@catong Yes, I agree! Both of those make sense - perfect.

2017-01-18 12:29 UTC, jareerahsan commented
@stroilova @catong Please review the update!

2017-01-18 13:36 UTC, stroilova commented
This looks great, thank you @jareerahsan !
👍

2017-01-18 15:44 UTC, catong requested changes
Minor comment and requested fixes to the cross-reference link text, then 👍 . Thank you!

2017-01-18 15:44 UTC, catong commented on en_us/data/source/internal_data_formats/institution_data.rst
> +The learner's id in ``auth_user.id``. For more information, see
Nit: "learner's id" -> "learner's ID"
Remove "column" from the ref so that the link text is the actual title of that section: 
```:ref:`auth_user`.```

2017-01-18 15:44 UTC, catong commented on en_us/data/source/internal_data_formats/institution_data.rst
> +:ref:`column<auth_user>`.
Same comment as above for the link syntax: remove "column".

2017-01-18 15:47 UTC, jareerahsan commented on en_us/data/source/internal_data_formats/institution_data.rst
> +:ref:`column<auth_user>`.
@catong I can remove the `column` but if you see the whole file, it is being referenced with every other field previously mentioned on this page. Should I go ahead and remove just these two?

2017-01-18 17:07 UTC, catong commented on en_us/data/source/internal_data_formats/institution_data.rst
> +:ref:`column<auth_user>`.
@jareerahsan The link goes to the same place as it would without the word "column" - all that it is doing is overriding the link text. Yes, please use the syntax I provided in the comment. In your branch, you can run "make html" in the "data" directory to see the output.

2017-01-18 17:15 UTC, catong commented on en_us/data/source/internal_data_formats/institution_data.rst
> +:ref:`column<auth_user>`.
To clarify, if you remove ```column``` from the cross-reference, the link text that is used is "Columns in the ``auth_user`` table". So the sentence will read, "For more information, see "Columns in the auth_user table." which I think works well.

2017-01-18 17:22 UTC, jareerahsan commented
@catong Updated!

2017-01-18 17:24 UTC, catong approved these changes

2017-01-18 17:24 UTC, catong commented
Looks great! 👍

2017-01-18 17:41 UTC, merged