Nedbat/ficus updates
openedx-unsupported/edx-documentation pull request #1428
Opened 2017-02-28 21:42 UTC by nedbat

## [OPEN_1867](https://openedx.atlassian.net/browse/OPEN-1867)

Changes to installation and release notes for Ficus.  Much of this will be cherry-picked onto master once everything has merged.

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @gsong 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2017-03-01 14:27 UTC, nedbat commented
@jbarciauskas you might have opinions also.

2017-03-01 14:27 UTC, jbarciauskas commented
Not me!

2017-03-01 14:39 UTC, jbarciauskas requested changes

2017-03-01 14:39 UTC, jbarciauskas commented on en_us/install_operations/source/installation/installation_options.rst
> +There are a number of Virtual Machine options, which install the Open edX
A number?

2017-03-01 14:39 UTC, jbarciauskas commented on en_us/install_operations/source/installation/installation_options.rst
>  * Fullstack is a Vagrant virtual machine instance designed for deploying all
Are we replacing all instances of Fullstack with "fullstack/native"?

2017-03-01 14:39 UTC, jbarciauskas commented on en_us/install_operations/source/installation/installation_options.rst
>    Fullstack`.
fullstack

2017-03-01 14:39 UTC, jbarciauskas commented on en_us/install_operations/source/installation/installation_options.rst
>  Open edX Fullstack
Fullstack

2017-03-01 14:39 UTC, jbarciauskas commented on en_us/install_operations/source/installation/installation_options.rst
> +from edX and the Open edX community, see the `Open edX Installation Options`_
Do we still need this link out?

2017-03-01 14:39 UTC, jbarciauskas commented on en_us/install_operations/source/installation/installation_options.rst
> +* Open EdX Search.
Open edX

2017-03-01 14:39 UTC, jbarciauskas commented on en_us/install_operations/source/installation/installation_options.rst
> +If you are installing an Open edX virtual machine on a Linux or Mac computer, you
Can you install an Open edX virtual machine on another OS?

2017-03-01 14:39 UTC, jbarciauskas commented on en_us/install_operations/source/platform_releases/ficus.rst
> +Upgrading a Vagrant Installation
I'm guessing from the formatting that it's clear that this is upgrading from ficus to ficus, but maybe worth clarifying?

2017-03-01 14:39 UTC, jbarciauskas commented on en_us/open_edx_release_notes/source/ficus.rst
> +You can also find `release announcements`_ on the open.edx.org website. You can
Should we encourage subscribing to this?

2017-03-01 14:39 UTC, jbarciauskas commented on en_us/open_edx_release_notes/source/ficus.rst
> +edx.org. Those changes are part of the master branch of the edX Platform in
Add a note that these will eventually make it into a future Open edX release, though they will not be available before then unless you want to figure out how to upgrade your installation to the master branch (which is unsupported)?

2017-03-01 15:20 UTC, catong commented on en_us/course_authors/source/conf.py
> +project = u'Building and Running an edX Course: Ficus Release'
@nedbat I think these Open edX project settings should be made to the Open edX version of the course authors conf.py instead?
en_us/open_edx_course_authors/source/conf.py

2017-03-01 15:21 UTC, catong commented on en_us/course_authors/source/index.rst
> +Building and Running an edX Course: Ficus Release
Same comment as above - the Open edX named release changes should be made in the open_edx_course_authors source directory.

2017-03-01 21:05 UTC, nedbat commented on en_us/install_operations/source/installation/installation_options.rst
> +There are a number of Virtual Machine options, which install the Open edX
three :)  fixed.

2017-03-01 21:08 UTC, nedbat commented on en_us/install_operations/source/installation/installation_options.rst
>  * Fullstack is a Vagrant virtual machine instance designed for deploying all
I'm looking for the best wording for this.  The instructions and wiki pages still talk about fullstack.  I wanted these changes to amount to, "fullstack is a native install in a vagrant box." I guess that is confusing. I don't want to have to say "fullstack/native" everywhere.

2017-03-01 21:12 UTC, nedbat commented on en_us/install_operations/source/installation/installation_options.rst
> +from edX and the Open edX community, see the `Open edX Installation Options`_
I just added this link, because the old links were to outdated information.  The Installation Options wiki page explains how to choose among the options.  I suppose that should move into the rst docs, but I was trying to limit this pass to, "fix things that are wrong."

2017-03-01 21:12 UTC, nedbat commented on en_us/install_operations/source/installation/installation_options.rst
> +* Open EdX Search.
fixed.

2017-03-01 21:16 UTC, nedbat commented on en_us/install_operations/source/installation/installation_options.rst
> +If you are installing an Open edX virtual machine on a Linux or Mac computer, you
Fullstack works fine on windows (I think).

2017-03-01 21:20 UTC, nedbat commented on en_us/install_operations/source/platform_releases/ficus.rst
> +Upgrading a Vagrant Installation
Clarified

2017-03-01 21:24 UTC, nedbat commented on en_us/open_edx_release_notes/source/ficus.rst
> +edx.org. Those changes are part of the master branch of the edX Platform in
I added the second sentence here:
```
Changes listed for 11 January 2017 and before are included in the Ficus release
of Open edX.  Changes after that point will be in future Open edX releases.
```
I'd rather not give people encouragement to try to follow master.

2017-03-01 21:24 UTC, nedbat commented on en_us/open_edx_release_notes/source/ficus.rst
> +You can also find `release announcements`_ on the open.edx.org website. You can
It sounds like you mean, "maybe we should stop encouraging," since the words are already there.

2017-03-01 21:27 UTC, jbarciauskas commented on en_us/open_edx_release_notes/source/ficus.rst
> +edx.org. Those changes are part of the master branch of the edX Platform in
sgtm

2017-03-01 21:27 UTC, jbarciauskas commented on en_us/open_edx_release_notes/source/ficus.rst
> +You can also find `release announcements`_ on the open.edx.org website. You can
yes, sorry, didn't mean to be obtuse

2017-03-01 21:31 UTC, nedbat commented on en_us/course_authors/source/conf.py
> +project = u'Building and Running an edX Course: Ficus Release'
oops! Fixed.

2017-03-01 21:31 UTC, nedbat commented on en_us/course_authors/source/index.rst
> +Building and Running an edX Course: Ficus Release
Fixed.

2017-03-01 21:37 UTC, jbarciauskas commented on en_us/install_operations/source/installation/installation_options.rst
> +from edX and the Open edX community, see the `Open edX Installation Options`_
That's fine, just checking

2017-03-01 21:38 UTC, jbarciauskas commented on en_us/install_operations/source/installation/installation_options.rst
>  * Fullstack is a Vagrant virtual machine instance designed for deploying all
I would just pick one (probably native) and treat fullstack as a special case of native.

2017-03-01 22:08 UTC, catong commented on en_us/open_edx_release_notes/source/ficus.rst
> +Added "View this course as" capability.
I believe this description isn't complete - "View this course as" feature has existed for a while. If this item refers to TNL-6050, what got added in Ficus was the ability to view as a member of a content group (if cohorts and content groups exist in the course).

2017-03-01 22:08 UTC, catong commented on en_us/open_edx_release_notes/source/ficus.rst
> +A post listing view that shows not only post titles, but also the first line of
Might want to move this below or group with "Improvements to the discussions UI" (line 41)

2017-03-01 22:08 UTC, catong commented on en_us/open_edx_release_notes/source/ficus.rst
> +
Not sure about the intent for the links in these 2 bullet items? They don't seem to make sense as part of the list about CAPA problems.

2017-03-01 22:08 UTC, catong commented on en_us/open_edx_release_notes/source/ficus.rst
> +The ability to prevent learners from receiving feedback until they've dropped
Suggest rewording to refer to the problem type up front; also make active voice: "In drag and drop problems, learners no longer receive feedback until..."

2017-03-02 16:48 UTC, nedbat commented on en_us/open_edx_release_notes/source/ficus.rst
> +You can also find `release announcements`_ on the open.edx.org website. You can
Removed the mention of subscribing to release announcements.

2017-03-02 19:23 UTC, nedbat commented on en_us/open_edx_release_notes/source/ficus.rst
> +A post listing view that shows not only post titles, but also the first line of
Good idea, grouped.

2017-03-02 19:31 UTC, gsong commented on en_us/install_operations/source/installation/installation_options.rst
> +machine.  Details are at the `Open edX Native Installation`_ page on the edX
Currently the link goes to 12.04 instructions. Will that be updated via the Confluence or do we need to change it here?

2017-03-02 19:31 UTC, gsong commented on en_us/install_operations/source/platform_releases/ficus.rst
> +If you installed Open edX using the `Open edX Native Installation`_, you can
Same thing here, currently link goes to 12.04 instructions.

2017-03-02 20:22 UTC, nedbat commented on en_us/open_edx_release_notes/source/ficus.rst
> +
I dug out the info, and made paragraphs for those two bullets.

2017-03-02 20:23 UTC, nedbat commented on en_us/open_edx_release_notes/source/ficus.rst
> +The ability to prevent learners from receiving feedback until they've dropped
Done

2017-03-02 20:25 UTC, nedbat commented on en_us/open_edx_release_notes/source/ficus.rst
> +Added "View this course as" capability.
done.

2017-03-02 20:26 UTC, nedbat commented
@catong @jbarciauskas @gsong Any other thoughts?

2017-03-02 20:31 UTC, nedbat commented on en_us/install_operations/source/installation/installation_options.rst
> +machine.  Details are at the `Open edX Native Installation`_ page on the edX
Right, I'll fix it.

2017-03-02 20:34 UTC, catong commented
@nedbat Taking a last look, thanks

2017-03-02 20:35 UTC, nedbat commented on en_us/install_operations/source/platform_releases/ficus.rst
> +If you installed Open edX using the `Open edX Native Installation`_, you can
Done.

2017-03-02 20:37 UTC, catong commented on en_us/open_edx_release_notes/source/ficus.rst
> +New Features
It's a little strange to see "LMS", "Discussions" and "Studio..." listed as "New Features".
Suggestion: Change the "New Features" heading to something else, perhaps "Highlights" to mirror your intro sentence above. Then, also modify the intro on line 17 to something like: "The Open edX Ficus release includes the following updates."

2017-03-02 20:39 UTC, catong commented on en_us/open_edx_release_notes/source/ficus.rst
> +
In these sections, it might make for easier reading if each item were bulleted?

2017-03-02 20:40 UTC, catong commented
@nedbat Made suggestions in comments, otherwise 👍

2017-03-03 18:29 UTC, nedbat commented on en_us/open_edx_release_notes/source/ficus.rst
> +New Features
Hmm, I think I like it better as it is than labelling them "Highlights," but the other points I'll take :)

2017-03-03 18:29 UTC, nedbat commented on en_us/open_edx_release_notes/source/ficus.rst
> +
Done.

2017-03-03 19:22 UTC, nedbat commented
@jbarciauskas I will accept your implicit assent :)

2017-03-03 19:23 UTC, merged

2017-03-03 19:43 UTC, jbarciauskas commented
Yeah lots of others chimed in :)