Update EMR configuration.
openedx-unsupported/edx-documentation pull request #1448
Opened 2017-03-17 23:00 UTC by brianhw

In August, 2016, we upgraded the version of AWS EMR on which we ran, from 2.4.11 to 4.7.2.  We sent out instructions at the time to those users who might want to perform a similar upgrade.  Those instructions can be seen here: 
https://groups.google.com/forum/#!msg/openedx-ops/eCyNwYdhVcU/cOIHPLZiBwAJ.  

However, we did not update our documentation to reflect the updated configuration.  

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @mulby 
- [ ] Subject matter expert: @HassanJaveed84 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: @tobz @azafty468 @iloveagent57 

### Testing

- [x] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2017-03-27 15:20 UTC, brianhw commented
The Travis build failed due to warnings in other doc (course-authoring).  I'm trying to rebase on master, assuming that it would build cleanly now.

2017-03-29 21:23 UTC, mulby approved these changes
LGTM

2017-04-04 20:42 UTC, brianhw commented
@edx/doc Do I need a thumb from you?   It would be great to have a more recent version of this for an openedx user who may be moving to AWS EMR soon.

2017-04-04 20:57 UTC, catong commented
@brianhw I'm going to do quick editing pass and we can get this merged. Thanks!

2017-04-04 20:59 UTC, catong requested changes
A couple of minor edits

2017-04-04 20:59 UTC, catong commented on en_us/install_operations/source/insights/elastic_mapreduce.rst
> +You may find you need to update Hadoop instance types and container
"may" - > "might" throughout when talking about possibility rather than permission.
Missing the word "are" between "that" and "running out of"

2017-04-04 23:49 UTC, brianhw commented
Thanks @catong !  I've made the requested changes.

2017-04-05 13:59 UTC, catong approved these changes

2017-04-05 14:39 UTC, merged