Release Notes for week ending April 14, 2017
openedx-unsupported/edx-documentation pull request #1486
Opened 2017-04-18 13:08 UTC by marcotuts

The following pull request includes the read the docs changes necessary for the week ending April 14, 2017 

### Release Notes Page

The confluence page for this week's release notes can be found here: [Release Notes: Week Ending April 14, 2017](https://openedx.atlassian.net/wiki/pages/viewpage.action?pageId=159168386)

### Date Needed (optional)

EOD Tuesday April 18, 2017

### Reviewers
Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [] Doc team review: @catong

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version 

- [ ] http://draft-release-notes.readthedocs.io/en/latest/2017/2017-04-14.html

### Post-review

- [ ]  Squash commits

2017-04-18 14:39 UTC, catong requested changes
Suggested text

2017-04-18 14:39 UTC, catong commented on en_us/release_notes/source/2017/lms/lms_2017-04-14.rst
> +For newly created courses that enable cohorts, inline discussions components
"For newly created courses that use cohorts, inline discussion components are no longer divided by cohort by default. By default, inline discussion components are unified so that all learners can participate in the discussion. You can still decide which inline discussion components are divided, and specify this on the **Cohorts** tab in the instructor dashboard. "

2017-04-18 14:39 UTC, catong commented on en_us/release_notes/source/2017/lms/lms_2017-04-14.rst
> +On the program progress page in the dashboard, learners can now more clearly differentiate between courses 'in progress' and courses that they have yet to complete. Should a 'in progress' course's up
"On the **Programs** tab of learners' dashboards, learners can now easily track which courses in each program are in progress, completed, or remaining. Courses are moved from "In Progress" to "Remaining" either if the upgrade deadline has passed, or if the course ends before the learner completes the course."

2017-04-18 14:48 UTC, catong commented on en_us/release_notes/source/2017/lms/lms_2017-04-14.rst
> +On the program progress page in the dashboard, learners can now more clearly differentiate between courses 'in progress' and courses that they have yet to complete. Should a 'in progress' course's up
@marcotuts I think the label is actually "Enrolled" instead of "Remaining", so the text should be updated accordingly.

2017-04-18 14:52 UTC, marcotuts commented
Text changes updated, ran tests locally successfully.

2017-04-18 15:10 UTC, catong commented on en_us/release_notes/source/2017/lms/lms_2017-04-14.rst
> +On the program progress page in the dashboard, learners can now more clearly differentiate between courses 'in progress' and courses that they have yet to complete. Should a 'in progress' course's up
D'oh. Completed, Enrolled, Not Enrolled!

2017-04-20 14:09 UTC, catong commented
👍

2017-04-20 14:10 UTC, merged