Sylvia/mit capa hide correct
openedx-unsupported/edx-documentation pull request #1489
Opened 2017-04-18 21:19 UTC by srpearce

## [Supersedes DOC PR 1466](https://github.com/edx/edx-documentation/pull/1466)

Got the following error message when I tried to push to PR 1466:

```
ERROR: Sorry, but @open-craft has blocked access to SSH keys created by some third-party applications. Your key was created before GitHub tracked keys created by applications, so we need your help.

If you personally created this key, you can approve it at:

  https://github.com/settings/ssh/audit/6872700/policy

Otherwise, please upload a new key:

  https://github.com/settings/keys

Fingerprint: 89:e9:08:46:7e:a8:53:bb:20:87:44:4c:ae:2a:07:ba

[EPOLICYKEYAGE]

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### Date Needed (optional)

19 April 2017

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): 
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Sandbox (optional)

- [ ] https://studio-pr14737.sandbox.opencraft.hosting/home/

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2017-04-19 20:25 UTC, grantgoodmanedX commented on en_us/shared/developing_course/course_subsections.rst
> +problem results from learners—for example, if you are administering an exam.
Is this our style for em dashes? The style guide suggests we avoid them, but I kind of like them.

2017-04-19 20:33 UTC, catong commented on en_us/shared/developing_course/course_subsections.rst
> +problem results from learners—for example, if you are administering an exam.
@grantgoodmanedX We don't have a style for em dashes because our style is to avoid them :-D. I'd suggest trying to rework the sentence to avoid the em dash, but if we use the em dash, I prefer a space on either side.

2017-04-19 20:36 UTC, grantgoodmanedX commented on en_us/shared/developing_course/course_subsections.rst
> +problem results from learners—for example, if you are administering an exam.
I agree on the spacing. Otherwise, it looks fine to me 👍

2017-04-19 20:36 UTC, catong commented on en_us/shared/developing_course/course_subsections.rst
> +problem results from learners—for example, if you are administering an exam.
Also, sorry to intrude on your review but now that I'm here: in the previous sentence, I'd suggest that saying "the results of their submissions" might be more clear than "the results of the problem".
And "may want to" -> "you might want to". 
OK, leaving now...

2017-04-20 18:02 UTC, srpearce commented on en_us/shared/developing_course/course_subsections.rst
> +problem results from learners—for example, if you are administering an exam.
Yeah, I know, I know. I thought I'd try to sneak one in, because I'm a dasher myself—but I'll take it out. Le sigh.

2017-04-20 18:06 UTC, srpearce commented
@pomegranited @sstack22 Can you guys review this and make sure it's accurate? Thanks!

2017-04-20 18:48 UTC, srpearce commented
@grantgoodmanedX I just added a couple of notes in the SFD_check_progress.rst file. Can you give those a quick copy edit?

2017-04-21 19:43 UTC, grantgoodmanedX approved these changes
Looks good! 👍

2017-04-23 11:00 UTC, pomegranited requested changes
Hi @srpearce , thank you for finding all the places in the documentation where this new feature should be referenced!  That should make it much easier for people to find and use.

I've left a few comments suggesting that some of the "Notes" be incorporated into the descriptions of the settings themselves?  Since each setting has its own peculiarities, I thought it was worth grouping them there, but am totally option to discussion.

Also note that hidden results are still visible on the Progress page, but will be hidden soon with an upcoming change.

2017-04-23 11:00 UTC, pomegranited commented on en_us/shared/developing_course/course_subsections.rst
> +     immediately when learners submit answers.
I think all the notes are confusing.. can they be integrated into each of these settings instead?  e.g. here, change to "Results are visible immediately when learners and staff submit answers."

2017-04-23 11:00 UTC, pomegranited commented on en_us/shared/developing_course/course_subsections.rst
> +   * **Never show results**: Never show results for answers in this subsection.
and here: "Never show results to learners or staff for answers in this subsection."

2017-04-23 11:00 UTC, pomegranited commented on en_us/shared/developing_course/course_subsections.rst
> +     (for self-paced courses) has passed.
and here: "Hide results from learners until the subsection due date...  Course staff can always see results when this setting is used, but can see the hidden results by :ref:`viewing the course as a student<Roles for Viewing Course Content>` when they preview the course or view the live course."

2017-04-23 11:00 UTC, pomegranited commented on en_us/shared/developing_course/course_subsections.rst
> +  **Never show results** is selected.
If we can incorporate this note above, then this one is not required.

2017-04-23 11:00 UTC, pomegranited commented on en_us/shared/developing_course/course_subsections.rst
> +  view the live course.
Same here: this note is not required if incorporated above.

2017-04-23 11:00 UTC, pomegranited commented on en_us/shared/developing_course/course_subsections.rst
> +  results when they preview the course or view the live course..
Note not required if information is above.

2017-04-23 11:00 UTC, pomegranited commented on en_us/shared/students/SFD_check_progress.rst
> +   in the grading details for the assignment.
This isn't true yet, but we're working on a change that will make problems in subsections with hidden results be not visible on the Progress page.

2017-04-23 11:00 UTC, pomegranited commented on en_us/shared/students/SFD_check_progress.rst
> +   These results are also not visible on your **Progress** page.
This isn't true yet, but we're working on a change that will make problems in subsections with hidden results be not visible on the Progress page.

2017-04-24 14:10 UTC, sstack22 commented on en_us/shared/developing_course/course_subsections.rst
> +well as their scores. However, you might want to temporarily or permanently
@srpearce  - I hope people only use the 'never' option for when they are using CAPA for surveys. Perhaps we can include that use case?

2017-04-24 14:13 UTC, sstack22 commented
Made one small comment, otherwise 👍  from me.

2017-04-24 15:25 UTC, srpearce commented
@pomegranited Great suggestions. I've incorporated your feedback—let me know what you think.

2017-04-25 03:45 UTC, pomegranited approved these changes
@srpearce Awesome, your changes look great!

:+1:

- [x] I tested this by generating the documentation on my local machine, and reading through the changed pages.
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> Doc changes only
- [x] Includes documentation.  It's all docs 😄

2017-04-25 15:50 UTC, merged