Add description about the user `emr` needed for the ec2 instance prof…
openedx-unsupported/edx-documentation pull request #1496
Opened 2017-05-03 18:21 UTC by aqt01

…ile and more detail about the Amazon EMR default roles

This detail is important because the command `aws emr create-default-roles ` just creates the default roles for the EMR cluster but also the ec2 profile instance is needed to manage privileges like s3 on the instances
More info -> https://goo.gl/OW8f6I

## [DOC-XXXX](https://openedx.atlassian.net/browse/DOC-XXXX)

Add a description of your changes with links to any relevant material.

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2017-05-03 18:21 UTC, edx-webhook commented
Thanks for the pull request, @aqt01! I've created [OSPR-1760](https://openedx.atlassian.net/browse/OSPR-1760) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-documentation/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2017-05-09 15:06 UTC, tobz requested changes

2017-05-09 15:06 UTC, tobz commented on en_us/install_operations/source/insights/elastic_mapreduce.rst
> +`default EC2 role for Amazon EMR`_ used by AWS. The command `aws emr create-default-roles` facilitates this task. For more info see [this](https://goo.gl/OW8f6I) link
Can you change the shortened link to be the full link? (**http://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-iam-roles-defaultroles.html**)

We'd like to have the authoritative link in the documentation rather than have to pass through shorteners, so that people know what they're clicking on.

2017-05-09 15:13 UTC, tobz commented
Overall, we really appreciate these changes.  Just that one change and I think we'll mostly be good.

I'll reach out to someone to take a look at the wording to make sure it matches our documentation writing style. 👍

2017-05-12 21:46 UTC, brianhw commented on en_us/install_operations/source/insights/elastic_mapreduce.rst
> +`default EC2 role for Amazon EMR`_ used by AWS. The command `aws emr create-default-roles` facilitates this task. For more info see [this](https://goo.gl/OW8f6I) link
Nit:  also please end the sentence with a period. : )

2017-05-12 21:51 UTC, brianhw commented on en_us/install_operations/source/insights/elastic_mapreduce.rst
> +`default EC2 role for Amazon EMR`_ used by AWS. The command `aws emr create-default-roles` facilitates this task. For more info see [this](https://goo.gl/OW8f6I) link
Also, in terms of style, we tend to avoid referring to "this link", but rather have an inline name for the link that describes what it is.

2017-06-05 19:52 UTC, grantgoodmanedX requested changes

2017-06-05 19:52 UTC, grantgoodmanedX commented on en_us/install_operations/source/insights/elastic_mapreduce.rst
> +`default EC2 role for Amazon EMR`_ used by AWS. The command `aws emr create-default-roles` facilitates this task. For more info refer to [Default IAM Roles for Amazon EMR](http://docs.aws.amazon.com/
A few changes to match edX styles and link practices:

The command ``aws emr
create-default-roles`` facilitates this task. For more information refer to
`Default IAM Roles for Amazon EMR`_.

Also, you need to create a role named ``emr`` with the policy
``AmazonElasticMapReduceforEC2Role`` for the EC2 instance profile.

2017-06-12 14:31 UTC, grantgoodmanedX commented on en_us/install_operations/source/insights/elastic_mapreduce.rst
> +`default EC2 role for Amazon EMR`_ used by AWS. The command `aws emr create-default-roles` facilitates this task. For more info refer to [Default IAM Roles for Amazon EMR](http://docs.aws.amazon.com/
@aqt01 Are you able to make these style changes? If it's not convenient, I can take them over and get this merged.

2017-06-20 15:56 UTC, grantgoodmanedX commented
I've merged corresponding changes in https://github.com/edx/edx-documentation/pull/1519 , so I think we can close this PR.

2017-07-10 20:48 UTC, closed without merging