New paragraph about OS support
openedx-unsupported/edx-documentation pull request #1497
Opened 2017-05-04 14:27 UTC by grantgoodmanedX

## [DOC-3648](https://openedx.atlassian.net/browse/DOC-3648)

In the Installation Options section, I made it more explicit that only Ubuntu is supported and pointed to Vagrant for OS options. Am I correct that you can use Windows versions of Vagrant to run fullstack and devstack?

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @nedbat 
- [ ] Doc team review (copy edit): @edx/doc 

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Squash commits

2017-05-04 15:46 UTC, nedbat requested changes

2017-05-04 15:46 UTC, nedbat commented on en_us/install_operations/source/installation/installation_options.rst
> +a Vagrant virtual machine running on Linux, Mac OS, or Windows systems. See the
I believe you can run Fullstack in Vagrant on Windows, but Devstack will not work.

2017-05-10 14:55 UTC, nedbat approved these changes

2017-05-10 18:25 UTC, catong commented
👍

2017-05-15 15:48 UTC, merged