Add edx.forum.thread.viewed event to research guide
openedx-unsupported/edx-documentation pull request #1532
Opened 2017-06-29 19:00 UTC by srpearce

## [DOC-3657](https://openedx.atlassian.net/browse/DOC-3657)

This PR adds the `edx.forum.thread.viewed` event to the research guide.

### Date Needed (optional)

5 Jul 2017

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @kdmccormick 
- [ ] Subject matter expert: @dsjen 
- [ ] Doc team review (copy edit): @edx/doc

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2017-06-29 19:04 UTC, grantgoodmanedX approved these changes
Looks good 👍

2017-06-29 19:10 UTC, kdmccormick commented on en_us/data/source/internal_data_formats/tracking_logs.rst
> +* ``title``
`title_truncated` is also in the event :)

2017-06-29 19:12 UTC, srpearce commented on en_us/data/source/internal_data_formats/tracking_logs.rst
> +* ``title``
Oh, rats. I thought so, but forgot to double-check.

2017-06-29 19:23 UTC, kdmccormick commented on en_us/data/source/internal_data_formats/tracking_logs.rst
>         emitted.
This actually has changed slightly. View events can come from mobile, where the threads are requested through the Mobile API. However, for the `url` field, we still use the browser URL no matter what the source is. So it's inaccurate now to say that this is the URL the user was visiting.

Accounting for this change, it might read something like "The escaped URL of the page from which the thread can be viewed."

2017-06-30 19:10 UTC, dsjen reviewed
Thanks! I left a comment about `target_username` for mobile apps. @kdmccormick, please confirm! :)

2017-06-30 19:10 UTC, dsjen commented on en_us/data/source/internal_data_formats/tracking_logs.rst
>         emitted.
Nice catch!

2017-06-30 19:10 UTC, dsjen commented on en_us/data/source/internal_data_formats/tracking_logs.rst
> +  The initial version of ``edx.forum.thread.viewed``, added DD Jul 2017, does
Sorry, I think we mislead you earlier about how this is going to work. We were able to figure out a way to include mobile views using the existing systems, but the `target_username` will not be available until the new version of the mobile apps.  @kdmccormick, please correct me if I'm wrong!

2017-07-03 18:34 UTC, srpearce commented on en_us/data/source/internal_data_formats/tracking_logs.rst
> +  The initial version of ``edx.forum.thread.viewed``, added DD Jul 2017, does
@dsjen Is this better? 

The initial version of ``edx.forum.thread.viewed``, added DD Jul 2017, does not include the ``target_username`` member field for discussion threads that are viewed on mobile devices. Future versions of this event will include the ``target_username`` member field for discussion threads on all devices.

2017-07-03 21:09 UTC, dsjen commented on en_us/data/source/internal_data_formats/tracking_logs.rst
> +  The initial version of ``edx.forum.thread.viewed``, added DD Jul 2017, does
Yeah! That sounds good to me!

2017-07-04 15:48 UTC, kdmccormick commented
LGTM! :+1:

2017-07-04 15:49 UTC, kdmccormick approved these changes

2017-07-07 13:24 UTC, kdmccormick requested changes

2017-07-07 13:24 UTC, kdmccormick commented on en_us/data/source/internal_data_formats/tracking_logs.rst
> +
Might be good to note that the `'target_username'` field is omitted from the event if the thread is posted anonymously.

2017-07-10 19:14 UTC, kdmccormick commented on en_us/data/source/internal_data_formats/tracking_logs.rst
> +  The initial version of ``edx.forum.thread.viewed``, added DD Jul 2017, does
Looks good, other than a nitpick: it's not future versions of the *event* that will have `target_username`; it's future versions of the *apps* that will emit events with `target_username`.

2017-07-10 21:34 UTC, srpearce commented on en_us/data/source/internal_data_formats/tracking_logs.rst
> +
Thanks, @kdmccormick. Do you know if that's true for the edx.forum.thread.voted event as well? (See line 4269—I added it assuming that the same is true for this event, but would like to make sure.)

2017-07-10 22:31 UTC, kdmccormick commented on en_us/data/source/internal_data_formats/tracking_logs.rst
> +
Ah, good catch! I believe it's actually not the case for `edx.forum.thread.voted`, and the fact that's its inconsistent is probably a bad thing. I'll talk with someone tomorrow and see how to reconcile this.

2017-07-12 15:26 UTC, srpearce commented on en_us/data/source/internal_data_formats/tracking_logs.rst
> +  The initial version of ``edx.forum.thread.viewed``, added DD Jul 2017, does
@kdmccormick Would it be correct to say one of these?

Versions 2.8 and earlier of the edX iOS and Android apps do not include the ``target_username`` member field in the ``edx.forum.thread.viewed`` event. Future versions of the mobile apps will include this member field.

or

Versions 2.8 and earlier of the edX iOS and Android apps do not include the ``target_username`` member field in the ``edx.forum.thread.viewed`` event. Versions 2.9 and later of the mobile apps include this member field.

2017-07-13 15:22 UTC, kdmccormick commented on en_us/data/source/internal_data_formats/tracking_logs.rst
> +
@srpearce After some discussion with @brianhw, we decided that this would be the best setup:
- edx.forum.thread.voted: Includes `target_username` whether or not thread is anonymous
- edx.forum.thread.viewed:
  - For browser views: Includes `target_username` whether or not thread is anonymous
  - For mobile views: Does not include target_username for anonymous threads

2017-07-13 15:22 UTC, kdmccormick commented on en_us/data/source/internal_data_formats/tracking_logs.rst
> +  The initial version of ``edx.forum.thread.viewed``, added DD Jul 2017, does
@srpearce Slightly modified:

Versions 2.9.1 and earlier of the edX iOS app and versions 2.8.1 and earlier of the edX Android app do not include the `target_username member` field in the `edx.forum.thread.viewed` event. Later versions of each of the mobile apps include this member field.

2017-07-13 15:34 UTC, kdmccormick commented
- edx.forum.thread.voted: Includes `target_username` whether or not thread is anonymous. This is true regardless of the app version
- edx.forum.thread.viewed:
  - For iOS<=2.9.1 and Android<=2.8.1:
      - Does not include `target_username`
  - For later versions of both apps:
    - For browser views: Includes `target_username` whether or not thread is anonymous
    - For mobile views: Includes `target_username` for NON-anonymous threads

2017-07-13 16:57 UTC, srpearce commented on en_us/data/source/internal_data_formats/tracking_logs.rst
> +   * - ``target_username``
@kdmccormick OK, can we go with the following description for this member field?

2017-07-13 17:04 UTC, kdmccormick approved these changes
Looks great! 👍

2017-07-13 17:05 UTC, kdmccormick commented on en_us/data/source/internal_data_formats/tracking_logs.rst
> +   * - ``target_username``
Perfect!

2017-07-13 17:31 UTC, merged