Update and consolidate video sections
openedx-unsupported/edx-documentation pull request #1534
Opened 2017-06-30 19:30 UTC by srpearce

## [DOC-3643](https://openedx.atlassian.net/browse/DOC-3643)

Update and consolidate video sections pending the addition of an option to choose thumbnail images (for partners only).

### Date Needed (optional)

5 July 2017

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @muzaffaryousaf (**Upload Video Files section only)**
- [ ] Doc team review (copy edit): @edx/doc
- [ ] Product review: @sstack22 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

*Make sure to review both versions, because they're different.*

- [ ] **Partners**
  [Working with Video Components](http://draft-partner-july-2017-video-changes.readthedocs.io/en/latest/course_components/create_video.html) (single file)
  [Creating and Adding Video Content](http://draft-partner-july-2017-video-changes.readthedocs.io/en/latest/video/index.html) (whole section)

- [ ] **Open edX**
  [Working with Video Components](http://draft-open-edx-july-2017-video-changes.readthedocs.io/en/latest/course_components/create_video.html) (single file)
  [Creating and Adding Video Content](http://draft-open-edx-july-2017-video-changes.readthedocs.io/en/latest/video/index.html) (whole section)

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2017-06-30 19:48 UTC, srpearce commented on en_us/course_authors/source/video/upload_video_edx/video_uploads.rst
@muzaffaryousaf Can you review lines 86-96 below? You don't need to review this entire PR.

2017-07-03 06:13 UTC, debchatigny commented on en_us/course_authors/source/video/upload_video_edx/video_overview.rst
> +First, the edX partner support team works with the appointed video
Should this be initial capitals (edX Partner Support Team)?

2017-07-03 06:14 UTC, debchatigny commented on en_us/course_authors/source/video/upload_video_edx/video_overview.rst
> +organization at YouTube™ and Amazon Web Services™ (AWS). For more information
Suggest adding Amazon Web Services (AWS) to the glossary.

2017-07-03 06:16 UTC, debchatigny commented on en_us/course_authors/source/video/upload_video_edx/video_setup.rst
> +edX partner support to make sure that the following preparatory tasks are
Initial capitalize edX Partner Support.

2017-07-03 06:17 UTC, debchatigny commented on en_us/course_authors/source/video/upload_video_edx/video_uploads.rst
> +the course. Your video administrator coordinates this task with the edX partner
Initial capitalize edX Partner Support.

2017-07-03 06:31 UTC, debchatigny commented on en_us/shared/video/additional_transcript_options.rst
> +transcripts for these videos, you name them video1_ES.srt and video2_ES.srt.
As we recommend course creators use the ISO 639-1 codes in 9.8.2.3, should the locales be listed in lowercase (which is how I've typically seen them in file names)?

2017-07-03 06:33 UTC, debchatigny commented on en_us/shared/video/create_transcript.rst
> +Transcripts are required for your videos. Transcripts help learners with
You could mention here that transcripts help all learners by providing an alternative way to consume the content, if they can't have sound on when watching videos, for example.

2017-07-03 06:36 UTC, debchatigny commented on en_us/shared/video/create_video.rst
> +      For courses on edx.org, in a later step, you upload your videos to edX,
I'd reword: For courses on edx.org, in a later step, once you upload your videos to edX, edX automatically converts each of your video files into ..

2017-07-03 06:39 UTC, debchatigny commented on en_us/shared/video/create_video.rst
> + media file. For example, if you create the file in a country that uses the PAL
Do we have a file that captures various acronyms/video-specific terminology? If not, I'd suggest adding terms like VBR, PAL, fps, and NTSC to the glossary.

2017-07-03 06:40 UTC, debchatigny commented on en_us/shared/video/create_video.rst
> + Typically you export at the same frame rate that was used when you created the
Insert comma: Typically, you..

2017-07-03 06:42 UTC, debchatigny commented on en_us/shared/video/upload_video.rst
> +  slow or intermittent Internet connections.
Internet is lowercase.

2017-07-03 07:22 UTC, muzaffaryousaf commented
@mushtaqak can you review the related part here for video images/thumbnails ?(video/upload_video_edx/video_uploads.rst lines 86-96 only)

2017-07-03 13:31 UTC, mushtaqak commented on en_us/course_authors/source/video/upload_video_edx/video_uploads.rst
> +   to play. Studio provides a thumbnail image by default for your videos.
@srpearce We are not showing default generated image to end user right now in this feature release. So we would probably remove this line `Studio provides a thumbnail image by default for your videos.`

So for now, we would 1st upload image through **Add Thumbnail** then if we want to update/change the image, we can use **Edit Thumbnail**

2017-07-03 13:33 UTC, mushtaqak requested changes
@srpearce I left a commit regarding video images. We are not yet showing showing default images for videos to user. Need to update it.

2017-07-05 15:19 UTC, catong commented on en_us/course_authors/source/video/create_preroll_video.rst
> +Add a Pre-Roll Video to Your edX Course
@srpearce What's the reason for renaming the heading? Our standard naming conventions would have "Adding" for conceptual topics and "Add..." for the procedural topic.

2017-07-05 15:20 UTC, catong commented on en_us/course_authors/source/video/additional_transcript_options.rst
> +.. note::
Suggestion: move the note earlier, immediately following the heading?

2017-07-05 15:22 UTC, catong commented on en_us/course_authors/source/video/upload_video_edx/index.rst
> +  :ref:`Step 3. Upload a Video for an edx Edge Course <Post the Video Online>`.
Is "Post the Video Online" the correct anchor? Looks like it should be "Upload Video"?

2017-07-05 15:23 UTC, catong commented on en_us/course_authors/source/video/upload_video_edx/index.rst
> +  slow or intermittent Internet connections.
lc "i" for "internet"

2017-07-05 15:23 UTC, catong commented on en_us/course_authors/source/video/upload_video_edx/video_overview.rst
> +  :ref:`Step 3. Upload a Video for an edx Edge Course <Post the Video Online>`.
Is "Post the Video Online" the correct anchor label?

2017-07-05 15:28 UTC, catong commented on en_us/course_authors/source/video/upload_video_edx/video_overview.rst
> +Course Team Add Video Overview
This heading reads oddly and would be difficult to translate. Maybe "Overview of Course Team Video Upload Process"?

2017-07-05 15:30 UTC, catong commented on en_us/course_authors/source/video/upload_video_edx/video_setup.rst
> + complete before the course team begins to add videos to the course in Studio.
"it must be complete" -> "it must be completed"

2017-07-05 15:34 UTC, catong commented on en_us/course_authors/source/video/upload_video_edx/video_uploads.rst
> +Remove Video Files
@srpearce Adding "Files to the heading" makes the actual impact of this procedure confusing - it's what I deliberately avoided when I worked on the story that enabled this cleanup. 
@muzaffaryousaf can confirm, but files are not removed; this procedure just cleans up the listing of files on the Video Uploads page.

2017-07-05 15:45 UTC, catong commented
@srpearce I left comments inline, and have a question about some flowcharts. In encoding_proc_overview.png. I'm confused about the "Upload" step having an arrow back to the "Assign Video ID" box, but I see the same thing in encoding_process_overview.png. However, the other flowcharts show the process ending after the upload step.

2017-07-05 18:55 UTC, srpearce commented
@catong The encoding_process.png flowchart is meant to show in more detail what happens in the encoding and hosting process (the overview flowchart just says "encode files" and "upload...", while the encoding_process.png flowchart shows the process encoding the original file into four separate files that are uploaded to four separate places). I'll try to make the overview flowchart more clear, however.

2017-07-05 18:58 UTC, srpearce commented on en_us/course_authors/source/video/create_preroll_video.rst
> +Add a Pre-Roll Video to Your edX Course
I'd like to maintain consistency with the other headings at that level:

![screenshot 12](https://user-images.githubusercontent.com/3493253/27877417-872821c0-6188-11e7-807c-fa48f30c3e28.png)

2017-07-05 18:58 UTC, srpearce commented on en_us/course_authors/source/video/upload_video_edx/video_uploads.rst
> +Remove Video Files
I probably wanted it to be consistent with the other heading ("Upload Video Files"), and I didn't know the files aren't actually deleted. I'll change this back.

2017-07-05 20:04 UTC, srpearce commented on en_us/course_authors/source/video/upload_video_edx/video_uploads.rst
@mushtaqak Made the changes you requested; are lines 86-89 below now accurate?

2017-07-06 07:44 UTC, mushtaqak approved these changes
@srpearce This is looking good 👍 Thanks.

I have left one suggestion/question regarding **Edit Thumbnail** if we want to tell user about it or not. It's up to you if you want to include it in docs.

2017-07-06 07:44 UTC, mushtaqak commented on en_us/course_authors/source/video/upload_video_edx/video_uploads.rst
This is looking good 👍 

I have one suggestion/question  : Should we also tell user about **Edit Thumbnail** option if he/she wishes to change image ?

2017-07-07 14:24 UTC, srpearce commented on en_us/course_authors/source/video/upload_video_edx/video_uploads.rst
@mushtaqak Yes, that's a great suggestion. Thanks!

2017-07-10 18:53 UTC, merged