WIP DOC-3719 Course Home and Course Tool Events
openedx-unsupported/edx-documentation pull request #1547
Opened 2017-07-20 19:40 UTC by catong

## [DOC-3719](https://openedx.atlassian.net/browse/DOC-3719)

Document in the edX Research Guide the course home and course tool events described on this wiki page: https://openedx.atlassian.net/wiki/display/AN/Course+Home+Page+Event+Design

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2017-07-26 12:27 UTC, robrap reviewed
Thanks @catong.

2017-07-26 12:27 UTC, robrap commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +The browser emits an ``edx.course.tool.accessed`` event when a user visits the
I know this is very late in the game, but reading the docs made me wonder if we have the right verb.
@marco @catong @stroilova @HarryRein: 
Can you remind me of what words we agreed were conventions and what each means?  For example, "clicked", "accessed", "viewed", etc.?  Which words imply or require client-side vs server-side events?  Although some naming conventions exist, I do not see this level of detail.  Maybe it is not needed?

2017-07-26 12:27 UTC, robrap commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +       ``edx.bookmarks`` and ``edx.reviews``.
Also 'edx.updates'.

2017-07-27 21:17 UTC, stroilova commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +The browser emits an ``edx.course.tool.accessed`` event when a user visits the
@robrap  I don't know if we had complete conventions yet, and I trust your team's judgment here. Accessed or clicked seems OK for client side browser events.

2017-07-27 21:30 UTC, robrap commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +The browser emits an ``edx.course.tool.accessed`` event when a user visits the
Thanks @stroilova.  Seems like @catong / docs could help come up with conventions, unless we don't care if everyone uses a variety of worse for the same things.

2017-07-28 14:09 UTC, catong commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +``edx.bookmark.accessed``
@robrap @HarryRein When a learner accesses the *Bookmarks* page, does this existing ```edx.bookmark.accessed``` event get emitted as well as the new ```edx.course.tools.accessed``` event?

2017-07-28 14:45 UTC, robrap commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +``edx.bookmark.accessed``
I think that `edx.bookmark.accessed` event is for accessing an individual bookmark.  However, I do think there will also be a server side `edx.bookmark.listed` that is fired.

2017-07-28 14:49 UTC, catong commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +``edx.bookmark.accessed``
Ah, good catch @robrap. So if a learner accesses the "My Bookmarks" page, both the ```edx.bookmark.listed``` and ```edx.course.tools.accessed``` events are emitted.

2017-07-28 16:38 UTC, stroilova commented
Thanks for the clarification @catong  @robrap !

This Bookmarks event workflow would be valuable to quickly capture in the docs, if that is easy ("nice to have")

@grantgoodmanedX  this is an example of the types of FAQ researchers ask -- this would be at the local level.

PS>> Grant, I'll follow up in an email, but maybe we can schedule a quick Research FAQ brainstorming session, to go this & other top FAQs -- maybe next week? Let me know if anyone else is interested!

2017-07-28 16:39 UTC, stroilova commented
👍 
one "nice to have" comment -- but not a blocker for merging

Thanks so much

2017-07-28 17:09 UTC, robrap commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +``edx.bookmark.accessed``
I believe so.

2017-07-28 17:32 UTC, catong commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +``edx.bookmark.accessed``
@robrap One more question :-) The edx.bookmark.listed event is emitted for each page that a user visits (if the list of bookmarks exceeds a single page). Is edx.course.tool.accessed emitted just once on the first visit? or does it behave the same as edx.bookmark.listed and get fired for each bookmark list page?

2017-07-28 17:38 UTC, robrap commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +``edx.bookmark.accessed``
The tool accessed event is browser side, and is triggered once when the user clicks the link under Tools.

2017-07-28 17:45 UTC, catong commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +``edx.bookmark.accessed``
Thanks @robrap I rewrote the sentence describing ```edx.course.tool.accessed``` to clarify when the event is emitted.

2017-07-28 17:49 UTC, catong commented
@robrap @edx/doc This PR is ready for your final review. Thanks!

2017-07-28 18:20 UTC, srpearce commented
@edx/doc I can take this one.

2017-07-28 18:31 UTC, srpearce approved these changes
A few nits (most of which I realized after the fact are for old text).

2017-07-28 18:31 UTC, srpearce commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +``edx.bookmark.listed``.
"the x event is emitted" --> "the browser emits the x event"

2017-07-28 18:31 UTC, srpearce commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +     - The number of pages a learner has bookmarked. If the ``course_id`` is
If the course_id value is specified
or
If course_id is specified

2017-07-28 18:31 UTC, srpearce commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +     - Possible values are 'per_course' or 'all_courses'.
Should use the double backquotes for "per_course" and "all_courses" (as in line 1259)

2017-07-28 18:31 UTC, srpearce commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +Reviews, or Updates.
Earlier "Bookmarks" is in bold—I think it should be here too (along with "Reviews" and "Updates").

2017-07-28 18:31 UTC, srpearce commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +``edx.bookmark.listed`` event is emitted in addition to
the browser emits the x event

2017-07-28 18:31 UTC, srpearce commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +       ``edx.bookmarks``, ``edx.reviews``, and ``edx.updates``.
We don't use a colon to introduce lists of possible values elsewhere.

2017-07-28 21:28 UTC, robrap commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +The browser emits this event when a user clicks **Bookmarks** under the
I'll look Monday if this is server side on bookmark listing.

2017-07-31 15:41 UTC, robrap requested changes
Thanks @catong.  I noted the differences I found from the code in comments.  Also, it seems that the wiki page documented the back-end events as "bookmarks API".  See: https://openedx.atlassian.net/wiki/spaces/AN/pages/29689303/Bookmarks+Event+Design

2017-07-31 15:41 UTC, robrap commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +The browser emits this event when a user bookmarks a page in the course.
@catong This one is server-side.

2017-07-31 15:41 UTC, robrap commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +The browser emits this event when a user clicks **Bookmarks** under the
This is also server side.  It happens each time a page is requested.

2017-07-31 15:41 UTC, robrap commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +When a user clicks **Bookmarks** to view the list of bookmarks, the browser
In my opinion, I would leave this out and simply let `edx.bookmark.listed` be the section that describes when it is fired.  I imagine there are lots of places where we might send multiple events, and I think it would be harder to maintain the docs to cross-reference them all for each potential user interaction.

2017-07-31 16:08 UTC, catong commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +When a user clicks **Bookmarks** to view the list of bookmarks, the browser
@robrap Is your suggestion to leave out the paragraph starting "when a user clicks **Bookmarks**"? (Just want to clarify what "this" refers to)

2017-07-31 16:33 UTC, robrap commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +When a user clicks **Bookmarks** to view the list of bookmarks, the browser
Yes. And to clarify, it is not that anything is wrong with this, it is just that it seems unnecessary and more difficult to maintain.

2017-07-31 18:13 UTC, catong commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +When a user clicks **Bookmarks** to view the list of bookmarks, the browser
@robrap I'd actually like to leave the sentence in - it seems unnecessary, but it is also confusing/will raise doubt, to make the cross-reference in one direction and not the other.

2017-07-31 18:46 UTC, catong commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +**Event Source**: Browser
@robrap Is ``edx.bookmark.removed`` also a server event?

2017-07-31 20:12 UTC, robrap commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +When a user clicks **Bookmarks** to view the list of bookmarks, the browser
I partly agree.  I missed the other cross-reference and I would remove the other cross-reference as well.

1.  I think it would be more maintainable to have each event clarify when it is triggered, and not include cross-referencing at all. 
2. Note that one of these is a client-side event and one is a server-side event.  This sentence is misleading if this difference is not mentioned, but gets too long if it is mentioned.
3. If you feel strongly about keeping cross-referencing, I would propose it gets called-out in a separate subsection (or sentence) and simply reads something like: "See also ``edx.course.tool.accessed`` event."

Let me know what you think.  Thanks.

2017-07-31 20:16 UTC, catong commented on en_us/data/source/internal_data_formats/tracking_logs/student_event_types.rst
> +When a user clicks **Bookmarks** to view the list of bookmarks, the browser
@robrap "See also" is a good idea. I'll take out the detail and just have the 2 events cross-referenced that way. Thanks!

2017-08-01 15:05 UTC, robrap approved these changes
Thanks @catong.  Minor fix proposed.  Then merge away. :)

2017-08-01 15:05 UTC, robrap commented on en_us/data/source/internal_data_formats/event_list.rst
> +   * - ``edx.course.tool.accessed``
Should this be in alphabetical order?

2017-08-01 15:06 UTC, catong commented on en_us/data/source/internal_data_formats/event_list.rst
> +   * - ``edx.course.tool.accessed``
Agggggh.

2017-08-01 15:28 UTC, catong commented
Merging https://github.com/edx/edx-documentation/pull/1547

2017-08-01 15:28 UTC, merged