Fix XBlock SDK checkout
openedx-unsupported/edx-documentation pull request #1549
Opened 2017-07-24 11:21 UTC by regisb

The latest XBlock SDK version (v0.1.4) is compatible with Django 1.11,
but not Django 1.8. Consequently, the `syncdb` command will not work
with v0.1.4. To address this problem in the Open edX documentation, we
choose to stick with the same Django version as Ficus/Ginkgo.

Affected user: https://openedx.slack.com/archives/C0GF6FTHA/p1500890543190218
(I know another faced this problem before, but I can't remember who)

### Date Needed

It would be great if this change was pushed to the official documentation as soon as possible, because XBlock developer currently can't create new XBlocks by following the documentation. The error that they obtain is cryptic ("no such table: workbench_xblockstate").

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @mhoeber (wrote the rest of the documentation page)

### Testing

- [x] Ran ./run_tests.sh without warnings or errors

```********** All builds done ************
TOTAL SPHINX ERRORS: 0
TOTAL SPHINX WARNINGS: 8
OTHER BUILD ERRORS: 0
There were problems while building the following projects:
en_us/course_authors
en_us/open_edx_course_authors```

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2017-07-24 11:21 UTC, edx-webhook commented
Thanks for the pull request, @regisb! I've created [OSPR-1843](https://openedx.atlassian.net/browse/OSPR-1843) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-documentation/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2017-07-24 16:47 UTC, efischer19 requested changes
Per [django docs](https://docs.djangoproject.com/en/1.7/ref/django-admin/#syncdb), `syncdb` has been a simple alias to `migrate` since 1.7. I think a better fix for this issue would be to `s/syncdb/migrate` in  https://github.com/edx/edx-documentation/blob/master/en_us/xblock-tutorial/source/reusable/create_db.rst.

This will allow developers to continue using the latest version, which should work correctly with both django 1.8 and 1.11.

2017-07-24 17:02 UTC, regisb commented
@efischer19 `syncdb` is no longer an alias for `migrate` in Django 1.11:
https://docs.djangoproject.com/en/1.11/ref/django-admin/#syncdb

The command is no longer available: https://github.com/django/django/tree/master/django/core/management/commands

I have considered modifying the documentation to rely on django 1.11 instead of 1.8, but that would mean that developers would create XBlocks with the django 1.11 API, whereas edx-platform still relies on django 1.8. This could cause XBlocks to work in the workbench, but not with Ficus/Ginkgo.

2017-07-24 17:26 UTC, efischer19 commented
Right, it *was* an alias, it is no longer. At any point during 1.8's usage, we can update the documentation to say `migrate` instead of `syncdb`; this will not change anything. As of 1.11, `syncdb` is no longer supported, so we *must* make the harmless change.

xblock-sdk, along with a lot of other repos, is designed to work with a range of django versions. The documentation should rely on django, but not on a specific version being installed. Thus, we should no longer refer to the 1.8 exclusive `syncdb` command and use the identical, but available in the full range of supported versions, `migrate`.

You're right in that a developer *could* make an XBlock that relies on some new, "only-available-in-1.11" feature using the latest version of xblock-sdk, and that XBlock would not work with Ficus/Ginkgo. However, the vast majority will work correctly in both versions, and updating the range of allowed versions in xblock-sdk now makes the work to update edx-platform to 1.11 much easier in the future.

2017-07-25 06:10 UTC, regisb commented
You're right @efischer19, I missed the point in my previous message. Since `migrate` is common to Django 1.8 and 1.11, it makes more sense to use `migrate` than `syncdb`.
I'll test the install procedure with v0.1.4 and update this PR.

2017-08-08 08:08 UTC, regisb commented
Any chance to see this merged any time soon? Unless I'm mistaken, the travis build warnings are not related to this commit.

2017-08-08 15:48 UTC, efischer19 approved these changes
Sorry for losing track of this one @regisb! I agree that the failures are unrelated and we ought to merge this, but I'll ask someone @edx/doc to verify that.

The warnings look like this, but `en_us/xblock-tutorial/source/reusable/create_db.rst` is the only file touched by this PR.

```
../shared/course_features/cohorts/cohorted_courseware.rst:144: WARNING: undefined label: specify components in courseware as available only to certain content groups (if the link has no caption the label must precede a section header)
../shared/course_features/cohorts/cohorted_courseware.rst:223: WARNING: undefined label: specify components in courseware as available only to certain content groups (if the link has no caption the label must precede a section header)
../shared/developing_course/workflow.rst:94: WARNING: undefined label: content groups (if the link has no caption the label must precede a section header)
../shared/developing_course/workflow.rst:94: WARNING: undefined label: enrollment track groups (if the link has no caption the label must precede a section header)
```

2017-08-08 16:06 UTC, catong commented
@regisb Can you please rebase against master? The errors should clear after you do that.

2017-08-08 17:20 UTC, merged

2017-08-08 20:29 UTC, regisb commented
Awesome, thanks!

2017-08-08 20:44 UTC, catong commented
@regisb Thank you very much for your contribution!