Add info for edx.grades.subsection.score_overriden event
openedx-unsupported/edx-documentation pull request #1562
Opened 2017-08-08 19:03 UTC by srpearce

## [DOC-3745](https://openedx.atlassian.net/browse/DOC-3745)

This PR adds documentation for the edx.grades.subsection.score_overridden event, which is added to the platform as part of the work for EDUCATOR-409.

### Date Needed (optional)

10 Aug 2017

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @thallada 
- [ ] Doc team review (copy edit): @edx/doc
- [ ] Product review: @katymywy

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2017-08-08 20:21 UTC, catong commented on en_us/data/source/internal_data_formats/tracking_logs/course_team_event_types.rst
> +This event will be emitted when a learner's subsection score has been
"will be emitted" -> "is emitted"

2017-08-08 20:21 UTC, catong commented on en_us/data/source/internal_data_formats/tracking_logs/course_team_event_types.rst
> +overridden (currently, only the result of an admin rejecting a proctored exam
"admin" -> "course team member with the Admin role" ? Or "course team members with the Admin or Staff role"

2017-08-08 20:22 UTC, catong commented on en_us/data/source/internal_data_formats/tracking_logs/course_team_event_types.rst
> +attempt or transitioning it from rejected to verified).
"transitioning it" -> "changing the exam result from Rejected to Verified"

2017-08-08 20:22 UTC, catong commented on en_us/data/source/internal_data_formats/tracking_logs/course_team_event_types.rst
> +**History**: Added XX Aug 2017.
Remember to add the actual date

2017-08-09 01:08 UTC, katymyw commented
This might be a question for @thallada , but how would the following fields get set for a subsection grade change? They seem like they would only be relevant for problem grade changes.

problem_id
only_if_higher

2017-08-09 15:29 UTC, thallada commented
@katymyw for the edx.grades.subsection.score_overridden event, `problem_id` maps to the subsection usage key and `only_if_higher` is actually passed to the function that does the override, but it is always False right now for overrides.

2017-08-09 17:58 UTC, thallada requested changes
Looks good besides the changes I mentioned inline.

2017-08-09 17:58 UTC, thallada commented on en_us/data/source/internal_data_formats/tracking_logs/course_team_event_types.rst
> +overridden (currently, only the result of an admin rejecting a proctored exam
It is actually "edX support team member with the Admin role"

2017-08-09 17:58 UTC, thallada commented on en_us/data/source/internal_data_formats/tracking_logs/course_team_event_types.rst
> +attempt or transitioning it from rejected to verified).
Based on what I learned from what the support team actually does in the Django admin, I would say "(currently, only the result of edX support team member with the Admin role rejecting a proctored exam by saving the proctored exam software secure review as Suspicious, or changing it from Suspicious to Clean)"

2017-08-09 19:24 UTC, srpearce commented on en_us/data/source/internal_data_formats/tracking_logs/course_team_event_types.rst
> +**History**: Added XX Aug 2017.
I have that as a "TO DO" in my PR description. ;-)

2017-08-09 19:33 UTC, katymyw commented
Thanks for the additional info on those fields @thallada. 

Everything looks good to me 👍

2017-08-09 19:37 UTC, srpearce commented on en_us/data/source/internal_data_formats/tracking_logs/course_team_event_types.rst
> +
@thallada Is the following description accurate?

2017-08-09 19:37 UTC, srpearce commented on en_us/data/source/internal_data_formats/tracking_logs/course_team_event_types.rst
> +     - Boolean
@thallada I also changed the following description. Can you confirm it's OK?

2017-08-09 20:37 UTC, thallada approved these changes
Just one more tweak, everything else looks good to me.

2017-08-09 20:37 UTC, thallada commented on en_us/data/source/internal_data_formats/tracking_logs/course_team_event_types.rst
> +     - Boolean
That looks right to me :thumbsup:

2017-08-09 20:37 UTC, thallada commented on en_us/data/source/internal_data_formats/tracking_logs/course_team_event_types.rst
> +
To be totally accurate, this should be: "overrides **or removes the override of** a learner's subsection score" or something along those lines.

2017-08-25 20:47 UTC, merged