WIP: DOC-3753 ICR updates
openedx-unsupported/edx-documentation pull request #1581
Opened 2017-08-21 21:10 UTC by catong

## [DOC-3753](https://openedx.atlassian.net/browse/DOC-3753)

**Not yet ready for review**

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?):
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2017-09-25 17:39 UTC, catong commented on en_us/install_operations/source/ecommerce/test_ecommerce.rst
> +.. the ecomm version has these commands for granting superuser permissions to the account:
@mjfrey I've added comments in this file to flag areas where the ecomm docs and the edx-doc docs differ. Please review for accuracy. Thanks!

2017-09-26 22:00 UTC, mjfrey requested changes
First pass at some minor things.  Otherwise looks good.

2017-09-26 22:00 UTC, mjfrey commented on en_us/install_operations/source/ecommerce/create_products/create_course_seats.rst
> +   * Bulk Enrollment Code Yes/No
In order to enable Enrollment Codes, the toggle must be turned on in the site configuration.  This is done via the Django admin->Site Configuration

2017-09-26 22:00 UTC, mjfrey commented on en_us/install_operations/source/ecommerce/create_products/create_products_overview.rst
> +
Note: This must be enabled in the Site Configuration in order to use.

2017-09-26 22:00 UTC, mjfrey commented on en_us/install_operations/source/ecommerce/create_products/create_program_offers.rst
> +#. Obtain the Program UUID for the program for which you are creating an offer.
This UUID is obtained from the Discovery Service Django admin.

2017-09-26 22:00 UTC, mjfrey commented on en_us/install_operations/source/ecommerce/create_products/create_program_offers.rst
> +
You may want to mention the Site Configuration “Enable Partial Programs”.  This setting allow the “Complete my bundle” feature.  Without that enabled, the discount will only be reflected if all of the courses in a program are in the learners basket.

2017-09-28 15:37 UTC, catong commented on en_us/install_operations/source/ecommerce/create_products/create_program_offers.rst
> +#. Obtain the Program UUID for the program for which you are creating an offer.
Modified the line below to specifically indicate it's the Discovery Service Django admin.

2017-09-28 17:32 UTC, catong commented on en_us/install_operations/source/ecommerce/create_products/create_program_offers.rst
> +
Added as a note

2017-09-28 17:38 UTC, catong commented on en_us/install_operations/source/ecommerce/create_products/create_products_overview.rst
> +
This is only an intro in the overview topic, so I'm going to the wording as is here. In the create_enrollment_codes.rst file, enabling the setting via a site configuration command option is mentioned:
```To enable enrollment codes in the E-Commerce service, run the site
   configuration command together with the following option.

   ::

     ``--enable-enrollment-codes=True``
```

2017-09-29 15:19 UTC, catong commented on en_us/install_operations/source/ecommerce/test_ecommerce.rst
> +.. ecomm version has file path ecommerce/blobmaster/acceptance_tests/config.py
@mjfrey Which path is correct/makes more sense to open edx readers?

2017-09-29 15:19 UTC, catong commented on en_us/install_operations/source/ecommerce/test_ecommerce.rst
> +.. ecomm version has ``make accept``?
@mjfrey Which command is correct?

2017-09-29 15:29 UTC, catong commented on en_us/install_operations/source/ecommerce/test_ecommerce.rst
> +     u.save()
@mjfrey Which version is preferred? (lines 182-183 vs lines 188-192)

2017-10-05 19:04 UTC, catong commented on en_us/install_operations/source/ecommerce/create_products/create_coupons.rst
> +     for **Number of Codes**, and ``1`` for **Maximum Number of Uses**.
@mjfrey is this correct?

2017-10-06 11:46 UTC, mjfrey commented on en_us/install_operations/source/ecommerce/create_products/create_coupons.rst
> +     for **Number of Codes**, and ``1`` for **Maximum Number of Uses**.
That is correct.  However shouldn't the last '1' be '10'?

2017-10-06 11:46 UTC, mjfrey approved these changes
one small comment.

2017-10-06 13:55 UTC, catong commented on en_us/install_operations/source/ecommerce/create_products/create_coupons.rst
> +     for **Number of Codes**, and ``1`` for **Maximum Number of Uses**.
@mjfrey That what I have been confused about; thanks for clarifying.
In the case of 10 customers who can use a code once, if we have "1" for "Number of Codes", we are generating only a single code, correct? So if 10 customers use the same code once each, the system does not count this as 10 uses of the same code - it is taking into account the different users?

2017-10-20 18:18 UTC, grantgoodmanedX requested changes
Most of my comments are in ecommerce/theming.rst, which you didn't modify for this PR, so feel free to push them off to a different ticket that calls for editing that section.

2017-10-20 18:18 UTC, grantgoodmanedX commented on en_us/install_operations/source/ecommerce/create_products/create_coupons.rst
> +     and ``10`` for **Maximum Number of Uses**.
in line 383, "Maximum Number of Usages" should be "Uses"

2017-10-20 18:18 UTC, grantgoodmanedX commented on en_us/install_operations/source/ecommerce/create_products/create_programs.rst
> +functionality" for programs, the LMS and the marketing site also need to know
I don't understand this paragraph. Should we have a more specific list of next steps that need to happen in the LMS and marketing site, with cross-references to the relevant procedures?

2017-10-20 18:18 UTC, grantgoodmanedX commented on en_us/install_operations/source/ecommerce/theming.rst
> +class names or id values of html elements inside a template, as these are used by javascript and/or css and overriding
HTML elements ... JavaScript or CSS

2017-10-20 18:18 UTC, grantgoodmanedX commented on en_us/install_operations/source/ecommerce/theming.rst
> +Any static asset included in ``ecommerce/static`` can be overridden except css files present in ``ecommerce/static/css``.
CSS files (or `` .css`` files)

2017-10-20 18:18 UTC, grantgoodmanedX commented on en_us/install_operations/source/ecommerce/theming.rst
> +Css styles can be overridden via sass overrides explained below.
CSS styles

2017-10-20 18:18 UTC, grantgoodmanedX commented on en_us/install_operations/source/ecommerce/theming.rst
> +    Theme names should be unique and no static asset and/or directory name should be same as theme's name.
Theme names should be unique and  no static asset or directory name can have the same name as the theme.

2017-10-20 18:18 UTC, grantgoodmanedX commented on en_us/install_operations/source/ecommerce/theming.rst
> +After installing a theme, it is associated with sites by adding appropriate entries to the following tables
After you install a theme, you associate it with sites by adding ...

2017-10-20 18:18 UTC, grantgoodmanedX commented on en_us/install_operations/source/ecommerce/theming.rst
> +for local devstack, if Otto server is running at ``localhost:8002`` you can enable a ``my-theme`` by
For example, for local devstack ... , you can enable a theme named ``my-theme`` by adding 
(this and the next few lines need some re-writing for clarity. Also, i'm not sure what our style for spelling Sass is).

2017-10-20 18:18 UTC, grantgoodmanedX commented on en_us/install_operations/source/ecommerce/theming.rst
> +If you have already setup ``COMPREHENSIVE_THEME_DIRS`` then you can use management command for adding
If you have already set up ... then you can use the following management command to add

2017-10-20 18:18 UTC, grantgoodmanedX commented on en_us/install_operations/source/ecommerce/theming.rst
> +.. code-block:: yaml
bash not yaml ?

2017-10-20 18:18 UTC, grantgoodmanedX commented on en_us/install_operations/source/ecommerce/theming.rst
> +    :--settings: settings file to use, ``default: ecommerce.settings.devstack``
This table displays badly. Maybe it would work better as a list, so we can fit the long command examples better?

2017-10-20 18:18 UTC, grantgoodmanedX commented on en_us/install_operations/source/ecommerce/theming.rst
> +Troubleshooting
This section needs rewriting (parallelism, spell out directory, etc.)

2017-10-20 19:55 UTC, catong commented on en_us/install_operations/source/ecommerce/create_products/create_coupons.rst
> +     and ``10`` for **Maximum Number of Uses**.
Good catch; thanks!

2017-10-20 19:56 UTC, catong commented on en_us/install_operations/source/ecommerce/create_products/create_programs.rst
> +functionality" for programs, the LMS and the marketing site also need to know
Oops, that was a "note to self" for expanding the content, that did not get commented out.

2017-10-23 16:02 UTC, catong commented
@grantgoodmanedX Updated per your review comments. Draft HTML also updated. Please re-review and approve if OK. Thanks!

2017-10-23 17:30 UTC, catong commented on en_us/install_operations/source/ecommerce/theming.rst
> +    :--settings: settings file to use, ``default: ecommerce.settings.devstack``
Done!

2017-10-23 19:58 UTC, grantgoodmanedX approved these changes
👍  looks good

2017-10-23 20:04 UTC, catong commented
Merging https://github.com/edx/edx-documentation/pull/1581

2017-10-23 21:25 UTC, merged