DOC-3776: SFD updates for mobile v2.11
openedx-unsupported/edx-documentation pull request #1608
Opened 2017-10-17 21:18 UTC by catong

## [DOC-3776](https://openedx.atlassian.net/browse/DOC-3776)

https://openedx.atlassian.net/wiki/spaces/LEARNER/pages/170262582/Mobile+Release+2.11

### Estimated Release

Oct 18-19

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): 
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2017-10-24 17:35 UTC, grantgoodmanedX approved these changes
LGTM 👍

2017-10-31 15:53 UTC, MirzaMubasharBaig requested changes

2017-10-31 15:53 UTC, MirzaMubasharBaig commented on en_us/shared/students/SFD_mobile.rst
> + **Discover** from the app's main menu. On Android devices, you do not need to have
We need to correct this '**On Android devices, you do not need to have an edX account or be logged in to browse courses. On iOS devices, you need to have an edX account and be logged in to browse courses.**'
Because, for both Android and iOS there is no need to have an edX account or be logged in to browse courses. However, When a user tap on 'Enroll Now' button on course detail page, app will take them to 'Register' screen.

2017-10-31 16:18 UTC, catong commented
@MirzaMubasharBaig Changes made. Please re-review. Thanks!

2017-10-31 21:05 UTC, marcotuts commented on en_us/shared/students/SFD_mobile.rst
> + To browse courses, select **Discover Courses** in the edX mobile app or
You can select the search icon on the courses page or the main discover menu in the app navigation.

2017-10-31 21:05 UTC, marcotuts approved these changes

2017-11-01 14:43 UTC, catong commented on en_us/shared/students/SFD_mobile.rst
> + To browse courses, select **Discover Courses** in the edX mobile app or
Added

2017-11-01 14:49 UTC, MirzaMubasharBaig approved these changes
LGTM

2017-11-01 15:17 UTC, catong commented
Merging https://github.com/edx/edx-documentation/pull/1608

2017-11-01 15:17 UTC, merged