WIP: Info about adding staff to Publisher docs
openedx-unsupported/edx-documentation pull request #1615
Opened 2017-10-31 17:50 UTC by srpearce

## [DOC-3810](https://openedx.atlassian.net/browse/DOC-3810)

Add information to Publisher docs per [Publisher documentation Google doc](https://docs.google.com/document/d/1uBssu7FQmgpEuFUj5V4qWyrz7PbHxK4nH_qGEWrui_4/edit?ts=59ef41a0).

### Date Needed (optional)

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): 
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2017-11-20 15:48 UTC, schenedx reviewed
I have a single comment for now. Would like to get more contextual information before I continue to review. Probably it's easier for me to talk to you when I review to do a good job of this and save me some time.

2017-11-20 15:48 UTC, schenedx commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/index.rst
> +* **If your goal is to enter course content in Studio**, you enter a small
Under what scenario would the goal of the course team be to enter course content in studio without first setting up course and run information in publisher properly? 
My point is, we want them to fill out all the required information in Publisher for a new course. For re-runs, they should only need to setup course_run information. I never encountered the scenario where the goal for the course tam is to enter course content in studio only.

2017-11-20 17:26 UTC, srpearce commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/index.rst
> +* **If your goal is to enter course content in Studio**, you enter a small
When Publisher was originally created, Julia (I can't find her on GitHub) said that about 50% of course teams wanted to start entering course content in Studio right away, and the other 50% wanted to get started creating an About page. I've asked Patrick and Julia for feedback and will let you know what I hear.

2017-11-21 19:51 UTC, schenedx reviewed
Overall, there isn't much difference from what we had before so I believe this is OK.
Added comments where the publisher is going through feature improvements

2017-11-21 19:51 UTC, schenedx commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_add_course_run_staff.rst
> +  Currently, a problem is preventing course teams from editing instructors
So, this is no longer true after Thanksgiving I believe.
What I know is true after Thanksgiving are:

1. Course team members can only edit the Instructor of their own organization
2. edX internal users should be able to edit any Instructors on publisher
3. If the instructors do not have any organizations but have the manually input organization override, any course team member can edit the instructor.

2017-11-21 19:51 UTC, schenedx commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_add_course_run_staff.rst
> +  Currently, a problem is preventing course teams from editing instructors
I just saw the message below. We should use the message below instead

2017-11-21 19:51 UTC, schenedx commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_add_course_run_staff.rst
> +     that you want, and then click the "edit" check box next to the instructor's
Why is that an `edit` check box? Isn't that a `pen` icon?

2017-11-21 19:51 UTC, schenedx commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_add_course_run_staff.rst
> +
Should we add instructions to help user understand how to lower image size below 256kb?
Like encourage the file format of JPG instead of PNG?

2017-11-21 21:18 UTC, jhendersonedx commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/index.rst
> +* **If your goal is to enter course content in Studio**, you enter a small
Hello. It's true that about 50% of course teams want to create their Studio instance and start working before they are ready to create an about page or announce their course. But I feel that we have now successfully trained them to request the Studio instance via Publisher. This is possible to do even before they have all of the About Page info. This is definitely a hurdle for teams and could be designed to be more intuitive. Happy to discuss more in person as needed.

2017-11-30 21:34 UTC, srpearce commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_add_course_run_staff.rst
> +     that you want, and then click the "edit" check box next to the instructor's
Maybe it's a pen icon. It's really small and hard to see, so I thought it was a check box. When I hover over it, the URL at the bottom of the page ends with /edit/#, so I went with "edit".

2017-11-30 22:01 UTC, srpearce commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_add_course_run_staff.rst
> +
We don't usually include non-edX-specific information, but I've added a note: "To keep your images small, consider using .jpg files instead of .png files."

2017-11-30 22:08 UTC, srpearce commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_add_course_run_staff.rst
> +.. The following feature will be implemented ~late November/early December 2017. Uncomment this section and delete step 3 above when the feature is live.
@schenedx Any ETA for this? I'm fine with publishing these docs now or waiting until this feature is live.

2017-11-30 22:11 UTC, srpearce commented
@schenedx Do we need to add any info from [LEARNER-3002](https://openedx.atlassian.net/browse/LEARNER-3002) to these docs? I don't think Publisher has an option to enter sponsors, does it?

2017-12-01 14:37 UTC, schenedx commented
@srpearce I don't believe so. Sponsor is not a field available in publisher for now.
Let's worry about that bridge when it's built.

2017-12-04 09:34 UTC, asadazam93 commented
@srpearce I don't think we need this note anymore. 
"Currently, a problem is preventing course teams from editing instructors directly. Instead of making changes to the instructor, write out the updates that you want to make in a comment on the course run page. The edX PC for the course run will update the instructor information."
And we should mention instead that the course team would be able to edit instructors that belong to the same organization as the course team.

2017-12-04 15:04 UTC, srpearce commented
@asadazam93 Are you looking at the latest commit? I had that note originally, but removed it. I also added that course team members can edit other instructors in the same organization.

2017-12-05 07:03 UTC, asadazam93 commented
@srpearce I was looking at this [link](http://draft-publisher-updates-nov-2017.readthedocs.io/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_add_course_run_staff.html). All good if you have corrected it.

2017-12-05 20:01 UTC, catong requested changes

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_course_creation.rst
> +   page for the course.
Does "creates a page for the course" mean that an About page gets created on the marketing site, or just a page within Publisher? Is there a way to clarify to avoid this confusion?

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_course_creation.rst
> +   page for the course.
On further reading I think this is a page within Publisher. Maybe something like "In this step, you provide basic information to create a course page in Publisher."

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_find_course.rst
> +  the course that you want, and then select **Search**.
Possible to add some link to another topic, (e.g. link the create course topic from "created") so that this topic doesn't live in isolation? Also, is it linked from anywhere?

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_create_course_run.rst
> +> Creating an edX Course > Self-paced: June 1, 2017``.
Possible to make the course name much more recognizable as such? Because we're in Help topics that are talking about creating a course, it's kind of difficult to immediately recognize "Creating an edX Course" as an example of a course name. Something like "Introduction to Computer Science", for example.
Also suggest bumping up the date of the example course run to make it less outdated seeming, e.g. "Dec 1, 2017"

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_edit_course.rst
> +the course. For example, the breadcrumbs may be ``Courses > Creating an edX
Possible to make the course name much more recognizable as such? Because we're in Help topics that are talking about creating a course, it's kind of difficult to immediately recognize "Creating an edX Course" as an example of a course name. Something like "Introduction to Computer Science", for example.

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_edit_course_run.rst
> +     For example, the name of a course run may be "Self-paced: June 01, 2017"
Suggest bumping up the date of the example course run to make it less outdated seeming, e.g. "Dec 1, 2017"

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_introduction.rst
Suggestion: many but not all of the procedural topics have as a first step "Go to https://prod-edx-discovery.edx.org/publisher and sign in." One just has "Open Publisher" without a URL.
For consistency and to avoid having to catch 8 separate instances of the URL if it ever changes, it might be good to have an "Accessing Publisher" section in this Intro topic that provides the URL once. Then, in the various procedures, step 1 can be "Sign in to Publisher" with a ref to the "Accessing" heading.

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_change_publisher_settings.rst
> +#. To open Publisher, go to https://prod-edx-discovery.edx.org/publisher.
This URL is repeated in the first step in many but not all of the procedural topics.
For consistency and to avoid having to catch 8 separate instances of the URL if it ever changes, reuse it from a single subtopic such as "Sign in to Publisher"  in this Intro page that provides the URL once. Then, in the various procedures, step 1 can be "Sign in to Publisher" with a link to the "Sign in" topic.

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_course_run_creation.rst
> +   the course run <Pub Finalize a Course Run>`. This is not common.
Not quite clear what is not common - reads as if "The course team then finalizes the course run" is not common. 
Rewrite? e.g. "It is unusual, but in some cases, the PC might change some course run information and return the course run to the course team, who then must finalize the course run." or just "In some cases, ... "

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_finalize_course_run.rst
> +    course run. This is not common.
Not quite clear what is not common - reads as if "The course team then finalizes the course run" is not common. 
Rewrite? e.g. "It is unusual, but in some cases, the PC might change some course run information and return the course run to the course team, who then must finalize the course run." or just "In some cases, ... "

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_send_course_run_review.rst
> +If the PC changes any of the course run information, the PC returns the course run to the course team. The course team then :ref:`finalizes the course run <Pub Finalize a Course Run>`. This is not co
Not quite clear what is not common - reads as if "The course team then finalizes the course run" is not common. 
Rewrite? e.g. "It is unusual, but in some cases, the PC might change some course run information and return the course run to the course team, who then must finalize the course run." or just "In some cases, ... "

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_send_course_run_review.rst
> +If the PC changes any of the course run information, the PC returns the course run to the course team. The course team then :ref:`finalizes the course run <Pub Finalize a Course Run>`. This is not co
Line wrap

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/planning_course_run_information/index.rst
>  Course run information, such as start and end dates, is specific to a course
Strike the first "Course run" and comma after information so that you are giving an example of course run information rather than saying "course run information is specific to a course run." ->
"Information such as start and end dates is specific to a course run. This section lists optional and required information for course runs..."

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_add_comment_to_course.rst
> +#. Go to https://prod-edx-discovery.edx.org/publisher and sign in.
Instead of repeating this URL in every procedure, reuse it from a single topic such as "Signing in to Publisher"

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_check_course_status.rst
> +#. Go to https://prod-edx-discovery.edx.org/publisher and sign in.
Instead of repeating this URL in every procedure, reuse it from a single topic such as "Signing in to Publisher"

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_create_course.rst
> +#. Go to https://prod-edx-discovery.edx.org/publisher and sign in.
Instead of repeating this URL in every procedure, reuse it from a single topic such as "Signing in to Publisher"

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_edit_course.rst
> +#. Go to https://prod-edx-discovery.edx.org/publisher and sign in.
Instead of repeating this URL in every procedure, reuse it from a single topic such as "Signing in to Publisher"

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_review_changes.rst
> +   * Open Publisher, go to the **Courses** page, and select the course that you
This topic doesn't provide the same sign in URL as other topics. Link to a single topic such as "Signing in to Publisher"

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_review_changes.rst
> +the edX marketing team, make final changes, and mark the course as reviewed.
Parsing might be easier if it's clear who is doing the marketing review. "When the edX marketing team finishes its review, you can view the changes and feedback, make final changes, and ..."

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_review_changes.rst
> +     #. To view the changes, select **View Changes**. A field opens to the left
Did you intend nested numbers starting at 1? Looks confusing.

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_review_changes.rst
> +documentation for specific insructions.
Typo: "instructions"

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_review_changes.rst
> +You can share the changes that the edX marketing team has suggested with others
This sentence is difficult to parse. Maybe "You can share the edX marketing team's suggestions with people who do not have access to Publisher..."

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_send_course_marketing.rst
> +#. Go to https://prod-edx-discovery.edx.org/publisher and sign in.
Instead of repeating this URL in every procedure, reuse it from a single topic such as "Signing in to Publisher"

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_send_course_marketing.rst
> +When you send a course to edX for SEO review, the edX marketing team reviews
This seems to be the only time you call it "SEO review"? Better to mention "SEO review" in the intro sentence, otherwise consider whether you can just omit it and go with generic "review" everywhere.

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_add_comment_to_course_run.rst
> +#. Go to https://prod-edx-discovery.edx.org/publisher and sign in.
Instead of repeating this URL in every procedure, reuse it from a single topic such as "Signing in to Publisher"

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_add_course_run_staff.rst
> +#. Go to https://prod-edx-discovery.edx.org/publisher and sign in.
Instead of repeating this URL in every procedure, reuse it from a single topic such as "Signing in to Publisher"

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_add_course_run_staff.rst
> +  instructor before you create a new instructor.
This note doesn't get to the bottom of why you are recommending they search for an instructor. Suggest something like: -> "Before you create a new instructor, we strongly recommend that you make sure the instructor you want to add is not already in Publisher. To do so, search for the instructor."

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_add_course_run_staff.rst
> +     or "June 1, 2017 - Self-paced".
Suggest using a later example date to make it less immediately outdated

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_add_course_run_staff.rst
> +#. Go to https://prod-edx-discovery.edx.org/publisher and sign in.
Instead of repeating this URL in every procedure, reuse it from a single topic such as "Signing in to Publisher"

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_add_course_run_staff.rst
> +     For example, the name of a course run may be "Self-paced: June 01, 2017"
Suggest using a later date for the example

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_add_course_run_staff.rst
> +   **Open**.
Add a result for the final step? Is there a confirmation message or anything that the user sees that confirms the upload was successfully added?

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_create_course_run.rst
> +#. Go to https://prod-edx-discovery.edx.org/publisher and sign in.
Instead of repeating this URL in every procedure, reuse it from a single topic such as "Signing in to Publisher"

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_finalize_course_run.rst
> +#. Go to https://prod-edx-discovery.edx.org/publisher and sign in.
Instead of repeating this URL in every procedure, reuse it from a single topic such as "Signing in to Publisher"

2017-12-05 20:01 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course_run/pub_send_course_run_review.rst
> +#. Go to https://prod-edx-discovery.edx.org/publisher and sign in.
Instead of repeating this URL in every procedure, reuse it from a single topic such as "Signing in to Publisher"

2017-12-05 20:01 UTC, catong commented on en_us/shared/set_up_course/planning_course_run_information/staffing.rst
> +  For courses on edx.org, you designate the staff that will be visible on the
"be visible on" reads a little oddly. How about "is listed on"?

2017-12-06 20:59 UTC, srpearce commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_change_publisher_settings.rst
> +#. To open Publisher, go to https://prod-edx-discovery.edx.org/publisher.
Great idea.

2017-12-06 21:21 UTC, srpearce commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_review_changes.rst
> +     #. To view the changes, select **View Changes**. A field opens to the left
It would better if our template did lettered steps inside numbered steps, but unfortunately it doesn't. I don't know of a way to change this—do you?

2017-12-06 22:12 UTC, catong commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_create_edit_course/pub_review_changes.rst
> +     #. To view the changes, select **View Changes**. A field opens to the left
I thought I had seen instances, but could be misremembered. What happens if you put the second level of #. at the same indent as the bullets?

2017-12-08 18:45 UTC, sstack22 commented on en_us/course_authors/source/set_up_course/pub_create_ann_course/pub_introduction.rst
I hope we can change the URL someday soon. :)

2017-12-08 18:59 UTC, merged