Clear proctored and timed exam attempts
openedx-unsupported/edx-documentation pull request #1624
Opened 2017-11-29 16:15 UTC by debchatigny

Added instructions on how to clear an exam attempt, in order to allow learners to retake a proctored or timed exam. Also, added three
glossary definitions.

2017-11-29 17:39 UTC, catong requested changes
Looks good! Suggestions inline. I did not repeat the equivalent comments for the timed exam topic from the proctored exam topic - please make the equivalent changes in both topics.

2017-11-29 17:39 UTC, catong commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +their exam attempt and allow them to retake the exam.
For clarity, "clear their exam attempt" -> "clear their existing exam attempt".

2017-11-29 17:39 UTC, catong commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +  When a learner retakes an exam, all previous answers are cleared and the
The fact that answers are cleared is due to the instructor clearing any existing exam attempt, rather than the learner retaking the exam? I think it would be better to reword:
"When you clear a learner's exam attempt, all of a learner's previous answers in the exam are cleared, and the learner starts the exam from the beginning."

2017-11-29 17:39 UTC, catong commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +#. From the Instructor Dashboard, select **Instructor**, then select **Special
The first step isn't quite right (selecting **Instructor** takes you to the instructor dashboard (note no caps)). You might want to follow the pattern in other procedures, e.g. Step 1 in http://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/course_features/cohorts/cohorted_courseware.html#associate-cohorts-with-content-groups

2017-11-29 17:39 UTC, catong commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +#. In the list of exam attempts, locate the specific exam name for the exam
Perhaps easier to parse: "...locate the name of the specific exam for which you are clearing the learner's exam attempt."?

2017-11-29 17:39 UTC, catong commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +   to confirm that you want to remove this student's exam attempt. Select **OK**.
"student" -> "learner's"

2017-11-29 17:39 UTC, catong commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +   to confirm that you want to remove this student's exam attempt. Select **OK**.
Make"Select OK" a separate step? Also, is it worth including a step result (is there a confirmation message, or some way that the instructor gets visual confirmation that the clearing succeeded)?

2017-11-29 17:39 UTC, catong commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +   .. Warning:: Clearing an exam attempt removes all learner inputs and is a
Perhaps instead of "inputs" - "answers in an exam"

2017-11-29 17:39 UTC, catong commented on en_us/shared/course_features/timed_exams.rst
> +their exam attempt and allow them to retake the exam.
Please make the same changes to this topic that you make to the " Allow Learners to Retake a Proctored Exam" topic.

2017-11-29 17:39 UTC, catong commented on en_us/shared/glossary/glossary.rst
> +  often part of verified certificate courses and for credit courses. For more
"...often required in courses that offer verified certificates or academic credit."

2017-11-29 17:39 UTC, catong commented on en_us/shared/glossary/glossary.rst
> +  Timed exams are sets of problems that you must complete in a limited amount
This glossary is in the CA guide, so "you" -> "learners" and this definition should be written for the course author perspective. Perhaps include the concept that course authors can specify the time limit, and that a countdown timer starts when learners start the exam.

2017-11-29 17:39 UTC, catong commented on en_us/shared/glossary/glossary.rst
> +  of time. The score you receive becomes part of your course progress record.
Strike "The score you receive becomes part of your course progress record."

2017-11-29 17:39 UTC, catong commented on en_us/shared/glossary/glossary.rst
> +  Timed exams are indicated on the **Course** page by a clock icon and the
If you rewrite the entry for course authors, up to you whether to keep this "indicated on the Course page by a clock icon". Probably strike in favor of mentioning more about the exam taking experience (countdown timer)?

2017-11-29 17:40 UTC, catong commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +case-by-case basis.
Our style minimizes hyphens

2017-11-30 17:37 UTC, debchatigny commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +   to confirm that you want to remove this student's exam attempt. Select **OK**.
Done.

2017-11-30 17:38 UTC, debchatigny commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +#. From the Instructor Dashboard, select **Instructor**, then select **Special
Done.

2017-11-30 17:39 UTC, debchatigny commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +#. In the list of exam attempts, locate the specific exam name for the exam
Done. I also added the column name (Exam Name).

2017-11-30 17:39 UTC, debchatigny commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +   .. Warning:: Clearing an exam attempt removes all learner inputs and is a
Done.

2017-11-30 17:40 UTC, debchatigny commented on en_us/shared/course_features/timed_exams.rst
> +their exam attempt and allow them to retake the exam.
Done.

2017-11-30 17:40 UTC, debchatigny commented on en_us/shared/glossary/glossary.rst
> +  often part of verified certificate courses and for credit courses. For more
+1 to this clarification. Done.

2017-11-30 17:40 UTC, debchatigny commented on en_us/shared/glossary/glossary.rst
> +  Timed exams are sets of problems that you must complete in a limited amount
Done.

2017-11-30 17:40 UTC, debchatigny commented on en_us/shared/glossary/glossary.rst
> +  of time. The score you receive becomes part of your course progress record.
Done.

2017-11-30 17:41 UTC, debchatigny commented on en_us/shared/glossary/glossary.rst
> +  Timed exams are indicated on the **Course** page by a clock icon and the
Done - I reworded a bit but did remove the bit about the clock icon and added language about the countdown timer.

2017-11-30 17:42 UTC, debchatigny commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +   to confirm that you want to remove this student's exam attempt. Select **OK**.
Done. The only result I see is that the exam attempt is removed from the list. There is no confirmatory or success message, sadly.

2017-11-30 17:42 UTC, debchatigny commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +  When a learner retakes an exam, all previous answers are cleared and the
Done.

2017-11-30 17:42 UTC, debchatigny commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +their exam attempt and allow them to retake the exam.
Done.

2017-11-30 17:43 UTC, debchatigny commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +case-by-case basis.
Done.

2017-11-30 17:48 UTC, debchatigny commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +#. From the Instructor Dashboard, select **Instructor**, then select **Special
For consistency, I followed the pattern of the preceding procedure in the **Timed Exams** topic.

2017-11-30 17:53 UTC, debchatigny commented
Thanks, @catong - I commented to your feedback inline. All changes are implemented. Would love a second sanity check, if you have time.

2017-11-30 18:43 UTC, catong commented on en_us/shared/glossary/glossary.rst
> +  If needed, you can also grant learners additional time to complete the exam.
Tiny nit: "also" seems unnecessary here.

2017-11-30 18:44 UTC, catong commented
@debchatigny Looks great. I just made one more optional suggestion in the glossary. Reminder to squash commits and run tests before merging.

2017-11-30 18:56 UTC, catong approved these changes

2017-11-30 20:09 UTC, debchatigny commented on en_us/shared/glossary/glossary.rst
> +  If needed, you can also grant learners additional time to complete the exam.
I'd debated its merits. I've removed it.

2017-12-11 10:55 UTC, Rabia23 requested changes

2017-12-11 10:55 UTC, Rabia23 commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +#. Select **Instructor**, and then select **Special Exam**.
Select **Instructor**, and then select **Special Exams**.

2017-12-11 10:55 UTC, Rabia23 commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +#. Search for the learner's username to locate their exam attempts.
Search for the learner's username or email address to locate their exam attempts.

2017-12-11 10:55 UTC, Rabia23 commented on en_us/shared/course_features/timed_exams.rst
> +#. Select **Instructor**, and then select **Special Exam**.
Select **Instructor**, and then select **Special Exams**.

2017-12-11 10:55 UTC, Rabia23 commented on en_us/shared/course_features/timed_exams.rst
> +#. Search for the learner's username to locate their exam attempts.
Search for the learner's username or email address to locate their exam attempts.

2017-12-11 10:55 UTC, Rabia23 commented on en_us/shared/glossary/glossary.rst
> +  credit. For more information, see :ref:`partnercoursestaff:Managing
I think we should mention this thing for proctored exams as well:
**If needed, you can grant learners additional time to complete the exam.**

2017-12-11 11:03 UTC, Rabia23 commented
@debchatigny just few nits otherwise it looks good to me 👍

2017-12-11 11:03 UTC, Rabia23 approved these changes

2017-12-13 16:39 UTC, debchatigny commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +#. Select **Instructor**, and then select **Special Exam**.
Done.

2017-12-13 16:39 UTC, debchatigny commented on en_us/shared/course_features/proctored_exams/proctored_managing.rst
> +#. Search for the learner's username to locate their exam attempts.
Done.

2017-12-13 16:39 UTC, debchatigny commented on en_us/shared/course_features/timed_exams.rst
> +#. Select **Instructor**, and then select **Special Exam**.
Done.

2017-12-13 16:39 UTC, debchatigny commented on en_us/shared/course_features/timed_exams.rst
> +#. Search for the learner's username to locate their exam attempts.
Done.

2017-12-13 16:50 UTC, debchatigny commented on en_us/shared/glossary/glossary.rst
> +  credit. For more information, see :ref:`partnercoursestaff:Managing
Done.

2017-12-13 17:25 UTC, Rabia23 commented
@debchatigny didn't you push the changes yet?

2017-12-13 17:25 UTC, Rabia23 approved these changes

2017-12-14 19:56 UTC, merged