Enabling self-pacing in Open edX ICR
openedx-unsupported/edx-documentation pull request #1627
Opened 2017-12-06 22:15 UTC by grantgoodmanedX

## [DOC-3778](https://openedx.atlassian.net/browse/DOC-3778)

I added a page about enabling self-paced courses in the Open edX Installing and Configuring guide. I verified the instructions in devstack.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Squash commits

2017-12-07 15:19 UTC, catong requested changes

2017-12-07 15:19 UTC, catong commented on en_us/install_operations/source/configuration/enable_pacing.rst
> +the Studio.
"in the Studio" -> "in Studio"

2017-12-07 15:19 UTC, catong commented on en_us/install_operations/source/configuration/enable_pacing.rst
> +*Building and Running an Open edX Course*.
We usually say "in the *Building and Running an Open edX Course* guide."

2017-12-07 15:19 UTC, catong commented on en_us/install_operations/source/configuration/enable_pacing.rst
> +Django admin panel, following these steps.
Reads a bit awkwardly. Maybe something like: "To enable self-paced courses, follow these steps to edit configurations in the (component name) Django admin tool."

- Which specific Django Admin tool are the settings changed in "LMS", etc? I don't believe we've referred to "Open edX Django Admin panel" in this guide, though I see it in the Open edX B&R. Also please check other topics for how we refer to Django admin. We aren't perfectly consistent yet, but I'd choose one of the existing ways we refer to it, e.g. "Django administration console",  "Django admin site"

2017-12-07 15:19 UTC, catong commented on en_us/install_operations/source/configuration/enable_pacing.rst
> +    #. Log in to your Open edX Django Admin panel.
See comment above re referring to Django Admin.

2017-12-07 20:32 UTC, grantgoodmanedX commented on en_us/install_operations/source/configuration/enable_pacing.rst
> +Django admin panel, following these steps.
I had copied from B&R: studio_scheduling.rst. We most often say Django administration console, so I've changed this to use that.

2017-12-07 20:54 UTC, grantgoodmanedX commented
@catong I've committed changes in response to your review, if you'd care to take another look.

2017-12-07 21:04 UTC, catong commented on en_us/install_operations/source/configuration/enable_pacing.rst
> +    #. Log in to your Open edX Django administration console.
@grantgoodmanedX I'm still not sure we have a single Django admin console that can be referred to as "your Open edX Django administration console." e.g. for edx.org, we have one for LMS, one for Discovery, one for eCommerce. I was trying to suggest something like "Log in to the LMS Django administration console for your Open edX site."

2017-12-07 21:12 UTC, catong commented on en_us/install_operations/source/configuration/enable_pacing.rst
> +Django admin panel, following these steps.
Yeah, I saw the reference in studio_scheduling.rst as well, and think that it is also not accurate; that fix would be for another story.

2017-12-08 15:28 UTC, catong approved these changes

2017-12-08 16:00 UTC, merged