Enterprise API Guide - DOC-3735
openedx-unsupported/edx-documentation pull request #1631
Opened 2017-12-18 20:59 UTC by grantgoodmanedX

## [ DOC-3735](https://openedx.atlassian.net/browse/ DOC-3735)

Add a description of your changes with links to any relevant material.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @douglashall 
- [ ] Subject matter expert: @brittneyexline 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] [HTML version](http://edx-enterprise-api.readthedocs.io/en/latest/index.html)

### Post-review

- [ ] Squash commits

2017-12-19 15:57 UTC, brittneyexline reviewed
I'm not sure where this should go, but one thing I think that would be potentially confusing to someone using this is how you would know what your enterprise uuid would be, but I'm not sure who they get that from and when.

2017-12-19 15:57 UTC, brittneyexline commented on en_us/enterprise_api/source/authentication.rst
> +  https://api.edx.org/{endpoint}/v1/access_token
i'm not exactly sure what {endpoint} should be, seems like it should be oauth2 instead, so that the full url they would be hitting is given?

2017-12-19 15:57 UTC, brittneyexline commented on en_us/enterprise_api/source/api_reference/reference.rst
> +The followig endpoints are available in the Enterprise API.
following

2017-12-19 15:57 UTC, brittneyexline commented on en_us/enterprise_api/source/api_reference/reference.rst
> +* **/enterprise_catalogs** - You can make GET calls to the
all paths for our endpoints start with /enterprise/api/v1, so i think it should be consistent with all of the endpoints listed here to always include or not include it and only specify in the detail sections.

2017-12-19 15:57 UTC, brittneyexline commented on en_us/enterprise_api/source/api_reference/reference.rst
> +* **/course_enrollments** - You can make POST calls to the
the full path of course_enrollments is /enterprise/api/v1/enterprise-customer/{enterprise_id}/course_enrollments/

2017-12-19 15:57 UTC, brittneyexline commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - Type of learning item. One of ``course``, ``courserun``, or ``program``.
programs also have an enrollment_url, similar to the course run.

2017-12-19 15:57 UTC, brittneyexline commented on en_us/enterprise_api/source/api_reference/reference.rst
> +   curl -X GET /oauth2/v1/access_token/\
this example request is a little confusing because the access token call is completely separate from subsequent calls. also, we should be directing people to the gateway (api.edx.org) instead of the lms directly (courses.edx.org). i imagine this should look more like:
```
curl -X GET \
  https://api.edx.org/enterprise/api/v1/entperise_catalogs/{catalog_id} \
  -H 'Authorization: JWT {access_token}'
```

2017-12-19 15:57 UTC, brittneyexline commented on en_us/enterprise_api/source/api_reference/reference.rst
> +   curl -X GET /oauth2/v1/access_token/\
it would be good for this to include an example payload, ie:
```
curl -X POST \
  https://api.edx.org/enterprise/api/v1/enterprise-customer/{enterprise_id}/course_enrollments/ \
  -H 'Authorization: JWT {access_token}' \
  -H 'Content-Type: application/json' \
  -d '[{
	"course_run_id":"course-v1:RITx+CYBER501x+2T2018_2",
	"course_mode":"audit",
	"user_email":"test@example.org",
	"email_students": true
}]'
```

2017-12-19 21:15 UTC, douglashall commented on en_us/enterprise_api/source/api_reference/reference.rst
> +   curl -X GET /oauth2/v1/access_token/\
The gateway URL paths are actually a little different from the edxapp URL paths.

`https://api.edx.org/enterprise/v1/enterprise-catalogs` for example. See the [gateway swagger yaml](https://github.com/edx/api-manager/blob/master/swagger/api.yaml#L46) for a reference.

2017-12-19 21:27 UTC, douglashall commented on en_us/enterprise_api/source/authentication.rst
> +  https://api.edx.org/{endpoint}/v1/access_token
Yes, replace `{endpoint}` with `oauth2`.

2017-12-21 21:11 UTC, douglashall requested changes

2017-12-21 21:11 UTC, douglashall commented on en_us/enterprise_api/source/api_reference/reference.rst
> +* **/enterprise_catalogs/{catalogID}/course_runs/{course_run_ID}** -
`* **/enterprise-catalogs/{catalogID}/course-runs/{course_run_ID}** -`

2017-12-21 21:11 UTC, douglashall commented on en_us/enterprise_api/source/api_reference/reference.rst
> +  ``/enterprise-catalogs/{catalog_id}/course_runs/{course_run_ID}`` endpoint
```/enterprise-catalogs/{catalog_id}/course-runs/{course_run_ID}```

2017-12-21 21:11 UTC, douglashall commented on en_us/enterprise_api/source/api_reference/reference.rst
> +enterprise_catalogs/{catalog_id} Endpoint
`enterprise-catalogs`

2017-12-21 21:11 UTC, douglashall commented on en_us/enterprise_api/source/api_reference/reference.rst
> +GET calls to the ``enterprise_catalogs/{catalog_id}`` endpoint return a list
`enterprise-catalogs`

2017-12-21 21:11 UTC, douglashall commented on en_us/enterprise_api/source/api_reference/reference.rst
> +  ``/enterprise/api/v1/enterprise_catalogs/{catalog_id}`` endpoint, the
`/enterprise/v1/enterprise-catalogs/{catalog_id}`

2017-12-21 21:11 UTC, douglashall commented on en_us/enterprise_api/source/api_reference/reference.rst
> +The ``POST /enterprise/api/v1/enterprise-customer/{enterprise_uuid}/course_enrollments``
`POST /enterprise/v1/enterprise-customer/{enterprise_uuid}/course-enrollments`

2017-12-21 21:11 UTC, douglashall commented on en_us/enterprise_api/source/intro_edx_apis.rst
> +:ref:`course_enrollments Endpoint`.
`course-enrollments`

2017-12-21 21:11 UTC, douglashall commented on en_us/enterprise_api/source/api_reference/reference.rst
> +  course run. For details, see :ref:`course_enrollments Endpoint`.
`course-enrollments`

2018-01-18 22:26 UTC, brittneyexline approved these changes
pending those two small changes.

2018-01-18 22:26 UTC, brittneyexline commented on en_us/enterprise_api/source/api_reference/reference.rst
> +* **/enterprise-catalogs/{catalogID}/course_runs/{course_run_ID}** -
course-runs

2018-01-18 22:26 UTC, brittneyexline commented on en_us/enterprise_api/source/api_reference/reference.rst
> +  ``/enterprise-catalogs/{catalog_id}/course_runs/{course_run_ID}`` endpoint
course-runs

2018-01-23 22:27 UTC, catong requested changes
This looks great! Comments inline.

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/intro_edx_apis.rst
> +Welcome to the Enterprise API user guide. This guide will help you get set
Suggest making it clear who the intended audience for this guide is vs generic "user".  Something like: "This guide is intended for..." or "The intended audience for this guide is.."

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/intro_edx_apis.rst
> +The enterprise uses the edX Enterprise API to retrieve its custom course
Perhaps a bit more context for "The enterprise" since this is the introduction to the entire guide? "The enterprise on which you are offering courses..." or "The enterprise for which you are..." (for example), or something else that makes sense.

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +.. _enterprise_catalogs_catalogID Endpoint:
Consider chunking so that the content for each endpoint is a separate page?

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +
Consider using a local TOC in each endpoint intro to make navigation and visual understanding of content in this section easier. In a guide like this it's really difficult to understand the content hierarchy, especially as we've lost indents in the TOC pane.

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +example API requests shown in this reference use the ``curl`` command-line
Seems as if the 2 sentences about examples using curl could be presented together rather than one before and one after the "You can use any technology..." sentence?
Perhaps "You can use any technology..." first, followed by the explanation that the example requests use curl.

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +Each top-level JSON object in the ``results`` array represents a content item
Should this paragraph go into the cell describing ``` ``results`` ```?

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - Type of learning item. One of ``course``, ``courserun``, or ``program``.
If this section specifically describes the fields for the "course" content item, then the content_type is this case is "course", right, not possibly one of the other types? 
The other field descriptions in this table are specifically for "course" so I think "content_type" should be as well.

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - sring
typo: "sring"

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - Type of learning item. One of ``course``, ``courserun``, or ``program``.
Same comment as above - should specifically be "courserun" in this case, right?

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - The last time at which learners can enroll.
"time" - > "date and time"
"at which" -> "by which"
A bit nitpicky, but perhaps "by which learners can enroll in this course run"?

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - The first time at which learners can enroll.
"time" -> "date and time"
"enroll" -> " enroll in this course run"?

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - The long description of the course and its content.
These and the following field descriptions in this table should all say "course run" rather than "course", shouldn't they? I did not add a comment for every occurrence.

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - Whether learners can enroll in the course.
"course" -> "course run"

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - The URL for the About page image for the course.
"course" -> "course run"

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - Type of learning item. One of ``course``, ``courserun``, or ``program``.
If this section specifically describes the fields for the "program" content item, then the content_type is this case is "program", right, not possibly one of the other types?
The other field descriptions in this table are specifically for "program" so I think "content_type" should be as well.

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - The program type. One of ``Professional Certificate``, ``XSeries``,
Do we have a program type called "Professional Program"?

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - int
Elsewhere you have "integer" in full

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - sring
typo: "sring"

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - int
Elsewhere you have "integer" in full

2018-01-23 22:27 UTC, catong commented on en_us/enterprise_api/source/authentication.rst
> +client secret, grant type, and token type, as shown in the following example,
grant type and token type were not previously mentioned. Will users know what these are/where to obtain them?

2018-01-24 20:31 UTC, grantgoodmanedX commented on en_us/enterprise_api/source/api_reference/reference.rst
> +example API requests shown in this reference use the ``curl`` command-line
fixed

2018-01-24 20:31 UTC, grantgoodmanedX commented on en_us/enterprise_api/source/api_reference/reference.rst
> +Each top-level JSON object in the ``results`` array represents a content item
I kept it out of the cell to serve as a transition to the fields table that follows.

2018-01-24 20:31 UTC, grantgoodmanedX commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - Type of learning item. One of ``course``, ``courserun``, or ``program``.
fixed

2018-01-24 20:31 UTC, grantgoodmanedX commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - Type of learning item. One of ``course``, ``courserun``, or ``program``.
fixed

2018-01-24 20:31 UTC, grantgoodmanedX commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - The last time at which learners can enroll.
fixed

2018-01-24 20:31 UTC, grantgoodmanedX commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - The first time at which learners can enroll.
fixed

2018-01-24 20:31 UTC, grantgoodmanedX commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - sring
fixed

2018-01-24 20:31 UTC, grantgoodmanedX commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - The long description of the course and its content.
Do course runs have separate descriptions from the course they belong to? I don't think they do.

2018-01-24 20:31 UTC, grantgoodmanedX commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - Whether learners can enroll in the course.
Fixed.

2018-01-24 20:32 UTC, grantgoodmanedX commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - The URL for the About page image for the course.
fixed

2018-01-24 20:32 UTC, grantgoodmanedX commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - int
Fixed

2018-01-24 20:32 UTC, grantgoodmanedX commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - Type of learning item. One of ``course``, ``courserun``, or ``program``.
Fixed

2018-01-24 20:32 UTC, grantgoodmanedX commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - sring
Fixed

2018-01-24 20:32 UTC, grantgoodmanedX commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - The program type. One of ``Professional Certificate``, ``XSeries``,
In this context, I think they're the same thing

2018-01-24 20:32 UTC, grantgoodmanedX commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - int
fixed

2018-01-24 20:36 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - The program type. One of ``Professional Certificate``, ``XSeries``,
If we are listing valid values then I would remove whichever is not a real option.

2018-01-24 20:41 UTC, catong commented on en_us/enterprise_api/source/api_reference/reference.rst
> +     - The long description of the course and its content.
My point is that this table is meant to describe fields for the "course run" object, so it's confusing/inappropriate to have field descriptions that refer to "course". That is a separate issue from the fact that in our (current) model we present course runs as if they are courses. Course runs can sometimes have different information from the course, such as different instructors for different course runs.

2018-01-25 16:07 UTC, grantgoodmanedX commented on en_us/enterprise_api/source/authentication.rst
> +client secret, grant type, and token type, as shown in the following example,
They are always the same value, so I've indicated that in the text.

2018-02-14 16:02 UTC, merged