Add math problem a11y information to CA and learner guides
openedx-unsupported/edx-documentation pull request #1634
Opened 2017-12-20 22:29 UTC by srpearce

## [DOC-3854](https://openedx.atlassian.net/browse/DOC-3854)

Add information about a workaround for an HTML/screen reader limitation so that screen reader users can access math problems.

### Date Needed (optional)

ASAP

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @cptvitamin 
- [ ] Doc team review (copy edit?): @edx/doc
- [ ] Partner support: @jaakana
- [ ] Learner support: @derek hixon

FYI: Tag anyone else who might be interested in this PR here.

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2017-12-21 17:37 UTC, debchatigny commented on en_us/shared/students/completing_assignments/SFD_mathformatting.rst
> +Viewing Mathematical Problems
As screen reader users are often blind or partially sighted, I'd suggest changing 'Viewing..' to 'Reading..' (or Completing). 

As the paragraph is also specifically for screen readers, I'd clarify the heading as follows:
'Reading Mathematical Problems with Screen Readers'

2017-12-21 17:39 UTC, debchatigny commented on en_us/shared/students/completing_assignments/SFD_mathformatting.rst
> +However, because of a limitation with HTML and screen reader technology, screen
I'd suggest including a link to the specific HTML limitation (does WebAIM or other a11y site contain specific details?):
https://webaim.org/techniques/screenreader/

2017-12-21 17:43 UTC, debchatigny commented on en_us/shared/students/completing_assignments/SFD_mathformatting.rst
> +EdX apologizes for any inconvenience this may cause.
I'd remove the apology and include: 

'Please see your screen reader's instructions for information on how to ensure all page content is read to you.'

2017-12-21 17:46 UTC, debchatigny commented on en_us/shared/accessibility/best_practices_course_content_dev.rst
> +  learners. However, because of limitations with HTML and screen reader
I'd suggest including a link to the specific HTML limitation (does WebAIM or other a11y site contain specific details?):
https://webaim.org/techniques/screenreader/

2017-12-21 17:53 UTC, debchatigny commented
Looks good, @srpearce - see my inline comments for a few suggested edits. Thanks!

2017-12-22 16:27 UTC, cptvitamin commented on en_us/shared/students/completing_assignments/SFD_mathformatting.rst
> +Viewing Mathematical Problems
I like "Completing" or "Reading" since it is technically more accurate.  I do want to avoid choosing specific language for blind users as a general rule. It's widely accepted that people with disabilities do not want anyone to alter the language they use or avoid using common phrases or idioms just because they might not make sense in their specific context.  e.g. a blind person would not take offense to someone saying "see you later"

2017-12-22 16:47 UTC, cptvitamin commented on en_us/shared/students/completing_assignments/SFD_mathformatting.rst
> +However, because of a limitation with HTML and screen reader technology, screen
Not a bad idea, but this is an edge case and it may only cause more confusion.  Your average screen reader user is not aware, nor should they be, of how all this technology works together.  They just want it to work.   The webaim link suggested, while a very comprehensive one, does not mention Math, or Accessibility APIs, and barely covers the nuances of HTML and the role it plays in exposing info to screen readers.  When I drafted this, I actually looked for references and all I found was technical docs and specifications and what I ended up with started turning into a long lesson on how all this stuff works together.  I'm OK, not providing any references here.

2017-12-22 16:48 UTC, cptvitamin commented on en_us/shared/accessibility/best_practices_course_content_dev.rst
> +  learners. However, because of limitations with HTML and screen reader
see above

2017-12-22 16:56 UTC, cptvitamin commented on en_us/shared/students/completing_assignments/SFD_mathformatting.rst
> +the screen reader's Interactive mode to Reading mode.
@srpearce I would like to revise my original draft here to be a little more forward thinking.  The reason this limitation exists is partly based on lack of support in the browsers and screen readers, but that may not be true as both continue to evolve.  Can we add a sentence here that says "If your browser and screen reader both support MathML, you can specify MathML as your preferred Math Renderer in MathJax."

2017-12-22 16:57 UTC, cptvitamin requested changes
@srpearce i just want to add one clarifying/forward thinking sentence. thanks!

2017-12-22 18:02 UTC, debchatigny commented on en_us/shared/students/completing_assignments/SFD_mathformatting.rst
> +However, because of a limitation with HTML and screen reader technology, screen
I agree, @cptvitamin; I wondered if you knew of a better/more explicit link, but if there's nothing succinct and helpful, no real value add in sending them offsite.

2017-12-22 22:32 UTC, cptvitamin commented
:+1:

2017-12-22 22:33 UTC, cptvitamin approved these changes

2017-12-27 16:20 UTC, grantgoodmanedX commented
@srpearce I merged this because I wanted to make @cptvitamin happy.

2017-12-27 16:20 UTC, merged

2018-01-03 14:43 UTC, srpearce commented
@grantgoodmanedX We all want to make @cptvitamin happy. Thanks for doing this!