Add info about discussion notifications to ICR guide
openedx-unsupported/edx-documentation pull request #1637
Opened 2018-01-03 17:22 UTC by srpearce

## [DOC-3859](https://openedx.atlassian.net/browse/DOC-3859)

Add info about how to enable discussion notifications to _Installing... the Open edX Platform_

### Date Needed (optional)

ASAP

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @iloveagent57 
- [ ] Doc team review: @edx/doc 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2018-01-03 17:27 UTC, catong requested changes

2018-01-03 17:27 UTC, catong commented on en_us/install_operations/source/configuration/enable_discussion_notifications.rst
> +For more information, see :ref:`opencoursestaff:ADD_REFERENCE` and
These references need to be added

2018-01-03 17:27 UTC, catong commented on en_us/install_operations/source/configuration/enable_discussion_notifications.rst
> +Enable Discussion Notifications
Top level and next level heading are identical. Our style is to use gerunds for the conceptual topic, so I'd recommend changing the top level heading to "Enabling" - will also make it consistent with other ICR headings

2018-01-03 17:27 UTC, iloveagent57 approved these changes

2018-01-08 02:21 UTC, srpearce commented on en_us/install_operations/source/configuration/enable_discussion_notifications.rst
> +.. _Enabling Discussion Notifications:
@iloveagent57 – would you remind reviewing this topic again? I forgot the info about ACE and a third party email client in the earlier version.

2018-01-08 02:22 UTC, srpearce commented
@catong Would you mind looking over this again? I think the install guide topic might be a bit awkward so would love a second opinion.

2018-01-08 02:24 UTC, srpearce commented on en_us/install_operations/source/configuration/enable_discussion_notifications.rst
> +message, see :ref:`opencoursestaff:Automatic Email` and
@catong This link seems to be broken, but I can't figure out why. Any ideas?

2018-01-08 15:01 UTC, catong commented on en_us/install_operations/source/configuration/enable_discussion_notifications.rst
> +message, see :ref:`opencoursestaff:Automatic Email` and
@srpearce If the "Automatic Email" anchor in the other file is new to this PR, the ref won't be found until you publish that guide and the target exists to be found in RTD. Could that be it?

2018-01-08 16:00 UTC, catong requested changes
@srpearce A couple of additional suggestions, as requested, then 👍

2018-01-08 16:00 UTC, catong commented on en_us/course_authors/source/manage_live_course/automatic_email.rst
> +   - Notifications that a user has responded to a post on a discussion.
Might be helpful to link "discussion" to the section on discussions.

2018-01-08 16:00 UTC, catong commented on en_us/install_operations/source/configuration/enable_discussion_notifications.rst
> +Obtain Discussion Notification Requirements
A heading such as "Requirements for Enabling Discussion Notifications" would make it more clear what's being communicated here. I had to read several times before I really figured out what the topic was for. "Obtain..." makes more sense for a procedure; this isn't a procedure.

2018-01-11 18:57 UTC, iloveagent57 approved these changes

2018-01-15 21:59 UTC, merged