WIP: Add documentation for ecommerce i18n
openedx-unsupported/edx-documentation pull request #1641
Opened 2018-01-12 15:21 UTC by BenjiLee

## [DOC-XXXX](https://openedx.atlassian.net/browse/DOC-XXXX)

Add a description of your changes with links to any relevant material.

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2018-01-12 17:00 UTC, catong commented
@BenjiLee I made a draft RTD project based on your branch - you can see how it looks at: http://draft-icr-ecomm-i8n.readthedocs.io/en/latest/ecommerce/internationalization.html

2018-01-12 17:14 UTC, amangano-edx commented on en_us/install_operations/source/ecommerce/internationalization.rst
> +the settings file, for example in ``ecommerce/settings/base.py``
It might be helpful to link to the django docs here.

https://docs.djangoproject.com/en/2.0/ref/settings/#languages

2018-01-12 17:40 UTC, catong requested changes
@BenjiLee Looks good! Suggested edits in comments.

2018-01-12 17:40 UTC, catong commented on en_us/install_operations/source/ecommerce/internationalization.rst
> +#. LANGUAGE_COOKIE_NAME is used to negotiate language. A user's language is set in their account settings in edx-platform which sets the language cookie. The language cookie name should be the same c
Is it possible to get more specific about where the learner account settings/language cookie name are found in the edx-platform repo?

3rd sentence "The language cookie name": it would be more precise to say something like "The language cookie name you set for the ecommerce language should be the sae as the language cookie name set in the edx-platform repo." Is that accurate?

2018-01-12 17:40 UTC, catong commented on en_us/install_operations/source/ecommerce/internationalization.rst
> +#. On the **Add switch** page, locate the **Active** checkbox and check it.
"On the **Add switch** page, select the **Active** checkbox."

2018-01-12 17:40 UTC, catong commented on en_us/install_operations/source/ecommerce/internationalization.rst
> +#. On the **Add switch** page, locate the **Name** field, and then add ``create_and_set_webprofile``
missing period at end of this sentence.

2018-01-12 17:40 UTC, catong commented on en_us/install_operations/source/ecommerce/internationalization.rst
> +Ecommerce Language Negotiation
Above the heading, add an anchor, formatted as:
```.. _Ecomm Language Negotiation:```

so that you can link to this section from elsewhere

2018-01-12 17:40 UTC, catong commented on en_us/install_operations/source/ecommerce/internationalization.rst
> +A language code for ecommerce will be taken from a cookie as described in Ecommerce Language Negotiation. When the
Link to the earlier section using the anchor you added above line 16.
"...as described in ``` `:ref:`Ecomm Language Negotiation` ```.

2018-01-12 17:40 UTC, catong commented on en_us/install_operations/source/ecommerce/internationalization.rst
> +language code is fetched from the cookie, only the base language is used. For example, ``es-419`` resolve to ``es``.
missing "s" in "resolves"

2018-01-12 19:21 UTC, BenjiLee commented
Ready for another pass

2018-01-16 14:39 UTC, mikix approved these changes
Looks fine to me.

2018-01-16 21:20 UTC, catong approved these changes
@BenjiLee Final minor edits, then 👍 . Thank you!

2018-01-16 21:20 UTC, catong commented on en_us/install_operations/source/ecommerce/internationalization.rst
> +More details can be found in the `Django documentation for Language`_.
Should the link text be "...for Languages" rather than "...for Language"? That's the heading you get to when you follow the link.

2018-01-16 21:20 UTC, catong commented on en_us/install_operations/source/ecommerce/internationalization.rst
> +Ecommerce Language Negotiation
Sorry, I did not catch this until I viewed the topic in context with the existing doc. We use "E-Commerce" throughout the guide so let's stay consistent.

2018-01-16 21:20 UTC, catong commented on en_us/install_operations/source/ecommerce/internationalization.rst
> +Language negotiation for ecommerce is handled by `Django's Locale Middleware`_. Django's Language Negotiation rules, in
"ecommerce" -> "E-Commerce"

2018-01-16 21:20 UTC, catong commented on en_us/install_operations/source/ecommerce/internationalization.rst
> +#. LANGUAGE_COOKIE_NAME is used to negotiate language. A user's language is set in their account settings in edx-platform which sets the language cookie. The language cookie name that is set for the
"Ecommerce -> "E-Commerce"

2018-01-16 21:20 UTC, catong commented on en_us/install_operations/source/ecommerce/internationalization.rst
> +#. Language prefix is not enabled by default for the ecommerce application.
"ecommerce" -> "E-Commerce"

2018-01-16 21:20 UTC, catong commented on en_us/install_operations/source/ecommerce/internationalization.rst
> +#. LANGUAGE_CODE is used as the last resort. This can be set in 'ecommerce/settings/base.py'
Use double backquotes instead of single straight quotes: ``` ``ecommerce/settings/base.py`` ```

2018-01-17 13:03 UTC, merged