DOC-3818: ICR - Configuration How-To for non-English certificates
openedx-unsupported/edx-documentation pull request #1648
Opened 2018-01-25 22:39 UTC by catong

## [DOC-3818](https://openedx.atlassian.net/browse/DOC-3818)

Add a description of your changes with links to any relevant material.

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2018-01-30 20:16 UTC, McKenzieW requested changes

2018-01-30 20:16 UTC, McKenzieW commented on en_us/install_operations/source/configuration/enable_certificates.rst
> +Enable Certificates in Additional Languages
Enabling Hours of Effort on certificates can happen independently of enabling additional languages, so perhaps a more apt title for this section would more broadly reference optional certificate features rather than additional just languages specifically

2018-01-30 20:16 UTC, McKenzieW commented on en_us/install_operations/source/configuration/enable_certificates.rst
> +      * - ``Mode``
For the course mode, it might be helpful for users to know that this field is actually optional. If no mode is selected the template will be used for all modes of the course runs fitting otherwise identified parameters.

2018-01-30 20:16 UTC, McKenzieW commented on en_us/install_operations/source/configuration/enable_certificates.rst
> +   .. note:: If more than one certificate template would apply to a course
Nit: "template _that_ would"

2018-01-30 20:16 UTC, McKenzieW commented on en_us/install_operations/source/configuration/enable_certificates.rst
> +   instance of Open edX. To do this, go to ``https://<host name of your Open
so for edx specifically this url actually includes some sort of variation of discovery.edx.org, I'm not entirely sure what the url would look like for OpenEdx installations, but I'd imagine that it would include discovery in it for them as well.

2018-01-30 20:16 UTC, McKenzieW commented on en_us/install_operations/source/configuration/enable_certificates.rst
> +   For example, this might be ``https://YourOrganization.com/admin``.
this url should probably be `courses.YourOrganization.com/admin` like you have above when referencing the LMS Django Admin page

2018-01-30 21:32 UTC, catong commented on en_us/install_operations/source/configuration/enable_certificates.rst
> +Enable Certificates in Additional Languages
The two sections are at the same level; the "hours of effort" section is not a subsection of the "additional languages" section. See the draft output: 
http://draft-ic-guide-certs-config.readthedocs.io/en/latest/configuration/enable_certificates.html#enabling-course-certificates

2018-01-30 21:53 UTC, catong commented on en_us/install_operations/source/configuration/enable_certificates.rst
> +   .. note:: If more than one certificate template would apply to a course
I think the existing wording is correct ("If more than one template would apply to a course run, the most specific template is used...") but I've reworded a bit for clarity.

2018-01-30 21:54 UTC, catong commented on en_us/install_operations/source/configuration/enable_certificates.rst
> +   instance of Open edX. To do this, go to ``https://<host name of your Open
Updated

2018-01-30 21:56 UTC, catong commented on en_us/install_operations/source/configuration/enable_certificates.rst
> +   For example, this might be ``https://YourOrganization.com/admin``.
Updated

2018-01-30 22:01 UTC, catong commented
@McKenzieW Ready for your re-review. The draft HTML has also been rebuilt for easier reviewing. Thanks!

2018-01-31 00:04 UTC, McKenzieW commented on en_us/install_operations/source/configuration/enable_certificates.rst
> +Enable Certificates in Additional Languages
oh I'm sorry, I was going to quickly and missed the detail

2018-01-31 00:06 UTC, McKenzieW commented on en_us/install_operations/source/configuration/enable_certificates.rst
> +   .. note:: If more than one certificate template would apply to a course
You're right. Another instance of me reading too quickly over it.

2018-01-31 00:14 UTC, McKenzieW approved these changes
Looks good! 👍 
Sorry for my misreadings in review round 1

2018-01-31 15:11 UTC, grantgoodmanedX commented on en_us/install_operations/source/configuration/enable_certificates.rst
> +#. Under **Course Metadata** > **Course Runs** locate the course run, and make
You could add a comma after **Course Runs**.

2018-01-31 15:12 UTC, grantgoodmanedX approved these changes
👍  with a possible addition of a comma.

2018-01-31 16:01 UTC, catong commented
Merging https://github.com/edx/edx-documentation/pull/1648

2018-01-31 16:01 UTC, merged