Updating discussion block OLX
openedx-unsupported/edx-documentation pull request #1674
Opened 2018-03-16 01:41 UTC by jolyonb

## [DOC-XXXX](https://openedx.atlassian.net/browse/DOC-XXXX)

This overhauls the discussion block OLX documentation, which is out of date and missing information. I've read through the [corresponding source code](https://github.com/edx/edx-platform/blob/master/openedx/core/lib/xblock_builtin/xblock_discussion/xblock_discussion.py) to figure out what's actually going on, and updated the documentation appropriately. I'm pretty sure I've got it right, but somebody who understands the source code better than me may like to confirm.

I apologize that I don't know how to fill in most of the below information.

### Date Needed

This documents features that were implemented years ago.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [x] Subject matter expert: jolyonb
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2018-03-16 01:42 UTC, edx-webhook commented
Thanks for the pull request, @jolyonb! I've created [OSPR-2306](https://openedx.atlassian.net/browse/OSPR-2306) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-documentation/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2018-03-21 15:23 UTC, jolyonb commented
Bump?

2018-03-21 18:10 UTC, nedbat commented
@dianakhuang Can you be the discussion block expert for this?

2018-03-21 18:13 UTC, nedbat commented
/cc @edx/doc

2018-04-05 19:07 UTC, grantgoodmanedX requested changes
Thanks for contributing this. I have a few small edits.

2018-04-05 19:07 UTC, grantgoodmanedX commented on en_us/olx/source/components/discussion-components.rst
> +The first is to include a discussion tag inside a vertical, as demonstrated in
I think we should do more to point users toward the first method. "The first, preferred, way is to include..."

2018-04-05 19:07 UTC, grantgoodmanedX commented on en_us/olx/source/components/discussion-components.rst
> +The second way is to create an XML file in the ``discussion`` directory for each
"The second way, which is deprecated, is to create..."

2018-04-05 19:07 UTC, grantgoodmanedX commented on en_us/olx/source/components/discussion-components.rst
> +       **Discussion** tab of the course. Eg: ``Problem 2``
Replace "Eg." with "For example:"

2018-04-05 19:07 UTC, grantgoodmanedX commented on en_us/olx/source/components/discussion-components.rst
> +       **Discussion** tab of the course. Eg: ``Problem Set 1``
Replace "Eg." with "For example:"

2018-04-05 19:07 UTC, grantgoodmanedX commented on en_us/olx/source/components/discussion-components.rst
> +     - Now called ``discussion_id``.
"Use ``discussion_id` instead.

2018-04-05 19:07 UTC, grantgoodmanedX commented on en_us/olx/source/components/discussion-components.rst
> +     - Now called ``discussion_target``.
"Use ``discussion_target`` instead."

2018-04-05 21:14 UTC, dianakhuang approved these changes
Approved from a tech perspective. 

I'm not sure about recommending combining the vertical and discussion blocks into the same file, especially since it will probably export into a separate file in a separate directory, but I don't have strong opinions on it.

Unfortunately, I think this documentation was missed when we replaced the original `discussion` XModule with a new `discussion` XBlock.

2018-04-08 23:16 UTC, jolyonb commented
Updated with requested changes. I tested the XML export; discussion blocks are exported with the method indicated as preferred (not in a separate directory). One curious note is that a `url_name` parameter is also exported with the discussion block; this generates warnings in the logs on course import, as the discussion xblock does not have a url_name property.

2018-04-09 19:47 UTC, grantgoodmanedX approved these changes
👍 Looks good.

2018-04-10 20:17 UTC, merged