Giving reason and role when enrolling manually on Instructor Dashboard
openedx-unsupported/edx-documentation pull request #1682
Opened 2018-04-02 18:58 UTC by grantgoodmanedX

## [DOC-3903](https://openedx.atlassian.net/browse/DOC-3903)

In the sections about enrolling and unenrolling learners from the Instructor Dashboard, I added notes about the new Role and Reason fields.

### Date Needed

The feature has already been released, so it would be good to get the docs published promptly.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @bill-filler 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Squash commits

2018-04-02 20:08 UTC, bill-filler approved these changes

2018-04-02 22:10 UTC, srpearce requested changes

2018-04-02 22:10 UTC, srpearce commented on en_us/shared/manage_live_course/course_enrollment.rst
> +#. Select the role of the learner. Select **Partner**, for instance, if the
Even though this UI label isn't very good, I think we need to indicate where the user performs this action. I also think we can make the language stronger, and move the info out of paragraph form into bullet form to make it more visible. And it looks like you can't add partner users and learner users at the same time. So I'd change this step to:

For **Role of the users being enrolled**, select the role of the learner.
* If the learner is a member of the course staff, select **Partner**.
* If the learner is not a member of the course staff, select **Learner**.
Note 
All of the users that you enroll at one time must have the same role. If you have some users who are partners and others who are learners, you must complete two batch enrollments.

I'd also suggest reviewing this UI text and creating a platform PR to update it, since it didn't have a doc review before. That would mean we'd have to update these docs later, but the changes would be small. For example, I'd change "Role of the users being enrolled" to "Role for these users" or similar.

2018-04-02 22:10 UTC, srpearce commented on en_us/shared/manage_live_course/course_enrollment.rst
> +#. Enter the reason that you are enrolling the learners manually.
Again, even though this label is terrible (which could very well be an a11y issue), we should tell the user where to perform the action:

In the **Enter the reason why the students are to be manually enrolled or unenrolled** field, enter a specific, detailed reason why you want to enroll these learners.

For the current UI text (Enter the reason why the students are to be manually enrolled or unenrolled. This cannot be left blank and will be recorded and presented in Enrollment Reports. Therefore, please give enough detail to account for this action.), I have some suggestions.
* Name the field "Reason for Enrollment or Unenrollment". 
* Use an edited version of the current three sentences as help text.
* Remove the "Reason" placeholder from the field. (Per Darren in UX, placeholder text creates a11y and other problems.)

2018-04-02 22:10 UTC, srpearce commented on en_us/shared/manage_live_course/course_enrollment.rst
> +#. Enter the reason that you are unenrolling the learners.
In the **Enter the reason why the students are to be manually enrolled or unenrolled** field, enter a specific, detailed reason why you want to unenroll these learners.

2018-04-03 15:53 UTC, grantgoodmanedX commented
@srpearce I've updated this with your suggested changes.

2018-04-03 18:04 UTC, srpearce approved these changes
Approved with one small change.

2018-04-03 18:04 UTC, srpearce commented on en_us/shared/manage_live_course/course_enrollment.rst
> +   * If the learner is not a member of the course staff, select Learner.
UI terms should be bold in the above.

2018-04-03 19:08 UTC, merged