TE-2567 Better requirements file management
openedx-unsupported/edx-documentation pull request #1693
Opened 2018-05-07 20:57 UTC by jmbowman

## [TE-2567](https://openedx.atlassian.net/browse/TE-2567)

This updates the management of Python package dependencies to comply with OEP-18, which should help make documentation builds more reliable over time and make it easier to upgrade dependencies like Sphinx when we choose.  There were originally two requirements files in the repository; one has been updated to just reference the new file in the standard location, and the other seems to be unused even in RTD project settings, so it's being removed.

I also updated one outdated link I found - `sphinx-napoleon` was merged into `sphinx` a while back.

### Date Needed

We would like this to be merged before the Hawthorn master branch is created, so Hawthorn doc builds are less likely to randomly fail over time.

### Reviewers

The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @nedbat
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc 

### Testing

- [x] Ran ./run_tests.sh without warnings or errors

2018-05-08 19:22 UTC, grantgoodmanedX commented
👍 This looks sensible to me. As you note, we'll need to coordinate to update all the existing RTD projects to use the proper requirements file.

2018-05-09 13:02 UTC, nedbat requested changes

2018-05-09 13:02 UTC, nedbat commented on Makefile
> +# Do things in edx-platform
This isn't edx-platform.

2018-05-09 13:02 UTC, nedbat commented on Makefile
> +# Do things in edx-platform
Good to merge once fixed :)

2018-05-09 13:03 UTC, nedbat approved these changes

2018-05-09 13:57 UTC, jmbowman commented on Makefile
> +# Do things in edx-platform
Fixed the copy-pasta.

2018-05-09 13:57 UTC, merged