Hawthorn installation docs
openedx-unsupported/edx-documentation pull request #1718
Opened 2018-07-23 20:29 UTC by grantgoodmanedX

## [DOC-3875](https://openedx.atlassian.net/browse/DOC-3875)

Here's an initial draft of the Open edX Installation and Configuration guide for the Hawthorn release. Points of interest:

- The main change is the addition of the Docker installation instructions for Devstack and the removal of the Vagrant instructions.
- The [release page](https://draft-hawthorn-icr-guide.readthedocs.io/en/latest/platform_releases/hawthorn.html) is mostly a cut and paste from Ginkgo. I'll need to update it with Hawthorn content. 

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @nedbat 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] RTD draft: https://draft-hawthorn-icr-guide.readthedocs.io/en/latest/installation/installation_options.html

### Post-review

- [ ] Squash commits

2018-07-26 15:15 UTC, nedbat commented
@mduboseedx @jmbowman Can you two take a quick look at this PR? I'm a little behind getting rc2 out, but I'd like to make enough progress to be able to push Hawthorn docs by Monday. Thanks.

2018-07-26 20:58 UTC, nedbat requested changes

2018-07-26 20:58 UTC, nedbat commented on en_us/install_operations/source/platform_releases/hawthorn.rst
> +The following Open edX git repositories have the Hawthorn git tag:
I want to get rid of this list.  Instead, let's say, "About two dozen repos are tagged as part of an Open edX release.  Many other repos are installed as dependencies of those repos."

2018-07-26 20:58 UTC, nedbat commented on en_us/install_operations/source/platform_releases/hawthorn.rst
> +the Open edX Developer stack>`.
Or by using the Native installation instructions.

2018-07-26 20:58 UTC, nedbat commented on en_us/install_operations/source/platform_releases/hawthorn.rst
> +   version of Ginkgo that will upgrade to Hawthorn successfully is Ginkgo.2.
This should say, "Be sure that your Ginkgo installation is on the latest open-release/ginkgo.master to be sure that your database is fully migrated and ready for upgrade to Hawthorn."

2018-07-26 20:58 UTC, nedbat commented on en_us/install_operations/source/platform_releases/hawthorn.rst
> +#. Run the Hawthorn migration script, which will update your Ginkgo data to be
Change this to "Run the Hawthorn migrations,"

2018-07-26 20:58 UTC, nedbat commented on en_us/install_operations/source/platform_releases/hawthorn.rst
> +>> ANYTHING ABOUT DJANGO 1.11? The following is leftover from Ginkgo and prob. no longer applies
This section doesn't apply, true.  I'm not sure if we need something about Django 1.11.

2018-07-26 21:40 UTC, jmbowman reviewed
Pretty good start!  A lot of my comments here are due to flaws in the devstack repo's README that we should have fixed a while ago.

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/installation/install_devstack.rst
> +     mkdir devstack
Cloning the repository in the first step creates and populates this directory automatically.

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/installation/install_devstack.rst
> +   see `Virtual Environments`_.
I realize this was in the devstack README, but I actually never use a virtualenv on the host machine when using devstack.  The only direct requirement is `docker-compose`, and Docker for Mac puts a working version of that in the user's `PATH` during installation.  Linux users would need to make sure they have installed it, though.

I'm not thrilled about giving different instructions to Linux vs. Mac users, but creating a virtualenv also tends to be a major sticking point for new Python developers.  I guess I'll leave it to your judgement whether to leave this step and the next one as is, or more explicitly cover ensuring that a suitable version of `docker-compose` is installed.

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/installation/install_devstack.rst
> +   Preferences -> File Sharing** in the Docker menu.
I think this step is only relevant on macOS; Docker doesn't run in a virtual machine on Linux, so it doesn't need this additional mapping layer.

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/installation/install_devstack.rst
> +     make dev.sync.provision
I'd recommend dropping all references to Docker Sync and the optional make targets using it.  It was a performance optimization which is now only marginally faster than default operation, and we've had some reliability issues with it.

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/installation/install_devstack.rst
> +Studio.
I don't think this is still needed in Docker devstack, but you should probably confirm with someone on the EDUCATOR team to make sure.

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/installation/install_devstack.rst
> +   work with.
Do you want to cover the instructions on running the containers for a named release from https://github.com/edx/devstack/#how-do-i-run-the-images-for-a-named-open-edx-release early in the steps here?  I can see people who want to run Hawthorn's devstack getting frustrated if they pull the wrong version of the images, etc.

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/installation/installation_options.rst
> +each option includes. There are two virtual machine options, which install
Docker uses a single virtual machine under the cover on macOS, but not at all on Linux.  Maybe just say "There are two development environment installation options, ..."?

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/installation/installation_options.rst
> +* Devstack is a Docker virtual machine instance designed for local
Again, not really a virtual machine.  Something like "Devstack is a set of Docker containers designed for..."

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/installation/installation_options.rst
> +* Analytics Devstack is a modified version of the Devstack virtual machine that
Maybe "Analytics Devstack is a variation on Devstack's Docker containers that..."

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/installation/installation_options.rst
> +You can run Devstack or Analytics Devstack on Linux or Mac OS. See the
I think it's officially written "macOS" these days, having been renamed from "Mac OS X".

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/installation/installation_options.rst
> +Devstack is a deployment of the Open edX platform within a Docker instance
"...within a set of Docker containers designed..."

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/installation/installation_options.rst
> +.. How has this changed, if at all?
By default, devstack includes: LMS, Studio, Discussion Forums, ORA, Notes, XQueue, Course Discovery, E-Commerce, Credentials, demo course, and Search (re-order as you see fit).  Programs has been removed from all Hawthorn installations.

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/installation/installation_prerequisites.rst
> +  `Introduction to the Mac OS X Command Line`_.
Again, the OS has been renamed.

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/installation/start_devstack.rst
> +    make dev.sync.up
Again, probably best to omit Docker Sync.

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/installation/start_devstack.rst
> +.. _Docker Sync:
Yet more Docker Sync stuff.

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/installation/troubleshooting_devstack.rst
> +
Do you want to include some of the content from https://github.com/edx/devstack/#troubleshooting-general-tips and https://github.com/edx/devstack/#troubleshooting-common-issues here?

2018-07-26 21:40 UTC, jmbowman commented on en_us/install_operations/source/platform_releases/hawthorn.rst
> +course teams, and developers. For more information, see the relesae notes.
"relesae" (Did we ever incorporate a spellchecker into the doc build process?  If not, would it be useful?)

2018-07-26 21:40 UTC, jmbowman commented on en_us/links/links.rst
> +.. _Docker sync installation: https://github.com/EugenMayer/docker-sync/wiki/1.-Installation
If we remove the Docker Sync references, shouldn't need this.

2018-07-27 18:01 UTC, grantgoodmanedX commented on en_us/install_operations/source/platform_releases/hawthorn.rst
> +>> ANYTHING ABOUT DJANGO 1.11? The following is leftover from Ginkgo and prob. no longer applies
@jmbowman Do you know of anything we'd want to say about Django 1.11?

2018-07-27 18:09 UTC, grantgoodmanedX commented on en_us/install_operations/source/platform_releases/hawthorn.rst
> +The following Open edX git repositories have the Hawthorn git tag:
Done.

2018-07-27 18:09 UTC, grantgoodmanedX commented on en_us/install_operations/source/platform_releases/hawthorn.rst
> +the Open edX Developer stack>`.
Done.

2018-07-27 18:09 UTC, grantgoodmanedX commented on en_us/install_operations/source/platform_releases/hawthorn.rst
> +   version of Ginkgo that will upgrade to Hawthorn successfully is Ginkgo.2.
Done.

2018-07-27 18:09 UTC, grantgoodmanedX commented on en_us/install_operations/source/platform_releases/hawthorn.rst
> +#. Run the Hawthorn migration script, which will update your Ginkgo data to be
Done.

2018-07-27 18:10 UTC, grantgoodmanedX commented on en_us/install_operations/source/installation/install_devstack.rst
> +     mkdir devstack
Done.

2018-07-27 18:15 UTC, grantgoodmanedX commented on en_us/install_operations/source/installation/install_devstack.rst
> +   Preferences -> File Sharing** in the Docker menu.
Done.

2018-07-27 18:15 UTC, grantgoodmanedX commented on en_us/install_operations/source/installation/install_devstack.rst
> +     make dev.sync.provision
Done.

2018-07-27 18:35 UTC, grantgoodmanedX commented on en_us/install_operations/source/installation/install_devstack.rst
> +   work with.
Done.

2018-07-27 18:36 UTC, grantgoodmanedX commented on en_us/install_operations/source/installation/installation_options.rst
> +each option includes. There are two virtual machine options, which install
Done.

2018-07-27 18:37 UTC, grantgoodmanedX commented on en_us/install_operations/source/installation/installation_options.rst
> +* Devstack is a Docker virtual machine instance designed for local
Done.

2018-07-27 18:38 UTC, grantgoodmanedX commented on en_us/install_operations/source/installation/installation_options.rst
> +* Devstack is a Docker virtual machine instance designed for local
Done.

2018-07-27 18:38 UTC, grantgoodmanedX commented on en_us/install_operations/source/installation/installation_options.rst
> +* Analytics Devstack is a modified version of the Devstack virtual machine that
Done.

2018-07-27 18:41 UTC, grantgoodmanedX commented on en_us/install_operations/source/installation/installation_options.rst
> +You can run Devstack or Analytics Devstack on Linux or Mac OS. See the
I feel so out of touch. Done.

2018-07-27 18:46 UTC, grantgoodmanedX commented on en_us/install_operations/source/installation/installation_options.rst
> +Devstack is a deployment of the Open edX platform within a Docker instance
Done.

2018-07-27 18:48 UTC, grantgoodmanedX commented on en_us/install_operations/source/installation/start_devstack.rst
> +    make dev.sync.up
Done.

2018-07-27 18:49 UTC, grantgoodmanedX commented on en_us/install_operations/source/installation/start_devstack.rst
> +.. _Docker Sync:
Done.

2018-07-27 18:49 UTC, grantgoodmanedX commented on en_us/install_operations/source/platform_releases/hawthorn.rst
> +course teams, and developers. For more information, see the relesae notes.
Done.

2018-07-27 18:49 UTC, grantgoodmanedX commented on en_us/links/links.rst
> +.. _Docker sync installation: https://github.com/EugenMayer/docker-sync/wiki/1.-Installation
Done.

2018-07-27 18:57 UTC, jmbowman commented on en_us/install_operations/source/platform_releases/hawthorn.rst
> +>> ANYTHING ABOUT DJANGO 1.11? The following is leftover from Ginkgo and prob. no longer applies
Maybe just a brief note along the lines of the following:

> Whereas Django 1.8 has already reached the end of its support window, Django 1.11 will continue to receive security patches and critical bug fixes until April 2020.  It also has faster database migrations, better support for HiDPI screens in the admin interface, and several useful new features to enhance developer productivity (along with dozens of other bug fixes and minor improvements).

2018-07-27 20:36 UTC, grantgoodmanedX commented on en_us/install_operations/source/installation/troubleshooting_devstack.rst
> +
Done.

2018-07-27 20:40 UTC, grantgoodmanedX commented on en_us/install_operations/source/platform_releases/hawthorn.rst
> +>> ANYTHING ABOUT DJANGO 1.11? The following is leftover from Ginkgo and prob. no longer applies
That's good content for the Hawthorn release notes, but I don' t think we need it in this context - users don't need to do anything in the installation process relating to the Django upgrade. Thanks, Jeremy

2018-07-27 21:10 UTC, grantgoodmanedX commented on en_us/install_operations/source/installation/install_devstack.rst
> +   see `Virtual Environments`_.
I've removed it, and added docker-compose in your path in the installation_prequisites.rst page.

2018-07-30 12:16 UTC, nedbat commented
@grantgoodmanedX thanks for the extensive responses.  Are there open questions in here that you think should prevent us from pushing this to readthedocs?

2018-07-30 12:17 UTC, nedbat approved these changes

2018-07-30 13:36 UTC, grantgoodmanedX commented
@nedbat I think I can go ahead and publish this. I'm working on that now

2018-07-30 14:43 UTC, merged