Add cohort membership documentation
openedx-unsupported/edx-documentation pull request #1736
Opened 2018-09-06 11:54 UTC by rao-abdul-mannan

## [DE-785](https://openedx.atlassian.net/browse/DE-785)

This PR adds documentation of cohort membership data which will be available in exporter files.

### Date Needed (optional)

This feature will be released earlier next week.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2018-09-06 14:57 UTC, grantgoodmanedX requested changes
This looks good, with a few suggestions.

2018-09-06 14:57 UTC, grantgoodmanedX commented on en_us/data/source/internal_data_formats/sql_schema.rst
> +  The name of group.
"The name of the group."

2018-09-06 14:57 UTC, grantgoodmanedX commented on en_us/data/source/internal_data_formats/sql_schema.rst
> +  The type of group. Only defined group type is "cohort".
"The only defined group type is "cohort".

2018-09-06 14:57 UTC, grantgoodmanedX commented on en_us/data/source/internal_data_formats/sql_schema.rst
> +Cohort membership data represents group of users enrolled in a course.
I'd add a cross reference to provide more context: "Cohort membership data presents information about groups of users enrolled in a course. For more information about cohorts, see :ref:`partnercoursestaff:Cohorts Overview` in the *Building and Running an edX
Course* guide."

2018-09-06 15:16 UTC, brianhw reviewed
Looks good, with the few nits that Grant identified.

2018-09-06 15:16 UTC, brianhw commented on en_us/data/source/internal_data_formats/sql_schema.rst
> +Cohort membership data represents group of users enrolled in a course.
nit:  change "group of users" to "groups of users" ?

2018-09-06 15:42 UTC, grantgoodmanedX approved these changes
👍 Looks good.

2018-09-06 19:58 UTC, debchatigny commented
Looks good. 👍

2018-09-06 20:33 UTC, brianhw approved these changes
LGTM. 👍

2018-09-11 13:51 UTC, rao-abdul-mannan commented
@grantgoodmanedX @debchatigny  I received 4 warnings while running full tests with following command ( they aren't related to my changes though ).  What should be done in this case ?
`./run_tests.sh`

Who should I contact for review as subject expert, product review & PM review ? PM would be my team's project manager or different ?

2018-09-11 15:11 UTC, grantgoodmanedX commented
@rao-abdul-mannan Did you get the warnings locally? There are no warnings on Travis, so I think you can ignore any local warnings. With @brianhw 's approval, I think you can go ahead and merge this.

2018-09-11 15:18 UTC, rao-abdul-mannan commented
@grantgoodmanedX yes I got them while running locally.

2018-09-11 16:00 UTC, merged