[BB-628] Make small corrections to EdX Docs.
openedx-unsupported/edx-documentation pull request #1798
Opened 2019-02-05 13:09 UTC by giovannicimolin

This PR updates some old information on the documentation.
This covers:
- Updating installation instructions for XBlocks on the Docker Devstack 
- Removing references of the color bar for indicating status on sections (the color bars are now only on the subsections)

### Reviewers

- [ ] @viadanna
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] EdX Expert TBD

### Testing

- [x] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2019-02-05 13:09 UTC, edx-webhook commented
Thanks for the pull request, @giovannicimolin! I've created [OSPR-3051](https://openedx.atlassian.net/browse/OSPR-3051) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

2019-02-05 19:04 UTC, natabene commented
@giovannicimolin Thank you for your contribution. Please let me know once it is ready to be looked at by edX reviewers.

2019-02-06 17:37 UTC, viadanna requested changes
Looks good, just a minor change.

2019-02-06 17:37 UTC, viadanna commented on en_us/xblock-tutorial/source/edx_platform/devstack.rst
> +After this, you'll be able to enable and add the XBlock to your course.
I believe it would be a good idea including instructions to restart the LMS and Studio containers after installing the XBlock to make sure it's available.

2019-02-06 18:32 UTC, giovannicimolin commented on en_us/xblock-tutorial/source/edx_platform/devstack.rst
> +After this, you'll be able to enable and add the XBlock to your course.
Done :+1:

2019-02-07 09:39 UTC, viadanna requested changes

2019-02-07 09:39 UTC, viadanna commented on en_us/xblock-tutorial/source/edx_platform/devstack.rst
> +   $ make lms-restart && make studio-restart
👍

2019-02-07 09:39 UTC, viadanna commented on en_us/xblock-tutorial/source/edx_platform/devstack.rst
> +       $ make studio-shell
Not sure if I missed this previously or was added by the last commits, but this is being quoted and is breaking the numbering of the list. Can you check this?
![image](https://user-images.githubusercontent.com/5691347/52402470-79a2d700-2aab-11e9-95d7-7b80200cfe96.png)

2019-02-07 10:32 UTC, giovannicimolin commented on en_us/xblock-tutorial/source/edx_platform/devstack.rst
> +       $ make studio-shell
@viadanna I'm not having that issue, are you using the latest commit? This was fixed there.
![screenshot from 2019-02-07 08-31-55](https://user-images.githubusercontent.com/27893385/52405667-f08f9e00-2ab2-11e9-967b-b55513c1e33f.png)

2019-02-07 10:44 UTC, viadanna commented on en_us/xblock-tutorial/source/edx_platform/devstack.rst
> +       $ make studio-shell
That's odd, maybe an issue with GitHub parser: https://github.com/edx/edx-documentation/blob/ff1b7449d64b9002c100dae58febfa7f0c96615f/en_us/xblock-tutorial/source/edx_platform/devstack.rst

2019-02-08 02:09 UTC, giovannicimolin commented on en_us/xblock-tutorial/source/edx_platform/devstack.rst
> +       $ make studio-shell
I've fixed this! It was a whitespace issue, latest commit [here](https://github.com/edx/edx-documentation/blob/b87107a279499d6c3364ddf15771ed2dcf16b534/en_us/xblock-tutorial/source/edx_platform/devstack.rst).

2019-02-08 11:21 UTC, viadanna commented on en_us/xblock-tutorial/source/edx_platform/devstack.rst
> +       $ make studio-shell
Awesome!

2019-02-08 11:21 UTC, viadanna approved these changes
Good to go 👍

- [x] I tested this by checking the rendered doc.
- [x] I read through the code.
- [ ] ~I checked for accessibility issues.~
- [ ] ~Includes documentation.~

2019-02-08 17:07 UTC, giovannicimolin commented
@natabene This is ready for review.

2019-02-08 17:08 UTC, natabene commented
@grantgoodmanedX Can you give this a look?

2019-02-21 17:13 UTC, natabene commented
@grantgoodmanedX Gentle ping, asking for review.

2019-02-21 19:02 UTC, grantgoodmanedX approved these changes
👍 Looks good, thanks.

2019-02-21 19:02 UTC, merged

2019-02-21 19:02 UTC, edx-webhook commented
@giovannicimolin 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-documentation&entry.867055334=https://github.com/edx/edx-documentation/pull/1798&entry.1484655318=https://github.com/giovannicimolin&entry.752974735=2019-02-05+13:09&entry.1917517419=2019-02-21+19:02&entry.2133058324=Yes) so we can improve your experience in the future.