Public Course Content
openedx-unsupported/edx-documentation pull request #1806
Opened 2019-03-07 18:52 UTC by grantgoodmanedX

## [DOC-3985](https://openedx.atlassian.net/browse/DOC-3985)

Documentation for the public course content feature, which is in Ironwood. It's based heavily on the blog post draft at https://docs.google.com/document/d/1reMV0HEhT6HZSwJinvMReBULQ_u_0orz-gmLoB0yOoU/edit#

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @pomegranited 
- [ ] Subject matter expert: @symbolist
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2019-03-08 08:48 UTC, pomegranited requested changes
Thank you for submitting this PR @grantgoodmanedX !  The text reads well and is straightforward to understand.

I've left some requested amendements, but will be happy to approve when they're addressed:

* Question about the [note at the top](https://github.com/edx/edx-documentation/pull/1806/files#diff-cb323a6516d7029b99941ca6c5d94435R44)?
* One issue noted with the [waffle flag images being switched around](https://github.com/edx/edx-documentation/pull/1806/files#diff-cb323a6516d7029b99941ca6c5d94435R60).
* `Images/public-course-vis-both.png` and `Images/public-course-vis.png` are added, but unused, so these can be removed.
* Remaining comments are just nits/suggestions, so heed them if you like 😄

2019-03-08 08:48 UTC, pomegranited commented on en_us/install_operations/source/configuration/enable_public_course.rst
> +         :alt: Setting a waffle flag in the Django LMS Admin.
The images for these two types of waffle flags are switched around.  Maybe if `../Images/public-waffle-flag.png` was named `../Images/course-waffle-flag.png` this would be easier to keep straight?

Also, since they're in a shared `Images` dir, you might want to name them according to the waffle flags we're adding here.

2019-03-08 08:48 UTC, pomegranited commented on en_us/install_operations/source/configuration/enable_public_course.rst
> +   the course outline, will be visible to anyone.
nit: says "visible to everyone" above, but "visible to anyone" here.

2019-03-08 08:48 UTC, pomegranited commented on en_us/shared/developing_course/controlling_content_visibility.rst
> +  to anyone, not just enrolled learners. For information, see
nit: "not just registered and enrolled learners" ?

2019-03-08 08:48 UTC, pomegranited commented on en_us/install_operations/source/configuration/enable_public_course.rst
> +  Platform`.
Since these are [not server configuration changes](https://github.com/edx/edx-documentation/blob/master/en_us/install_operations/source/configuration/updating_platform.rst#L3), they're not protected by the guidelines noted here.  So I believe this note can be omitted?

2019-03-08 19:02 UTC, grantgoodmanedX commented
@pomegranited Thanks for your thoughtful review. I think I've addressed all of your suggestions. 

I also think that the test failure will be resolved in the build (since I'm referring to a new page that's added in the same PR).

2019-03-11 04:44 UTC, pomegranited approved these changes
@grantgoodmanedX Thank you for making this change, and for addressing my concerns !  👍  from me :)

- [x] I tested this by reading through the change and checking it against our internally-reviewed instructions for this feature.
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> Docs change only
- [x] Improves the documentation

2019-03-11 14:37 UTC, merged

2019-03-11 14:44 UTC, pomegranited commented
Thanks for getting this docs change in @grantgoodmanedX !  Can you point me to where it will be visible on the https://edx.readthedocs.io site, so I can link to it from my blog post?

2019-03-11 15:02 UTC, grantgoodmanedX commented
@pomegranited It's now visible at https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/enable_public_course.html