ADA Due Date Extensions documentation V1
openedx-unsupported/edx-documentation pull request #1828
Opened 2019-05-22 20:01 UTC by stroilova

## [DOC-XXXX](https://openedx.atlassian.net/browse/DOC-XXXX)

Documentation for ADA

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: @davestgermain 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review: @stroilova 
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2019-05-28 15:15 UTC, matthugs requested changes

2019-05-28 15:15 UTC, matthugs commented on en_us/shared/student_progress/course_grades.rst
> +Instructions
```suggestion
Instructions
============
```

would make this a subsection heading, which seems more like what you're intending here. See http://docutils.sourceforge.net/docs/user/rst/quickstart.html#sections for more information on the formatting

2019-05-28 15:15 UTC, matthugs commented on en_us/shared/student_progress/course_grades.rst
> +What courses is this feature available for?
You may want to make this more explicitly visually distinct from the text which answers the question.

2019-05-28 15:15 UTC, matthugs commented on en_us/shared/student_progress/course_grades.rst
> +You can also use this tab to **View** all deadlines or **Reset** a deadline.
why are "View" and "Reset" capitalized here?

2019-05-28 15:15 UTC, matthugs commented on en_us/shared/student_progress/course_grades.rst
> +All new courses. If you need this feature for an older course, please contact your PM.
I would recommend against abbreviating "PM" in this context; it invites questions from anal people who object to undefined abbreviations in technical writing ;)

2019-05-29 17:39 UTC, stroilova commented on en_us/shared/student_progress/course_grades.rst
> +You can also use this tab to **View** all deadlines or **Reset** a deadline.
This was mostly to visually draw attention to the other two functionalities in the Exceptions dashboard. We can edit later to add more info if needed - trying to get something quick out, as a preliminary reference.

2019-05-29 17:40 UTC, merged

2019-05-29 18:57 UTC, matthugs commented on en_us/shared/student_progress/course_grades.rst
> +You can also use this tab to **View** all deadlines or **Reset** a deadline.
Are they text used in the interface? Are they capitalized there?

2019-05-29 19:29 UTC, stroilova commented
Good question - there are two more sections:
1) a section called "Viewing granted extensions" with two call-to-action
buttons:  "List all students with due date extensions" and "List date
extensions for student"
2) a section called "Resetting extensions" with a single call-to-action
button:  "Reset due date for student"

Agreed that we can build out the docs more here - and perhaps also make the
UI CTA labels more cohesive as well (E.g. use View consistently). I was
thinking these could be V2 polish improvements, after we got a V1 solidly
out...

On Wed, May 29, 2019 at 2:57 PM Matt Hughes <notifications@github.com>
wrote:

> *@matthugs* commented on this pull request.
> ------------------------------
>
> In en_us/shared/student_progress/course_grades.rst
> <https://github.com/edx/edx-documentation/pull/1828#discussion_r288720960>
> :
>
> > +You can extend graded subsection due dates for individual learners.
> +
> +This can be used to support special circumstances, personal emergencies, and disabilities accommodations.
> +
> +Instructions
> +
> +To extend a deadline for a learner, visit the **Extensions** tab on the **Instructor Dashboard**
> +
> +1. Look up learner by email address or username
> +2. Choose the graded subsection from the dropdown
> +3. Enter new due date
> +4. Specify the reason for the extension
> +5. Click **Change due date for student**
> +
> +
> +You can also use this tab to **View** all deadlines or **Reset** a deadline.
>
> Are they text used in the interface? Are they capitalized there?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/edx/edx-documentation/pull/1828?email_source=notifications&email_token=AAXMS3YE7UC4R44XUDKCI5TPX3G2FA5CNFSM4HOXQ4K2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB2BNOIQ#discussion_r288720960>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAXMS35KGPUEIOT7JL4XENLPX3G2FANCNFSM4HOXQ4KQ>
> .
>

2019-06-03 14:28 UTC, brittneyexline commented
is it possible that this PR is causing failures for the test suite? we have a PR open where the tests are failing, and the same failures happen on master when tests are run locally... this was the last thing that was merged
let me know if there is an easy way to resolve this and we can include it in our PR (https://github.com/edx/edx-documentation/pull/1829)
fyi @saleem-latif

2019-06-04 12:28 UTC, stroilova commented
Hi Brittney,

Yes, you might be right, one of the ADA documentation tests might be
failing. We'll explore today.

Thanks,
Olga

On Mon, Jun 3, 2019 at 10:28 AM Brittney Exline <notifications@github.com>
wrote:

> is it possible that this PR is causing failures for the test suite? we
> have a PR open where the tests are failing, and the same failures happen on
> master when tests are run locally... this was the last thing that was merged
> let me know if there is an easy way to resolve this and we can include it
> in our PR (#1829 <https://github.com/edx/edx-documentation/pull/1829>)
> fyi @saleem-latif <https://github.com/saleem-latif>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/edx/edx-documentation/pull/1828?email_source=notifications&email_token=AAXMS357HFLPFKEIVRDFY3LPYUTBFA5CNFSM4HOXQ4K2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWZSO2I#issuecomment-498280297>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAXMS36UBOV7DUKABL3N65LPYUTBFANCNFSM4HOXQ4KQ>
> .
>