ENT-1912: Added xAPI customer facing documentation/instructions
openedx-unsupported/edx-documentation pull request #1829
Opened 2019-05-31 11:02 UTC by saleem-latif

## [ENT-1912](https://openedx.atlassian.net/browse/ENT-1912)

This PR adds customer-facing documentation for xAPI.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2019-05-31 14:52 UTC, mattdrayer requested changes
Looking good -- thanks very much for adding this documentation!

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +This references include detailed information about the `xAPI (Experience API)` of the reporting services.
"This references contains detailed information about edX Enterprise Reporting Services, including the `xAPI (Experience API)` reporting channel."

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +xAPI
"xAPI Reporting Channel"

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +xAPI (experience API) lets the content providers report user experience analytics back to the client.
"xAPI (experience API) allows content providers to report..."

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +xAPI can be used to track learner events starting from course enrollment and upto course completion.
"and upto" -> "through"

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +Following is the list of the events currently being tracked by the xAPI.
"Here is the list of events currently reported via the edX xAPI reporting channel."

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +    * course info (e.g. course_id, course_title, course_description etc.)
"course" -> "Course"

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +    * Learner grades for course completion (grade, success or failure? etc.)
"success or failure?" -> "pass/fail status"

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +To integrate client’s LRS  (Learning Record Store) with edX reporting channel, the following are required
"The following information is required in order to broadcast xAPI events from edX to a client's LRS  (Learning Record Store):"

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +#. URL to the LRS
"Learning Record Store (LRS) Endpoint URL"

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +#. URL to the LRS
Please include a sample value.

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +#. Client Id (or client key) of a client on LRS
"Learning Record Store Client ID/Key"    (also please include sample value)

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +#. Client Secret of a client on LRS
"Learning Record Store Client Secret" (also please include sample value)

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +**********************
This information is for internal use by the edX team -- it should not be presented to customers or it will confuse them.

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +Reporting Mechanism:
"xAPI Event Delivery Mechanism"

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +edX queues all of the xAPI events for the learners of a client and sends these at a specified time every day.
"The edX xAPI Event Delivery Mechanism currently transmits events in batches on a daily basis."

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +Each event is sent as a separate API request but during a specified time window.
"Each event is transmitted separately."

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +Information sent to LRS depends on the type of event being reported.
Information contained within each xAPI event depends on the type of event being transmitted.

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +Sample Payload data for xAPI LRS (Learning Record Store)
"Sample Payload Data for edX xAPI Events"

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +Sample data for the events sent to the LRS is as follows:
Sample data for xAPI events sent to a client Learning Record Store is as follows:

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +enterprise learner (a student associated with an enterprise customer) enrolls in a course.
Remove "(a student associated with an enterprise customer)"

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +enterprise learner (a student associated with an enterprise customer) completes a course.
Remove "(a student associated with an enterprise customer)"

2019-05-31 14:52 UTC, mattdrayer commented on en_us/enterprise_api/source/reporting_services/reference.rst
> +**********************
Also we can remove the PNG file that accompanies this section from the PR.

2019-06-03 09:49 UTC, saleem-latif commented
@mattdrayer I have updated the documentation according to your feedback, please take another look.

@brittneyexline regarding the test failure, I ran the test command `./run_tests.sh` locally on master and it fails with the same message as on my branch. What should be the right way to handle this? should I create a ticket to resolve that issue?

2019-06-03 14:28 UTC, brittneyexline commented
@saleem-latif - i think the test failures are related to the pr that was most recently merged: https://github.com/edx/edx-documentation/pull/1828
i left a comment there, but don't feel blocked on merging this.

2019-06-04 00:35 UTC, mattdrayer approved these changes
Please remove the extra binary file from this PR -- otherwise I think it looks great!

2019-06-04 15:14 UTC, merged