[WIP] Added Information on how to enable course metadata
openedx-unsupported/edx-documentation pull request #1871
Opened 2020-06-25 21:19 UTC by nizarmah

Adds information on how to enable course metadata. This is helpful for those who are trying to add course metadata but can't figure out where the `Other Course Settings` field is in _Advanced Settings_. 

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] @bradenmacdonald 

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

> There were warnings; however, the changes done did not increase the number of warnings. The warnings present are already present in the `master` branch.

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2020-06-25 21:19 UTC, edx-webhook commented
Thanks for the pull request, @nizarmah! I've created [OSPR-4757](https://openedx.atlassian.net/browse/OSPR-4757) to keep track of it in JIRA, where we prioritize reviews.  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.

2020-06-26 05:36 UTC, nizarmah commented
I am aware that the build failed. However, the file edited, which is `creating_new_course.rst`, has not shown any warnings or errors. The warnings that are present were already present in the `master` branch, which was the base of this branch.

2020-06-26 16:47 UTC, bradenmacdonald requested changes
Thanks, just one change. Also please mark this as not "Draft" once it's ready. Don't worry about the failing build, it's clearly unrelated and you can just rebase this once it's fixed in master.

2020-06-26 16:47 UTC, bradenmacdonald commented on en_us/shared/set_up_course/studio_add_course_information/creating_new_course.rst
> +  under ``FEATURES`` in ``cms.env.json`` and restart Studio.
From Juniper onward this setting is made in `/edx/etc/studio.yml` (and `/edx/etc/lms.yml`) instead of the .env.json files.

2020-06-26 18:50 UTC, natabene commented
@nizarmah Thank you for your contribution. Please let me know once it is ready for edX review.

2020-06-26 19:00 UTC, nizarmah commented
@natabene I'm happy to be contributing! I believe it is ready. It is a slight addition, that's all, in hopes to add some clarification. 🙂

2020-06-26 20:53 UTC, bradenmacdonald approved these changes
👍

2020-06-30 00:41 UTC, natabene commented
@nizarmah Thank you, I am lining this up for our review.

2020-06-30 10:59 UTC, merged

2020-06-30 10:59 UTC, edx-webhook commented
@nizarmah 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-documentation&entry.867055334=https://github.com/edx/edx-documentation/pull/1871&entry.1484655318=https://github.com/nizarmah&entry.752974735=2020-06-25+21:19&entry.1917517419=2020-06-30+10:59&entry.2133058324=Yes) so we can improve your experience in the future.

2020-07-17 00:52 UTC, pomegranited commented
Congratulations on getting this PR merged @nizarmah ! And thank you for opening it.. improving user-facing documentation is so helpful for so many people.