update teams documentation
openedx-unsupported/edx-documentation pull request #1874
Opened 2020-07-13 14:09 UTC by jansenk

Draft of updated Teams documentation

- Replaced references to topics with team sets
- Modified opening paragraph about reasonings / uses of teams
- Added section about teamset types

2020-07-13 14:20 UTC, jansenk commented on en_us/shared/course_features/teams/teams_setup.rst
> +   teams associated with the deleted team set. (This isn't even true. They'll still show up on My Teams)
This is a draft but don't merge this xD

2020-07-15 15:48 UTC, nsprenkle reviewed
Some notes about establishing consistent spelling/capitalizations and finishing loose ends from the draft, but the content is good 👍

2020-07-15 15:48 UTC, nsprenkle commented on en_us/shared/course_features/teams/teams_setup.rst
> +teams in your course by defining "Team Sets", groups of teams based around a specific
Confirm w/ Sapana the canonical punctuation/capitalization.

e.g. Team Sets vs Team sets vs team sets vs Team-Sets vs Team-sets vs team-sets

2020-07-15 15:48 UTC, nsprenkle commented on en_us/shared/course_features/teams/teams_setup.rst
> +It can also optionally specify a primary communication language
Wording nit: the team itself is not the subject doing the action of setting a language
```suggestion
A primary communication language can optionally be specified
```

2020-07-15 15:48 UTC, nsprenkle commented on en_us/shared/course_features/teams/teams_setup.rst
> -    "topics": [
I thought we still called this `topics`

2020-07-15 15:48 UTC, nsprenkle commented on en_us/shared/course_features/teams/teams_setup.rst
> +includes team set names and the maximum team size.
Same note here about canonical spelling of `team set`

2020-07-15 15:48 UTC, nsprenkle commented on en_us/shared/course_features/teams/teams_setup.rst
> +   teams associated with the deleted team set. (This isn't even true. They'll still show up on My Teams)
Yeah, this feels like an area to clarify w/ product what we want and how it deviates from actual behavior.

2020-07-15 15:48 UTC, nsprenkle commented on en_us/shared/course_features/teams/teams_setup.rst
> +   Max Team Size should
Unfinished sentence fragment?

2020-07-15 15:48 UTC, nsprenkle commented on en_us/shared/course_features/teams/teams_setup.rst
> +   which will be explained later in this document.
For narrative flow, I think it makes sense to give a brief description of the "type" instead of hinting at it but not explaining it.
```suggestion
   which sets the visibility and access for teams. Different ``"type"`` configurations are explained in the next section"
```

2020-07-15 15:48 UTC, nsprenkle commented on en_us/shared/course_features/teams/teams_setup.rst
> +Each team set has a 'type'. Setting a team set's type allows you to control who can see, create, and join teams within
This is an excellent intro line 🥇

2020-07-15 15:48 UTC, nsprenkle commented on en_us/shared/course_features/teams/teams_setup.rst
> +staff. Course staff can control team membership through the **Manage** tab on the **Teams** page. (The **Manage** tab
Same note about "teamset" syntax

2020-07-15 19:05 UTC, muselesscreator commented on en_us/shared/course_features/teams/teams_setup.rst
> +teams in your course by defining "Team Sets", groups of teams based around a specific
I think we are going with Team-Sets as the standardized version for customer-facing (re: 5170)

2020-07-15 19:05 UTC, muselesscreator commented on en_us/shared/course_features/teams/teams_setup.rst
> +teams in your course by defining "Team Sets", groups of teams based around a specific
note: not going to comment on other instances, but should copy the decided-on wording throughout

2020-07-15 19:06 UTC, muselesscreator commented on en_us/shared/course_features/teams/teams_setup.rst
> +It can also optionally specify a primary communication language
+1

2020-07-15 19:06 UTC, muselesscreator commented on en_us/shared/course_features/teams/teams_setup.rst
> +to connect socially, consider using discussions  within the course rather than teams.
double-space

2020-07-15 19:08 UTC, muselesscreator commented on en_us/shared/course_features/teams/teams_setup.rst
> +   teams associated with the deleted team set. (This isn't even true. They'll still show up on My Teams)
Yeah... if this is the intended behavior (enough to be used for user-facing docs) I feel like there should be a ticket for it,

2020-07-15 19:09 UTC, muselesscreator commented on en_us/shared/course_features/teams/teams_setup.rst
> +   which will be explained later in this document.
+1

2020-07-15 19:11 UTC, muselesscreator commented on en_us/shared/course_features/teams/teams_setup.rst
> +================  ===========================  ==========================  =====================================  =============================
++

2020-07-15 19:12 UTC, muselesscreator commented on en_us/shared/course_features/teams/teams_setup.rst
> +   new team in this team set** link.
Should this be updated in the code as well as part of 5170 to match the user-facing terminology?

2020-07-15 19:14 UTC, muselesscreator commented
Overall looks great.
One Sentence fragment that **needs** to be fixed, and then a bunch of instances of needing to replace "team set", "teamset", or "Team Set" with the approved user-facing string (which I believe is "Team-Set")

2020-07-16 15:25 UTC, jansenk commented on en_us/shared/course_features/teams/teams_setup.rst
> -    "topics": [
calling it topics is deprecated, but still allowed

2020-07-16 15:38 UTC, jansenk commented on en_us/shared/course_features/teams/teams_setup.rst
> +================  ===========================  ==========================  =====================================  =============================
What does this comment mean?

2020-07-16 17:20 UTC, jansenk commented
I've created a google doc to make it easier for sapana to review. If you have additional comments, try to make them / copy them there as well: https://docs.google.com/document/d/1LipCl_UmRu6f5-ECNHo9VEBCHnVlDtIkF9w32SifHpw/edit?usp=sharing

2020-07-28 20:19 UTC, nsprenkle requested changes
Updates needed from https://openedx.atlassian.net/browse/EDUCATOR-5170

2020-07-28 20:19 UTC, nsprenkle commented on en_us/shared/course_features/teams/teams_setup.rst
> +**Teamset with id [ID] is duplicated**
```suggestion
**Team-set with id [ID] is duplicated**
```

2020-07-28 20:19 UTC, nsprenkle commented on en_us/shared/course_features/teams/teams_setup.rst
> +**Teamset with id [ID] does not exist**
```suggestion
**Team-set with id [ID] does not exist**
```

2020-07-28 20:19 UTC, nsprenkle commented on en_us/shared/course_features/teams/teams_setup.rst
> +**Team(s) [team] don’t have matching teamsets**
```suggestion
**Team(s) [team] don’t have matching team-sets**
```

2020-07-28 21:03 UTC, nsprenkle commented on en_us/shared/course_features/teams/teams_setup.rst
> +When a team is created, it is given an name and description to identify it.
```suggestion
When a team is created, it is given a name and description to identify it. 
```

2021-05-11 14:36 UTC, nedbat commented
@jansenk @nsprenkle What's the status of these changes?

2022-01-13 17:32 UTC, jansenk commented on en_us/shared/course_features/teams/teams_setup.rst
> +teams in your course by defining "team-sets", groups of teams based around a specific
need to change this term as I guess they aren't "team-sets" anymore?

2022-01-13 17:32 UTC, jansenk commented on en_us/shared/course_features/teams/teams_setup.rst
> +up a team-set where learners can join a team to discuss a certain course topic,
and here

2022-01-13 17:32 UTC, jansenk commented on en_us/shared/course_features/teams/teams_setup.rst
> +or set up a team-set where learners can join a team to work on a group assignment.
and here

2022-01-13 17:32 UTC, jansenk commented on en_us/shared/course_features/teams/teams_setup.rst
> +or set up a team-set where learners can join a team to work on a group assignment.
not gonna continue but just blanket we should be consistent with terms and even though we weren't a part of this discussion, the UI uses a new term now so we should change the docs i guess

2022-01-13 17:32 UTC, jansenk commented on en_us/shared/course_features/teams/teams_setup.rst
> +**Types of Team Groups**
This whole thing is from https://github.com/openedx/edx-documentation/pull/1990

2022-02-08 15:48 UTC, merged