CR-2617 Remove timed exam settings on advanced settings from docs
openedx-unsupported/edx-documentation pull request #1883
Opened 2020-08-29 11:38 UTC by schenedx

The application change was done 2 months ago. We need to remove the reference of it from the documentation

## [CR-2617](https://openedx.atlassian.net/browse/CR-2617)

Remove the documentation that is out of date.

@edx/masters-devs-cosmonauts Please review

2020-08-31 13:35 UTC, matthugs requested changes
From the build
>../shared/course_features/timed_exams.rst:37: WARNING: undefined label: learners:taking_timed_exams (if the link has no caption the label must precede a section header)

I am not sure about wholesale deleting this. I think a note indicating that the setting is deprecated would suffice, if it is still an available option.

2020-08-31 14:18 UTC, schenedx commented
@matthugs I took your feedback and edit the removal to discuss the setting as deprecated setting.
As for the warning message you pointed out, that was not a result of my change here. I believe that warning exists in Masters branch as well.

2020-09-01 17:52 UTC, michaelroytman reviewed
I have just a few grammatical improvements and a question around clarifying some instructions. Overall, I think this is good; I just want to better understand what "please set the specific exam type" means before approving.

2020-09-01 17:52 UTC, MichaelRoytman commented on en_us/shared/course_features/timed_exams.rst
> +Timed exams is automatically enabled in your course.
```suggestion
Timed exams are automatically enabled in your course.
```

2020-09-01 17:52 UTC, MichaelRoytman commented on en_us/shared/course_features/timed_exams.rst
> +If you want to disable the Timed exams, please set the specific exam type.
```suggestion
If you want to disable timed exams, please set the specific exam type.
```

2020-09-01 17:52 UTC, MichaelRoytman commented on en_us/shared/course_features/timed_exams.rst
> +If you want to disable the Timed exams, please set the specific exam type.
I'm not sure what "please set the specific exam type" means here. Does this mean that you should go to each subsection that is set to be a "timed" exam and set it to "none"? Can we be more specific with our instructions in this case or link to elsewhere in the documentation that discusses this?

2020-09-01 17:52 UTC, MichaelRoytman commented on en_us/shared/course_features/timed_exams.rst
> +   page
```suggestion
   page.
```
There's a missing period.

2020-09-01 19:39 UTC, michaelroytman approved these changes
Thank you for incorporating my feedback!

2020-09-01 19:42 UTC, merged