Explain requirements for certificate auto-generation
openedx-unsupported/edx-documentation pull request #1914
Opened 2021-02-17 20:03 UTC by fghaas

Update *Installing, Configuring, and Running the Open edX Platform* to explain that with regard to certificate auto-generation, it

* requires setting a Waffle switch,
* does not apply to enrollments in the audit and honor tracks.

In addition, update the *Building and Running an Open edX Course* guide with a back-reference to the former, to clarify that certificate auto-generation for self-paced courses does not work out of the box in an Open edX configuration, and instead requires the aforementioned Waffle switch.

2021-02-17 20:03 UTC, edx-webhook commented
Thanks for the pull request, @fghaas! I've created [OSPR-5630](https://openedx.atlassian.net/browse/OSPR-5630) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2021-02-17 20:21 UTC, fghaas commented
Not quite sure how to fix this. The GitHub workflow tells me that there's a problem in `course_authors`, but `./run_tests.sh en_us/course_authors/` works for me:

```
$ ./run_tests.sh en_us/course_authors/
[...]
Build finished. The HTML pages are in build/html.
SPHINX ERRORS: 0
SPHINX WARNINGS: 0

********** All builds done ************
TOTAL SPHINX ERRORS: 0
TOTAL SPHINX WARNINGS: 0
OTHER BUILD ERRORS: 0
All builds passed.
```

Likewise in `en_us/install_operations/`:

$ ./run_tests.sh en_us/install_operations/
[...]
Build finished. The HTML pages are in build/html.
SPHINX ERRORS: 0
SPHINX WARNINGS: 0

********** All builds done ************
TOTAL SPHINX ERRORS: 0
TOTAL SPHINX WARNINGS: 0
OTHER BUILD ERRORS: 0
All builds passed.
```

And just `run_tests.sh` by itself, which is what the `Build Docs` action runs, exits 0 for me, so I don't really know what breaks in GitHub.

So, I guess this is ready for review?

2021-02-19 15:37 UTC, natabene commented
@fghaas Thank you for your contribution. @nedbat could you take a look?

2021-02-22 14:59 UTC, nedbat commented
The warning seems harmless.  Running run_tests.sh locally once in a clean environment reproduces the warning, but running it a second time passes.

2021-02-22 15:01 UTC, nedbat commented on en_us/install_operations/source/configuration/enable_certificates.rst
> +Open edX caches the the value of this Waffle switch, thus the changed
```suggestion
Open edX caches the value of this Waffle switch, thus the changed
```

2021-02-22 15:02 UTC, nedbat requested changes
Just one tweak, then we can merge! Thanks.

2021-02-22 18:45 UTC, fghaas commented
> Just one tweak, then we can merge! Thanks.

Thanks for catching that! Fixed, and rebased on current `master`.

2021-02-22 20:33 UTC, merged

2021-02-22 20:33 UTC, edx-webhook commented
@fghaas 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-documentation&entry.867055334=https://github.com/edx/edx-documentation/pull/1914&entry.1484655318=https://github.com/fghaas&entry.752974735=2021-02-17+20:03&entry.1917517419=2021-02-22+20:33&entry.2133058324=Yes) so we can improve your experience in the future.

2021-02-24 12:30 UTC, fghaas commented
@nedbat, just checking:

* In https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/enable_certificates.html#enable-automatic-certificate-generation, the cross-document links to _Building and Running an Open edX Course_ are working correctly.
* However, in https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/student_progress/checking_student_progress.html#allow-learners-to-receive-early-certificates, the backlink "(see enable automatic certificate generation in Installing, Configuring, and Running the Open edX Platform)" isn't being rendered correctly.

This does not match my local behavior when running `develop.sh`, where both of those cross-references render as links. Did I do something wrong, or is something broken in the production build process?

2021-02-24 18:37 UTC, nedbat commented
I re-built the book with the missing link, and now it's there.  There's something about inter-book references that is hard to get right.

2021-02-24 19:44 UTC, fghaas commented
Looks great now. Thank you!