[BD-24] Add LTI 1.3 documentation and reorganize docs WIP
openedx-unsupported/edx-documentation pull request #1934
Opened 2021-04-15 15:07 UTC by giovannicimolin

## [DOC-XXXX](https://openedx.atlassian.net/browse/DOC-XXXX)

This PR adds LTI 1.3 and LTI Advantage documentation while reorganizing the documentation contents. 

### Reviewers

- [ ] Subject matter expert: @nedbat 
- [ ] Subject matter expert: @sarina 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review: @marcotuts 

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2021-04-15 15:07 UTC, edx-webhook commented
Thanks for the pull request, @giovannicimolin! I've created [BLENDED-825](https://openedx.atlassian.net/browse/BLENDED-825) to keep track of it in Jira.   More details are on the [BD-24](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1545076784/BD-24+LTI+v1.3+Improvements+Advantage+Support) project page.


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->


<!-- comment:welcome-blended -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2021-04-15 15:59 UTC, marcotuts commented on en_us/shared/exercises_tools/lti_component.rst
> +information, see :ref:`Enable Additional Exercises and Tools`.
We really need to get rid of this silly step of enabling LTI as an advanced module. We similarly simplified the unit page experience for ORA recently. Given how close we are to done on the budget we can do this outside of BD-24 instead of adding another story here. 

@sarina , @nedbat can connect on whether this is a reasonable LTI backlog item to consider or something T&L should consider as part of authoring efficiency type efforts in the future.  

This comment is not blocking for the PR at all, but wanted to put this thread into the context of the educator impact today.

2021-04-17 01:12 UTC, marcotuts approved these changes

2021-04-21 14:29 UTC, giovannicimolin commented
@nedbat @sarina @marcotuts I've finished writing the documentation.
You can use this sandbox to test: https://lti-1p3-validation.opencraft.hosting (with the usual `staff` sanbox users).

2021-04-22 14:11 UTC, sarina commented on en_us/shared/exercises_tools/lti_component.rst
> +`Deep Linking`_ and `Assignments and Grades services`_.
The image below (L48) is broken

2021-04-22 14:47 UTC, sarina reviewed
I did a pass at formatting and wording. Overall it is clear. I think I need an LTI component to practice the setup instructions?

2021-04-22 14:47 UTC, sarina commented on en_us/shared/exercises_tools/lti_component.rst
> +`Deep Linking`_ and `Assignments and Grades services`_.
Also I wonder if the underscore is needed outside of the ticks? They're showing up in the text. So are the ticks. I'm not versed enough in RST to know the fix offhand.

![image](https://user-images.githubusercontent.com/1985317/115729228-3ca52100-a353-11eb-929b-3479e363a85a.png)

2021-04-22 14:47 UTC, sarina commented on en_us/shared/exercises_tools/lti_component.rst
> +`Deep Linking`_ and `Assignments and Grades services`_.
Same at L26 & 58

![image](https://user-images.githubusercontent.com/1985317/115730662-80e4f100-a354-11eb-847f-654d5ce5d885.png)

2021-04-22 14:47 UTC, sarina commented on en_us/shared/exercises_tools/lti_component.rst
> +`Deep Linking`_ and `Assignments and Grades services`_.
and L66/71 links don't work

![image](https://user-images.githubusercontent.com/1985317/115731114-dd481080-a354-11eb-88ea-b8d3ca7bd0f8.png)

2021-04-22 14:47 UTC, sarina commented on en_us/shared/exercises_tools/lti_component.rst
> +.. note::
This note isn't indenting the text properly

2021-04-22 14:47 UTC, sarina commented on en_us/shared/exercises_tools/lti_component.rst
> +information, see :ref:`Enable Additional Exercises and Tools`.
This `ref` displays funny, as I pointed out above

2021-04-22 14:47 UTC, sarina commented on en_us/shared/exercises_tools/lti_component.rst
> +  ``lti`` module is no longer present in the **Advanced Module List**.
Do we recommend they remove `lti` module from Advanced Module List?

2021-04-22 14:47 UTC, sarina commented on en_us/shared/exercises_tools/lti_component.rst
> +Some LTI 1.1 tools require users to provide authentication credentials. If the LTI
typo at L161 - shouldn't be a new line - puts a space between `yr` and `8`

2021-04-22 14:47 UTC, sarina commented on en_us/shared/exercises_tools/lti_component.rst
> +*******************************
I would add this same header above the 1.1 instructions

2021-04-22 14:47 UTC, sarina commented on en_us/shared/exercises_tools/lti_component.rst
> +   You also see to set **LTI 1.3 Tool Public Key** with a key provided by the
nit: s/You/you/

2021-04-22 14:47 UTC, sarina commented on en_us/shared/exercises_tools/lti_component.rst
> +   For basic LTI 1.3 launches, the following variables are required:
what are these variables & where do they come from?

2021-04-22 14:47 UTC, sarina commented on en_us/shared/exercises_tools/lti_component.rst
> +.. note:: LTI 1.3 launches only work with published blocks, make sure the block is
this note is also not properly indenting

2021-04-22 14:47 UTC, sarina commented on en_us/shared/exercises_tools/lti_component.rst
> +   the LTI-AGS service by selecting **Disabled** or pick one of the tho operation
nit: remove `tho`

2021-04-22 14:47 UTC, sarina commented on en_us/shared/exercises_tools/lti_component.rst
> +.. note:: LTI 1.3 launches only work with published blocks, make sure the block is
note not indenting correctly

2021-04-23 18:52 UTC, nedbat commented on en_us/shared/exercises_tools/lti_component.rst
> +`Deep Linking`_ and `Assignments and Grades services`_.
You can't trust GitHub rendering for links like this. They depend on .rst features GitHub doesn't support, mostly multi-file features.  If you checkout this PR and run ./run_tests.sh locally, all the links resolve with no warnings.

2021-04-23 20:58 UTC, nedbat requested changes

2021-04-23 20:58 UTC, nedbat commented on en_us/shared/exercises_tools/lti_component.rst
> +To enable the LTI tool in Studio, add the ``"lti_consumer"`` module to the
```suggestion
To enable the LTI tool in Studio, add ``"lti_consumer"`` to the
```

2021-04-23 20:58 UTC, nedbat commented on en_us/shared/exercises_tools/lti_component.rst
> +   LTI tool. An example key is shown below, and should be pasted directly in
We should make clear that this example will not work.  Maybe something like, "the key will look something like this example: ... You should paste your key directly into the configuration field."

2021-04-23 20:58 UTC, nedbat commented on en_us/shared/exercises_tools/lti_component.rst
> +#. The studio page will refresh and display LTI configuration required by the
```suggestion
#. The Studio page will refresh and display LTI configuration required by the
```

2021-04-23 20:58 UTC, nedbat commented on en_us/shared/exercises_tools/lti_component.rst
> +.. note:: LTI 1.3 launches only work with published blocks, make sure the block is
It looks like this in HTML: 
<img width="752" alt="image" src="https://user-images.githubusercontent.com/23789/115925893-e669d800-a44f-11eb-8954-576cd70ba1bc.png">

2021-04-23 20:58 UTC, nedbat commented on en_us/shared/exercises_tools/lti_component.rst
> +   For basic LTI 1.3 launches, the following variables are required:
You refer to these as "values" in the previous sentence, it will be clearer to also call them "values" here, or "configuration values".

2021-04-23 20:58 UTC, nedbat commented on en_us/shared/exercises_tools/lti_component.rst
> +Currently, Open edX supports the following LTI Advantage extensions:
This file is shared between two versions of the authoring book.  Do we have a good way to refer to edX or Open edX that works for both?

2021-04-23 20:58 UTC, nedbat commented on en_us/shared/exercises_tools/lti_component.rst
> +   entry on :ref:`LTI Component settings`.
Can we put a description of the modes here?  As written, it would require flipping to another part of the docs.

2021-04-23 20:58 UTC, nedbat commented on en_us/shared/exercises_tools/lti_component.rst
> +   entry on :ref:`LTI Component settings`.
```suggestion
   modes available. For more information about each mode, see :ref:`LTI Component settings`.
```

2021-04-23 20:58 UTC, nedbat commented on en_us/shared/exercises_tools/lti_component.rst
> +#. Once the configuration is complete, you'll be redirected back to the LMS and the
Back to the LMS, or back to Studio?

2021-04-23 20:58 UTC, nedbat commented on en_us/shared/exercises_tools/lti_component.rst
> +       This is sometimes called *redirect* url in some tools.
url should be capitalized, and perhaps it would be cleared as "This is sometimes called "Redirect URL" in some tools."

2021-04-23 20:58 UTC, nedbat commented on en_us/shared/exercises_tools/lti_component.rst
> +         and the tool will have full control over the grading process, enabling it to
```suggestion
       * **Allow tools to manage and submit grade (programmatic)** - The tool will have full control over the grading process, enabling it to
```

2021-04-23 20:58 UTC, nedbat commented on en_us/shared/exercises_tools/lti_component.rst
> +         will be linked to the LMS.
Can we change "linked to" to "returned to" or "reported to"?

2021-04-23 20:58 UTC, nedbat commented on en_us/shared/exercises_tools/lti_component.rst
> +   entry on :ref:`LTI Component settings`.
How about, "or pick one of the operation modes available: declarative to allow one grade, or programmatic to let the tool create many grades. For more information ..."

2021-04-26 14:21 UTC, giovannicimolin commented on en_us/shared/exercises_tools/lti_component.rst
> +  ``lti`` module is no longer present in the **Advanced Module List**.
@sarina I think this was already in the documentation. Not sure how old or how many courses are still using the `lti` module though. I feel like rewording the old docs doesn't apply to the current scope, and I prefer if there's a follow up task for it.

2021-04-26 14:23 UTC, giovannicimolin commented on en_us/shared/exercises_tools/lti_component.rst
> +*******************************
@sarina It's already above, but the difference is that LTI 1.1 requires setting up the passport strings, which are subsections of the `Setting up an LTI 1.1 component` header.

2021-04-26 14:31 UTC, giovannicimolin commented on en_us/shared/exercises_tools/lti_component.rst
> +#. Once the configuration is complete, you'll be redirected back to the LMS and the
Studio, thanks for catching this.

2021-04-26 14:37 UTC, giovannicimolin commented on en_us/shared/exercises_tools/lti_component.rst
> +Currently, Open edX supports the following LTI Advantage extensions:
@nedbat Maybe `the plaform`?

2021-04-26 14:40 UTC, giovannicimolin commented on en_us/shared/exercises_tools/lti_component.rst
> +         will be linked to the LMS.
Done!

2021-04-26 14:40 UTC, giovannicimolin commented on en_us/shared/exercises_tools/lti_component.rst
> +   entry on :ref:`LTI Component settings`.
I went with the second approach, mentioning the modes available and linking to the docs.

2021-04-26 14:41 UTC, giovannicimolin commented on en_us/shared/exercises_tools/lti_component.rst
> +   LTI tool. An example key is shown below, and should be pasted directly in
Done.

2021-04-26 14:42 UTC, giovannicimolin commented
@sarina @nedbat I addressed the review comments. This is ready for another review pass.

2021-04-27 13:39 UTC, nedbat requested changes
Ugh, I caught one more typo, then good to merge!

2021-04-27 13:39 UTC, nedbat commented on en_us/shared/exercises_tools/lti_component.rst
> +features in LTI components. See `LTI Advantage`_ for more imformation.
```suggestion
features in LTI components. See `LTI Advantage`_ for more information.
```

2021-04-27 13:55 UTC, giovannicimolin commented on en_us/shared/exercises_tools/lti_component.rst
> +features in LTI components. See `LTI Advantage`_ for more imformation.
Fixed!

2021-04-28 13:01 UTC, sarina commented on en_us/shared/exercises_tools/lti_component.rst
> +  ``lti`` module is no longer present in the **Advanced Module List**.
👍

2021-04-28 13:02 UTC, sarina commented on en_us/shared/exercises_tools/lti_component.rst
> +*******************************
👍

2021-04-28 13:02 UTC, sarina approved these changes

2021-04-28 18:42 UTC, viadanna approved these changes
Good to go, just a comment on a link getting Access Denied.

- [x] I read through this.
- [x] I tested the links.

2021-04-28 18:42 UTC, viadanna commented on en_us/links/links.rst
> +.. _IMS LTI 1.1 Consumer Launch: https://www.imsglobal.org/developers/LTI/test/v1p1/lms.php
Got an Access Denied here :(

2021-04-28 19:54 UTC, giovannicimolin commented
@viadanna @nedbat The broken link above is only used for the LTI Provider setup (on https://github.com/edx/edx-documentation/blob/9468a2681170a2b5cdbe46e4193939f94a4833df/en_us/install_operations/source/configuration/lti/tpa_lti.rst#L87-L88). 
It's probably returning a `Access Denied` here because it's expecting a LTI 1.1 authentication message. I've reverted my changes to this line.

2021-05-05 13:39 UTC, nedbat approved these changes

2021-05-05 13:39 UTC, merged