docs: add the native installation page to docs and reorganized installation index page
openedx-unsupported/edx-documentation pull request #1948
Opened 2021-06-03 15:03 UTC by alfredchavez

## Issue: https://github.com/openedx/build-test-release-wg/issues/53

- Moved wiki page  https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/1969455764/Koa+Native+Open+edX+platform+Ubuntu+20.04+64+bit+Installation to be displayed instead of native installation section in installation_operations index
- I moved the other sections of the installation part and added a toctree that redirects to them instead, I think it is better organized that way(now that native installation is a page)
- Added new links and changed links that redirected to wiki of koa/lilac installation

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

### Testing

- [x] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2021-06-03 15:03 UTC, edx-webhook commented
Thanks for the pull request, @alfredchavez! I've created [OSPR-5833](https://openedx.atlassian.net/browse/OSPR-5833) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2021-06-03 18:24 UTC, natabene commented
@alfredchavez Thank you for your contribution. Is this ready for our review?

2021-06-03 19:50 UTC, alfredchavez commented
@natabene Hi, yes, I think it is ready for review

2021-06-04 15:40 UTC, sarina requested changes
A few small changes requested, then I'll merge

2021-06-04 15:40 UTC, sarina commented on en_us/install_operations/source/installation/native_installation.rst
> +This page describes how to install the Open edX Koa release on a single Ubuntu 20.04 64-bit server from scratch. For Juniper and earlier, see `Open edX Native Installation`_.
Two nits: 1. I'd list Lilac first (before Koa) everywhere as with Lilac's release we would prefer people not run Koa.

2. I'd change the title of the Juniper & earlier instructions to `Legacy Open edX Native Installation` and put a big, big header on there that says this is for old releases only (is Juniper supported with Lilac's release?)

2021-06-04 15:40 UTC, sarina commented on en_us/install_operations/source/installation/native_installation.rst
> +Bad suggestions (Arbitrary Upgrades)
Nit: Call this section DO NOT UPGRADE or something similarly warning-like. `Bad Suggestions` feels like something I'd glaze over

2021-06-04 18:57 UTC, alfredchavez commented
@sarina Hi, I have added the requested changes, including a fix to some references in release notes I was missing
Let me know if more change is needed

2021-06-04 19:09 UTC, sarina approved these changes

2021-06-04 19:10 UTC, sarina commented
This is great thanks @alfredchavez ! I didn't realize build wasn't running, I added you to the whitelist. When the build passes, I will merge it.

2021-06-04 19:14 UTC, merged

2021-06-04 19:14 UTC, edx-webhook commented
@alfredchavez 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-documentation&entry.867055334=https://github.com/edx/edx-documentation/pull/1948&entry.1484655318=https://github.com/alfredchavez&entry.752974735=2021-06-03+15:03&entry.1917517419=2021-06-04+19:14&entry.2133058324=Yes) so we can improve your experience in the future.

2021-06-04 19:14 UTC, sarina commented
If you are porting this to Lilac/Koa branches, please ping me for a merge

2021-06-07 14:40 UTC, nedbat commented
I've cherry-picked this onto Lilac as 658b0f8991b5740629686e71e32974f37cc4ee5f