docs: Adds Tutor as a supported installation method
openedx-unsupported/edx-documentation pull request #1952
Opened 2021-06-07 22:18 UTC by arbrandes

Adds Tutor as a supported (and recommended) installation method starting on Lilac, consolidates references to the Native Installation, while also integrating the gist of the "Open edX Installation Options" wiki page.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: @nedbat 
- [ ] Subject matter expert: @regisb 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2021-06-07 22:18 UTC, edx-webhook commented
Thanks for the pull request, @arbrandes! I've created [OSPR-5844](https://openedx.atlassian.net/browse/OSPR-5844) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2021-06-08 05:10 UTC, regisb commented on en_us/install_operations/source/insights/tutor.rst
> +deployment of Lilac and above.
Is it accurate to say that "the native installation is being deprecated in Lilac"? My understanding was that the native installation would be deprecated for Maple, but not before then. If my interpretation is correct, I suggest the following wording:

> Tutor is a supported installation method as of Lilac. It is expected to replace the native installation, which is scheduled for deprecation in the next release (Maple). We recommend to use Tutor for any new Open edX deployment of Lilac and above.

2021-06-08 13:25 UTC, arbrandes commented on en_us/install_operations/source/insights/tutor.rst
> +deployment of Lilac and above.
I was under the impression this would be the last release where the BTR group would support edx/configuration - _unless_ Tutor doesn't work out in the next 6 months, for some reason.  No?

2021-06-08 13:25 UTC, arbrandes commented on en_us/install_operations/source/insights/tutor.rst
> +deployment of Lilac and above.
@nedbat, thoughts?

2021-06-08 13:39 UTC, regisb commented on en_us/install_operations/source/insights/tutor.rst
> +deployment of Lilac and above.
> I was under the impression this would be the last release where the BTR group would support edx/configuration - unless Tutor doesn't work out in the next 6 months, for some reason. No?

Yes, of course, this is what we agreed. I guess at this point it's more a question of language comprehension: when I read that "the native installation method is being deprecated in the same release", I understand that it's already deprecated. But maybe I'm misunderstanding. I'll let people who speak better English than me decide :)

2021-06-08 13:43 UTC, arbrandes commented on en_us/install_operations/source/insights/tutor.rst
> +deployment of Lilac and above.
Ah, ok.  Yes, a third set of eyes would be good.  To be clear, what I meant by "deprecation in the same release" was that we will be deprecating edx/configuration (i.e., announcing that it will be retired) with Lilac.1, with a target for actual retirement of Maple.1.

2021-06-08 15:55 UTC, nedbat commented on en_us/install_operations/source/insights/tutor.rst
> +deployment of Lilac and above.
I came here to comment on "deprecated", and found this discussion! Nice, I will soon be obsolete :)

I think "deprecated" is a squishy and confusing term.  Perhaps we can say, "Because we expect Tutor to completely replace the Native installation for Maple, ..."

2021-06-08 15:56 UTC, nedbat commented on en_us/install_operations/source/insights/tutor.rst
> +.. _Open edX Tutor Installation:
This file is in the insights directory, which is not where it should be.  I will make a PR into this PR to fix the warnings also. One sec.

2021-06-08 16:08 UTC, nedbat commented on en_us/install_operations/source/installation/native_installation.rst
> +.. _Open edX Native Installation:
This causes one of the warnings.  I haven't thought through this completely, but I think it is fine for master and Lilac to have this page titled "Lilac Native...".  When we make Maple, we can update the page, and master and Maple will say "Maple...", while Lilac will continue to say Lilac.

2021-06-08 16:26 UTC, nedbat commented
I've made a PR for changes: https://github.com/open-craft/edx-documentation/pull/2   This fixes the warnings that are failing the build.

2021-06-08 18:01 UTC, arbrandes commented on en_us/install_operations/source/insights/tutor.rst
> +deployment of Lilac and above.
Good call, @nedbat.  I incorporated your suggestion.  Work for you, @regisb?

2021-06-08 18:01 UTC, arbrandes commented
> I've made a PR for changes: [open-craft#2](https://github.com/open-craft/edx-documentation/pull/2) This fixes the warnings that are failing the build.

I added your PR here.  Thanks @nedbat!

2021-06-08 18:04 UTC, regisb commented on en_us/install_operations/source/insights/tutor.rst
> +deployment of Lilac and above.
Works great for me.

2021-06-08 18:27 UTC, nedbat requested changes
The wiki page just points to readthedocs, so skip the step by linking straight there.

2021-06-08 18:27 UTC, nedbat commented on en_us/install_operations/source/installation/index.rst
> +Details of the releases are at the `Open edX Releases Wiki Page`_.
```suggestion
Details of the releases are on the `Open edX Named Releases page`_.
```

2021-06-08 18:27 UTC, nedbat commented on en_us/install_operations/source/installation/index.rst
> +Details of the releases are at the `Open edX Releases Wiki Page`_.
And also apply this patch:
```
diff --git a/en_us/links/links.rst b/en_us/links/links.rst
index e0d9d6da..64e6ca6d 100644
--- a/en_us/links/links.rst
+++ b/en_us/links/links.rst
@@ -230,6 +230,8 @@
 
 .. _Open edX Releases Wiki page: https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/11108700/Open+edX+Releases
 
+.. _Open edX Named Releases page: https://edx.readthedocs.io/projects/edx-developer-docs/en/latest/named_releases.html
+
 .. _Release Pages: https://openedx.atlassian.net/wiki/pages/viewpage.action?pageId=12550314
 
 .. _Open edX Installation options: https://openedx.atlassian.net/wiki/x/wwCXAw
```

2021-06-09 02:18 UTC, natabene commented
@arbrandes Thank you for your contribution. Glad to see reviews are well underway.

2021-06-09 17:36 UTC, arbrandes commented on en_us/install_operations/source/installation/index.rst
> +Details of the releases are at the `Open edX Releases Wiki Page`_.
Agreed.  (Though the patch isn't needed.  That link is already there, further up.)

2021-06-09 17:51 UTC, nedbat approved these changes

2021-06-09 17:52 UTC, merged

2021-06-09 17:52 UTC, openedx-webhooks commented
@arbrandes 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-documentation&entry.867055334=https://github.com/edx/edx-documentation/pull/1952&entry.1484655318=https://github.com/arbrandes&entry.752974735=2021-06-07+22:18&entry.1917517419=2021-06-09+17:52&entry.2133058324=Yes) so we can improve your experience in the future.

2021-06-09 17:56 UTC, nedbat commented
I've cherry-picked this onto Lilac.