Added Edx Discovery API docs
openedx-unsupported/edx-documentation pull request #1978
Opened 2021-08-31 11:55 UTC by HammadAhmadWaqas

## [ENT-4877](https://openedx.atlassian.net/browse/ENT-4877)

Added documentation for EdX discovery API, specifically for taxonomy.

### Testing

-  clone this repo.
-  create new virtual env
-  install requirement by `make requirements`
-  install more requirements by `pip install -r shared/tools.txt`
-  run server by `./develop.sh en_us/discovery_api/`
- open `http://127.0.0.1:9090` to see docs

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2021-09-01 14:16 UTC, mattdrayer commented on en_us/discovery_api/source/api_reference/reference.rst
> +* **/jobs** - You can make GET calls to the
I think the `jobs` endpoints are going to cause a lot of confusion for people down the road if we don't do a good "job" providing the context for this data.   We need to provide more descriptive information about what skills are, what jobs are, etc.   Otherwise API consumers will likely think that edX has some sort of job listings business and that these endpoints return information about those.

2021-09-01 14:17 UTC, mattdrayer commented on en_us/discovery_api/source/intro_edx_apis.rst
> +catalogs, and search. It also provides skills, jobs and job postings data for courses.
Here we should add more information about what skills are, and what jobs are, in the context of the Discovery Service.

2021-09-01 14:18 UTC, mattdrayer approved these changes
The PR looks good from a programmatic standpoint.  We need to include more context about what Skills are, what Jobs are, etc.  This info should be made available in the Intro area, at least for starters.

2021-09-02 08:06 UTC, saleem-latif requested changes

2021-09-02 08:06 UTC, saleem-latif commented on en_us/discovery_api/source/api_reference/reference.rst
> +*********
I think the number of `*` should be the same as the number of characters in the title. Same for all other places.

2021-09-02 08:06 UTC, saleem-latif commented on en_us/discovery_api/source/api_reference/reference.rst
> +The following endpoints are available in the Discovery API under Taxonomy app.
nit:  The following endpoints are available in the Taxonomy app under Discovery API.

2021-09-02 08:06 UTC, saleem-latif commented on en_us/discovery_api/source/api_reference/reference.rst
> +  ``/skills/{skill_id}`` endpoint to get a details of a specified
nit: remove `a`, will change to `endpoint to get details of ...`

2021-09-02 08:06 UTC, saleem-latif commented on en_us/discovery_api/source/api_reference/reference.rst
> +that represents the intended object from the GET request. here is the details.
nit: Please change to "Here are the details."

2021-09-02 08:06 UTC, saleem-latif commented on en_us/discovery_api/source/api_reference/reference.rst
> +GET calls to ``/skills`` endpoint return a list of all the available skills in the system.
nit: Please change to "GET call to \`\`/skills\`\` endpoint returns a list of all the available skills in the system."

2021-09-02 08:06 UTC, saleem-latif commented on en_us/discovery_api/source/api_reference/reference.rst
> +records you want to load in a single page. if you will not specify the
nit: capitalize 'if', change to `If`

2021-09-02 08:06 UTC, saleem-latif commented on en_us/discovery_api/source/api_reference/reference.rst
> +records you want to load in a single page. if you will not specify the
Also change it to "If not provided the default of 20 is used for \`page_size\`."

2021-09-02 08:06 UTC, saleem-latif commented on en_us/discovery_api/source/api_reference/reference.rst
> +     - Unique identifier in edx system. It is Used to get detailed views.
use small letters in "Used", change to "It is used to get the detailed views."

2021-09-02 08:06 UTC, saleem-latif commented on en_us/discovery_api/source/api_reference/reference.rst
> +     - Represents the relevance the skill to course. It's value ranges from 0 to 1.
nit: change to "Represents the relevance of the skill to course. It's value ranges from 0 to 1."

2021-09-02 08:06 UTC, saleem-latif commented on en_us/discovery_api/source/api_reference/reference.rst
> +     - An identifier for the object in EMSI system. Example: "KS122LN6CLX3P61KWSP2".
I think we should not reference EMSI in docs.

2021-09-02 08:06 UTC, saleem-latif commented on en_us/discovery_api/source/api_reference/reference.rst
> +GET calls to ``/jobs`` endpoint return a list of all the available jobs in the system.
nit: change to "GET call to \`\`/jobs\`\` endpoint returns a list of all the available jobs in the system."

2021-09-02 08:06 UTC, saleem-latif commented on en_us/discovery_api/source/api_reference/reference.rst
> +records you want to load in a single page. if you will not specify the
nit: change to "Also change it to "If not provided the default of 20 is used for \`page_size\`."

2021-09-02 08:06 UTC, saleem-latif commented on en_us/discovery_api/source/api_reference/reference.rst
> +GET calls to ``/jobpostings`` endpoint return a list of all the available job postings in the system.
nit: change to "GET call to \`\`/jobpostings\`\` endpoint returns a list of all the available job postings in the system."

2021-09-02 08:06 UTC, saleem-latif commented on en_us/discovery_api/source/api_reference/reference.rst
> +`page_size` it will take 20 as default. For example:
nit: change to "Also change it to "If not provided the default of 20 is used for \`page_size\`."

2021-09-02 13:02 UTC, HammadAhmadWaqas commented
@mattdrayer @saleem-latif 
I have tried to incorporate all the feedback.

Could you please review it again?

2021-09-03 06:21 UTC, irfanuddinahmad commented on en_us/discovery_api/source/intro_edx_apis.rst
> +These ``skills`` are extracted by text processing provided in course's full description. We
The ``skills`` are associated with the courses using third party services.

2021-09-03 06:21 UTC, irfanuddinahmad commented on en_us/discovery_api/source/intro_edx_apis.rst
> +using third party tools and services. ``Job posting`` is information about the number of job postings
remove "using third party tools and services" from here since it is now mentioned above

2021-09-03 07:09 UTC, HammadAhmadWaqas commented on en_us/discovery_api/source/intro_edx_apis.rst
> +using third party tools and services. ``Job posting`` is information about the number of job postings
The above one is a different page. That is why I mentioned it here as well.

2021-09-03 10:34 UTC, irfanuddinahmad commented on en_us/discovery_api/source/api_reference/reference.rst
> +The following endpoints are available in Taxonomy app under the Discovery API.
*in the Taxonomy application ...

2021-09-03 10:34 UTC, irfanuddinahmad commented on en_us/discovery_api/source/api_reference/reference.rst
> +This API reference includes detailed information about the endpoints of the edX
remove "detailed"

2021-09-03 10:34 UTC, irfanuddinahmad commented on en_us/discovery_api/source/api_reference/reference.rst
> +    `skills`. We extract this imformation using third party tools and services.
*information

2021-09-03 10:34 UTC, irfanuddinahmad commented on en_us/discovery_api/source/api_reference/reference.rst
> +    Jobs are linked with the skills that can help the learners to those jobs in
Jobs are linked with the skills to help learners align their career plans with their course work.

2021-09-03 10:34 UTC, irfanuddinahmad commented on en_us/discovery_api/source/api_reference/reference.rst
> +    JobPostings is information about the number of job postings available in market,
JobPostings contains the number of job postings with posting company and median salary information.

2021-09-03 10:34 UTC, irfanuddinahmad commented on en_us/discovery_api/source/api_reference/reference.rst
> +Example Response Showing Information skills list
* Information about skills list

2021-09-03 10:34 UTC, irfanuddinahmad commented on en_us/discovery_api/source/api_reference/reference.rst
> +Example Response Showing Information Job details
* Information about

2021-09-03 10:34 UTC, irfanuddinahmad commented on en_us/discovery_api/source/api_reference/reference.rst
> +Example Response Showing Information JobPostings
* Information about

2021-09-03 12:58 UTC, irfanuddinahmad commented on en_us/discovery_api/source/api_reference/reference.rst
> +    Skills are extracted by text processing provided in course
I think text processing is not quite accurate ... EMSI uses AI on its large database to come up with these matches

2021-09-03 12:59 UTC, irfanuddinahmad commented on en_us/discovery_api/source/intro_edx_apis.rst
> +the ``skills`` are extracted by text processing provided in course's full description. We
I think text processing is not quite accurate ... EMSI uses AI on its large database to come up with these matches

2021-09-07 09:51 UTC, HammadAhmadWaqas commented on en_us/discovery_api/source/intro_edx_apis.rst
> +the ``skills`` are extracted by text processing provided in course's full description. We
I was trying to say we are using `text` in full description to get skills. I have rephrased it to remove confusion.
@irfanuddinahmad could you please has a look at it again.

2021-09-07 10:52 UTC, irfanuddinahmad commented on en_us/discovery_api/source/api_reference/reference.rst
> +    their for desired skills. You can make GET calls to the ``/skills`` endpoint to get
their

2021-09-07 10:57 UTC, irfanuddinahmad approved these changes
LGTM!

2021-09-07 11:22 UTC, merged