docs: Add a tip with link for commit style
openedx-unsupported/edx-documentation pull request #2037
Opened 2022-03-09 10:35 UTC by ghassanmas

It just adds a tip in the contributor guide, about the commit style
which is coverd [OEP 51](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html). 

Add a description of your changes with links to any relevant material.

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:.

- [ ] Subject matter expert:
- [ ] Subject matter expert:
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support:
- [ ] PM review:

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2022-03-09 10:35 UTC, edx-webhook commented
Thanks for the pull request, @ghassanmas! I've created [OSPR-6511](https://openedx.atlassian.net/browse/OSPR-6511) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-03-09 10:42 UTC, ghassanmas commented
This ready for review

2022-03-15 16:58 UTC, natabene commented
@ghassanmas Thank you for your contribution.

2022-03-15 20:36 UTC, nedbat commented on en_us/developers/source/process/contributor.rst
> +
I like the idea of mentioning OEP-51, but I think we can be more direct about it.  How about:
```
#. Commit messages should conform to `OEP-51\: Conventional Commits`_.  This style categorizes commits to make them easier to understand.
```

2022-03-15 20:38 UTC, nedbat requested changes
Let's simplify the paragraph.

2022-03-16 10:10 UTC, ghassanmas commented on en_us/developers/source/process/contributor.rst
> +
Yup make sense, since there is a note about sqush on later points.

2022-03-16 13:24 UTC, nedbat approved these changes

2022-03-16 13:24 UTC, merged

2022-03-16 13:25 UTC, edx-webhook commented
@ghassanmas 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-documentation&entry.867055334=https://github.com/openedx/edx-documentation/pull/2037&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2022-03-09+10:35&entry.1917517419=2022-03-16+13:24&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->