docs: Add more details about studio Import Errors.
openedx-unsupported/edx-documentation pull request #2078
Opened 2022-08-09 19:17 UTC by feanil

The document we linked to was not public so I pulled out the relevant
information about the new types of errors.

2022-08-09 21:03 UTC, arbrandes approved these changes
Thanks for doing this, @feanil!

I realize this was copied verbatum from the source, but I figure we could copyedit it, some.  Hence, my  suggestions.

Just suggestions, though.  I'm fine if this is committed as-is.

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +- **File Chunk Missed During Upload** - The most common error that was captured, “Chunk Missed Error”. When a Course Import file (tar.gz) is larger than 20MB, it is divided into equal chunks and uplo
Probably means to say "combining", rather than "combing".  Also missing a period at the end.

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +- **File Chunk Failed To Upload Error** - This error is raised when a file chunk has been lost during the upload process. Due to this the file is corrupted and can not be processed.
can + not = cannot

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +- **Incompatible File** - This error is raised for the sanity check if a user accidentally tries to upload an incompatible file. This check exists in the frontend as well.
I'd shorten/rephrase a little:  "Raised if a user accidentally tries to upload..."

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +There are a few validation checks before the unpacking of the tar file begins. These validation checks look redundant and similar to file upload but these errors are in place because this is an async
I don't get it.  Are the additional validation checks implemented?  What exactly was out of scope?

(Later...) Ah, the What's Next section sheds some light on this:

> Currently, there are duplicate validations that happen during the Upload and Unpacking stages. The main reason is that the Unpacking stage is asynchronous and can be called through an API. Code cleanup is required so that this duplicate code can be avoided. There are the following duplicate validations as of today
> 
> * The file has a valid extension
> * User is valid
> * The user has write permissions

I figure we can just get rid of this intro paragraph.  Otherwise, this looks like info that should be a comment in the code.

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +- **Invalid User** - In case the user_id provided does not exist. This is highly unlikely to occur from the front end, but this check is in place for the sanity check.
Weird phrasing.  How about:

"Raised if the provided `user_id` does not exist.  The check is redundant if the import is submitted via Studio frontend, but is a valid sanity check for API submissions."

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +- **Permission Denied** - This error occurs if the user does not have the required permissions to perform the course import. Once that case occurs, the system throws the error to the user.
Redundant last sentence.  We should ditch "Once that case occurs..."

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +- **Incompatble File** - This error is raised if the file to unpack is not in tar.gz format. This check verifies that the process of unpacking does not execute if the file is not in a valid format.
Last sentence also kinda redundant.

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +- **File Not Found** - This error occurs if the uploaded file is not available in the storage or has been deleted.
"in storage"

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +- **Unsafe Tar File** - This is a system-level error that occurs when the tar file tries to unpack itself at the root where it does not have permissions.
" ...tries to unpack itself at the root directory."

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +- **Unknown Exception** - There can still be unknown events that may occur during the course import, for those further information will be logged in the system logs but there is not a clear and usefu
"There can still be unforeseen errors during the course import.  Those will be detailed in the system logs, but the user-facing message is generic."

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +- **Verify Root Name** - The root name for a course import is ``course.xml`` and for a library it's ``library.xml``. If that file does not exist then this error is thrown.
"The root XML file for a course is..."

"If one or the other does not exist..."

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +The errors can occur after the XML validation and during the data update in the course.
"These errors..."

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +- **Error while parsing asset XML** - Error while reading ``assets.xml`` file when it has syntax or other errors.
"Syntax or other parsing errors while reading ``assets.xml``."

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +- **Duplicate CourseID** - Aborting import because a course with this id already exists
Missing final period.

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +- **Module Import Error** - A module in the coures failed to import correctly.
Typo: "course".

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +- **Unknown Error** - An unknown error occured whyl updating the course.
Typo: "while"

Also, not really a fan of "unknown".  We can't change the error name, but in the description I'd say "An _unforeseen_ error".

2022-08-09 21:03 UTC, arbrandes commented on en_us/open_edx_release_notes/source/maple.rst
> +   More information about the development process can be found in this `documented in Confluence`_.  However that is not a public document and only left here for admins and future reference. The erro
Typo: "document in Confluence"

2022-08-10 02:27 UTC, merged

2022-08-10 02:35 UTC, pdpinch requested changes
I agree with Adolfo's copy edits, and added one more. 

It's a little odd to stuff all this into the release notes, but I think it's a OK solution for the issue. 

What would be the process to add something to the _Building and Running a Course_ docs at https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/releasing_course/export_import_course.html?highlight=import#import-a-course ?

2022-08-10 02:35 UTC, pdpinch commented on en_us/open_edx_release_notes/source/maple.rst
> +Now educators will see specific error messages in the course import area of Studio. For developers, these errors are logged and can exported to a New Relic, Splunk, etc.
wow, did I copy edit this? 😳

```suggestion
Now educators will see specific error messages in the course import area of Studio. For developers, these errors are logged and can be exported to New Relic, Splunk, etc.
```

2022-08-10 02:37 UTC, pdpinch commented
Oops, too slow. I'm going to let it ride.