docs: 11.3 section of documentation updated according to new MFE
openedx-unsupported/edx-documentation pull request #2085
Opened 2022-10-03 11:55 UTC by mehaknasir

Add a description of your changes with links to any relevant material.

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:.

- [ ] Subject matter expert:
- [ ] Subject matter expert:
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support:
- [ ] PM review:

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2022-10-05 07:16 UTC, ayub02 requested changes
Center all images please.

2022-10-05 07:16 UTC, ayub02 commented on en_us/open_edx_students/source/sfd_discussions/add_post.rst
> +If the course staff has enabled the option to allow anonymous posts, a Post anonymously to peers checkbox
Bold font style for "Post anonymously to peers"

2022-10-05 07:16 UTC, ayub02 commented on en_us/open_edx_students/source/sfd_discussions/add_post.rst
> +    functional purpose, leave the Description field empty and select This image is for decorative purposes
Change text to: "leave Image Description field empty"
Set font style bold for "Image Description"
Set font style bold for "This image is for decorative purposes only and does not require a description"

2022-10-05 07:16 UTC, ayub02 commented on en_us/open_edx_students/source/sfd_discussions/add_post.rst
> +description and source of the image.
Image is missing

2022-10-05 07:16 UTC, ayub02 commented on en_us/open_edx_students/source/sfd_discussions/add_post.rst
> +    :width: 700
reduce width to 500

2022-10-05 07:16 UTC, ayub02 commented on en_us/open_edx_students/source/sfd_discussions/add_post.rst
> +    :width: 700
reduce width to 500

2022-10-05 11:22 UTC, mehaknasir commented on en_us/open_edx_students/source/sfd_discussions/add_post.rst
> +description and source of the image.
https://draftinf-572.readthedocs.io/en/latest/sfd_discussions/add_post.html#add-image-to-a-post-on-the-discussion-page

<img width="794" alt="Screen Shot 2022-10-05 at 4 22 15 PM" src="https://user-images.githubusercontent.com/67791278/194049197-d7daf6dc-d8c8-419c-bc29-36da42c3e79c.png">

I can see the image here

2022-10-06 11:37 UTC, ayub02 approved these changes

2022-10-06 18:42 UTC, merged