WIP: Olive Release Notes
openedx-unsupported/edx-documentation pull request #2093
Opened 2022-11-20 17:01 UTC by pdpinch

Olive Release Notes. 

part of https://github.com/openedx/build-test-release-wg/issues/229

### Date Needed (optional)

Nutmeg will be released on Decmber 9, 2022

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:.

- [ ] Subject matter expert: @sarina 
- [ ] Subject matter expert: @feanil 
- [ ] Subject matter expert: @nedbat 
- [ ] Subject matter expert: @kdmccormick 
- [ ] Subject matter expert: @ghassanmas
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review: @jmakowski1123 
- [x] PM review: n/a (Is a PM different from Product Review?)

 @blarghmatey @shaidar @shellyu @cachob 

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [x] https://olive.demo.overhang.io/

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2022-11-20 17:01 UTC, openedx-webhooks commented
Thanks for the pull request, @pdpinch!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2022-12-02 17:01 UTC, kdmccormick commented on en_us/open_edx_release_notes/source/olive.rst
> +.. _How to Enable Persistent Grades: https://openedx.atlassian.net/wiki/spaces/AC/pages/755171487/WIP+How+to+Enable+Persistent+Grades+in+Hawthorne
This page was written from the perspective of a Hawthorne-era edx.org developer. I reworked it and renamed it to make more sense for the Olive release.
```suggestion
.. _Migrating to Persistent Grading: https://openedx.atlassian.net/wiki/spaces/AC/pages/755171487/Migrating+to+Persistent+Grading
```

2022-12-02 21:52 UTC, kdmccormick commented on en_us/open_edx_release_notes/source/olive.rst
> +- fixed a performance issue when using multiple themes when running in docker. Now by using LRU cache when searching themes,  the performance was improved.
@dcoa @arbrandes @ghassanmas We will want to bring up [MFE Runtime Config](https://github.com/openedx/frontend-wg/issues/103) in these notes, both in terms of the new benefits as well as the breaking changes to tutor-mfe.

2022-12-11 19:48 UTC, ghassanmas commented on en_us/open_edx_release_notes/source/olive.rst
> +- fixed a performance issue when using multiple themes when running in docker. Now by using LRU cache when searching themes,  the performance was improved.
I am happy to collaborate on this, from tutor-mfe side speaking there is now the olive overhangio/tutor-mfe/pull/66 which I suppose probably would entail docs about the breaking changes because of the dynamic config. 
Secondaly, do we need to cross post those info or just to announce that _tutor-mfe in Olive has a breaking chanegs and please review instursction at <insert link tutor-mfe readme.rst file>_

Other thing I think worth mentioning is that from Olive, 
- you can run/start openedx without buildling the MFE image, _so about 25 minutes saved_.
- You wouldn't need to rebuild the image when changing configuration like `SITE_NAME` 
- More info _link for tutor-mfe readme file_

2022-12-12 12:47 UTC, arbrandes requested changes
These are great, thanks a lot @pdpinch!

I made a couple of totally optional suggestions, but there are a couple of changes I'm actually asking for.  (Hopefully the distinction is clear in context.)

2022-12-12 12:47 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +The Learning Micro Frontend (MFE) is no longer optional, and must be run as part of your installation now. It has been the default since the Maple release, with a setting that allowed for opting out.
Suggestion: the "now" feels a bit redundant.

```suggestion
The Learning Micro Frontend (MFE) is no longer optional, and must be run as part of your installation. It has been the default since the Maple release, with a setting that allowed for opting out. The setting :code:`courseware.use_legacy_frontend` has been removed. (See Deprecations & Removals below for more).
```

2022-12-12 12:47 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +The Learning Micro Frontend (MFE) is no longer optional, and must be run as part of your installation now. It has been the default since the Maple release, with a setting that allowed for opting out.
Another suggestion: it would be nice to link to the Deprecations & Removals anchor instead of just mentioning it.

2022-12-12 12:47 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +The Discussions MFE is included in the Olive release, but is not enabled by default. You can control which learners will see it with the waffle flag :code:`discussions.enable_discussions_mfe`. To con
Actually, as of Friday, it *is* enabled by default. :)

2022-12-12 12:47 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +- The Learner records MFE is now available as an optional frontend for the Credentials application. See the `Learner Records MFE README`_ for configuration information.
Suggestion: maybe we should explicitly mention that Credentials needs to be installed and running for the LRMFE to work?

2022-12-12 12:47 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +The Course Authoring Micro-frontend is included in the Olive release. It is enabled by setting :code:`COURSE_AUTHORING_MICROFRONTEND_URL`. The Course Authoring MFE allows for several new features, in
We should mention that the MFE itself is enabled by default: the fact we mention the MFE URL explicitly might lead people to think otherwise.

We should also mention that only the Pages & Resources feature is enabled by default.  The new editors are not.

Finally, I think we should also say here that of the new editors, only the HTML editor is production-ready.  I ran into issues testing the Video editor: the video preview wasn't working.  And the problem one is just a place-holder, of course.

2022-12-12 12:47 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +Part of the :ref:`course-authoring-mfe`, when this feature is enabled course authors can now get to the Pages & Resources view from the Content menu (it replaces the "Pages" menu item). This is a mod
```suggestion
Part of the :ref:`course-authoring-mfe`, when this feature is enabled course authors can now get to the Pages & Resources view from the Content menu (it replaces the "Pages" menu item). This is a modular interface for settings for various course applications and tools. Depending on which ones are enabled, they can include Progress, Discussion, Notes, Wiki, Calculator, Custom pages, Proctoring, and Textbooks. The waffle flag :code:`discussions.pages_and_resources_mfe` must be set to enable access to Pages & Resources.  (It is enabled by default.)
```

2022-12-12 12:47 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +Part of the :ref:`course-authoring-mfe`, the new video editor can be enabled by setting the waffle flag :code:`new_core_editors.use_new_text_editor`
```suggestion
Part of the :ref:`course-authoring-mfe`, the new video editor can be enabled by setting the waffle flag :code:`new_core_editors.use_new_video_editor`
```

2022-12-12 12:47 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +- Send out an email to discussion moderators when a content (post/response/comment) is reported. See https://github.com/openedx/edx-platform/pull/30276 for more details.
```suggestion
An email can now be sent out to discussion moderators when content (post/response/comment) is reported.  To use it, set the :code:`discussions.enable_reported_content_email_notifications` waffle flag.  See https://github.com/openedx/edx-platform/pull/30276 for more details.
```

2022-12-12 12:47 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +* `Discussions Micro-Frontend (MFE)`_
We can remove Authn and Discussions from this list.

```suggestion
```

2022-12-12 12:47 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +.. _Discussions Micro-Frontend (MFE): https://github.com/openedx/frontend-app-discussions
```suggestion
```

2022-12-12 12:47 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +
```suggestion
Known Issues
============
```

It would be nice to have a section detailing the issues we couldn't get fixes to in time.  At time of writing, it's mostly about the Zoom Tool being broken.  See option 1 [in this comment](https://github.com/openedx/build-test-release-wg/issues/208#issuecomment-1340889576).

There are also hard-coded mentions of edX in the AuthN MFE.  It's more than likely we'll only get to them by Olive.2.

2022-12-12 13:11 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +- fixed a performance issue when using multiple themes when running in docker. Now by using LRU cache when searching themes,  the performance was improved.
How about:

```suggestion

MFE runtime configuration support
---------------------------------

Where up until Nutmeg it was only possible to change a micro-frontend's settings at build time, it is now possible to do so at both server _and_ browser runtime via a new configuration mechanism.  In addition to the added convenience, this significantly reduces the frequency at which MFE container images need to be rebuilt.  Many operators will never have to build them to begin with, as pre-built ones can be (and are) provided, thus saving up precious time and resources on deployment.

This behavior is optional and controlled by the :code:`ENABLE_MFE_CONFIG_API` Django setting in the LMS, and the :code:`APP_ID` and :code:`MFE_CONFIG_API_URL` MFE build-time settings.  The actual runtime configuration can then be specified via the :code:`MFE_CONFIG` and :code:`MFE_CONFIG_OVERRIDES` variables in the LMS.  (These can also be overriden via `site configuration <https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/sites/configure_site.html>`_, with the effect that such configuration can be changed dynamically via the backing database.)  For more details, refer to the `corresponding architecture decision record <https://github.com/openedx/edx-platform/blob/open-release/olive.master/lms/djangoapps/mfe_config_api/docs/decisions/0001-mfe-config-api.rst>`_.

Other Operator Experience changes
---------------------------------
- fixed a performance issue when using multiple themes when running in docker. Now by using LRU cache when searching themes,  the performance was improved.
```

2022-12-12 13:26 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +- fixed a performance issue when using multiple themes when running in docker. Now by using LRU cache when searching themes,  the performance was improved.
@kdmccormick @ghassanmas if there's a breaking change, I would want to mention it in the breaking change section, and then probably give the rest of these details in the Administrators and Operators section. 

What is the breaking change exactly?

2022-12-12 13:58 UTC, regisb commented on en_us/open_edx_release_notes/source/olive.rst
> +The Persistent Grades feature was added as an option in Hawthorne. Legacy, non-persistent grades were deprecated in Nutmeg. Now, persistent grades are required. If you have not turned on persistent g
Can you please specify that existing Tutor user are not affected and do not have to migrate persistent grades because they were enabled in Nutmeg?

2022-12-12 13:58 UTC, regisb commented on en_us/open_edx_release_notes/source/olive.rst
> +The Learning Micro Frontend (MFE) is no longer optional, and must be run as part of your installation. It has been the default since the Maple release, with a setting that allowed for opting out. The
In Tutor terms, this means that the MFE plugin must be installed and enabled (see below).

2022-12-12 14:08 UTC, ghassanmas commented on en_us/open_edx_release_notes/source/olive.rst
> +
I can provide context, the thing I am note following correctly, is the docs seems to be written in a perspective of outside tutor/tutor-mfe ecosystem, and that being said, you can use dynamic config without tutor and there wouldn’t be a breaking changes by default as to my knowledge. 

On the other hand the part about not needed to rebuild the image, for that I can say that
1. you don’t need to rebuild the image for specific args using dynamic config 
1. With ( specific set up, a proxy role) + (dynamic config) you might not need to rebuild the image at all 
   1. This the default case for tutor-mfe 
   1. This can be useful  for other providers even outside tutor-mfe, consider the case you have different LMS instances but you want to proivde same MFEs for all of them, then in theory you can build the your mfe image once for all the instances
   
  ## The case of 2.i 
   
Now to recap for the case of 2.i there are breaking changes, because some patches for tutor are no longer used, and would need to use patch in order to override config values. 

## The case of 2.ii 

For the caes of 2.ii, to be do that the simple trick we used in tutor-mfe is that we use the following: 

Build a container image for an MFE with the following env variables: 

### Changes at MFE level 
```
ENV APP_ID=<MFE-name> #Name to need to match the name in LMS settings
ENV PUBLIC_PATH='mfe-name' # Only needed if you server multiple MFE from same domina
ENV MFE_CONFIG_API_URL=/api/mfe_config/v1
```

### Changes in LMS:

- As you already said, one need to set the featuer flag of dynamic config API. 
- You can define configuration all apply to all 
- You can define configuration per mfe hence `APP_ID` above 

### Proxy role

Recall we set `MFE_CONFIG_API_URL=/api/mfe_config/v1`  above, this means that the MFE will will make a **relative** API call to it's host, i.e. but however this request is meant to be served by the LMS, thus for this proxy to work correctly; _The MFE host (be it nginx, caddy,...etc) needs to know the hsot of the LMS in order to create a proxy role such that: 

`When reqeust is prefiex with `/api/mfe_config/v1 => LMS_HOST`. 

Last Note: regarding this case of 2.ii, we have tested and made few changes in order for it to work as expected, _to ensure consumer MFE do get their LMS/CMS url from dynamic config). So note this probably important and relevant in case people want to make their set up using 2.ii **and are using MFE that is officialy in ollive branch**

2022-12-12 14:21 UTC, regisb commented on en_us/open_edx_release_notes/source/olive.rst
> +==========================
Could you please link Tutor users to the Tutor changelog? https://github.com/overhangio/tutor/blob/master/CHANGELOG.md

2022-12-12 14:21 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +
We're discussing whether to include 2.i here [in Slack](https://openedx.slack.com/archives/C049JQZFR5E/p1670854510775359?thread_ts=1670792405.761119&cid=C049JQZFR5E), but I'm pretty sure 2.ii and the proxy role should be a forum post, as opposed to part of the official documentation.  Sort of a "This is How We Solved the Container Build Problem With Tutor".

As for the LMS changes and specific feature documentation, the link to the ADR should take care of it.

2022-12-12 15:35 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +The Persistent Grades feature was added as an option in Hawthorne. Legacy, non-persistent grades were deprecated in Nutmeg. Now, persistent grades are required. If you have not turned on persistent g
I made that more explicit. Let me know if it isn't clear.

2022-12-12 15:38 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +==========================
Sure, but what context should I provide? When I look at the changelog, it's not obvious to me which changes are relevant to olive.

2022-12-12 15:42 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +The Learning Micro Frontend (MFE) is no longer optional, and must be run as part of your installation. It has been the default since the Maple release, with a setting that allowed for opting out. The
Sorry, I don't understand what change you're proposing. And I don't know what you are referring to when you say "see below"

2022-12-12 15:45 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +==========================
I added a link. Let me know if you have any edits or clarifications.

2022-12-12 15:49 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +
> the docs seems to be written in a perspective of outside tutor/tutor-mfe ecosystem

The docs should be written from the Tutor perspective. If they aren't please point out where changes should be made. 

I don't think we need to address your case of 2.ii since it is outside the Tutor ecosystem.

2022-12-12 15:50 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +
If the configuration is optional, I don't understand why it's a breaking change. 

Are there configuration changes that are required (for Tutor users) that are necessary for the MFEs to continue to work?

2022-12-12 15:55 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +
I added a Known Issues section. I feel like this could be an infinite list, but I guess we'll start with two bullets.

2022-12-12 16:08 UTC, ghassanmas commented on en_us/open_edx_release_notes/source/olive.rst
> +
@pdpinch for tutor_mfe the way it's set up it's not optional to not use dynamic config, bceause tutor-mfe utilzie the the case (2). And it would be really messy if tutor to support 1 and 2 in the sametime _that was the census at the time we add this change_... 

So in summary it's dynamic config is optional if you don't rely on tutor/tutor-mfe, while it's not if your have your setup/deployment. 

But again do we want to mention the docs here or in the release notes of tutor or/and tutor-mfe?

2022-12-12 17:00 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +
@pdpinch, see if this makes sense to you:

```suggestion

Upgrade note
~~~~~~~~~~~~

In Tutor, :code:`ENABLE_MFE_CONFIG_API` is not only enabled and used by default by all supported MFEs, but the mechanism of setting some MFE settings via Tutor configuration is no longer supported.  When upgrading from Nutmeg to Olive, the following variables can no longer be set via :code:`tutor config save --set`:

* Account MFE: :code:`COACHING_ENABLED` and :code:`ENABLE_DEMOGRAPHICS_COLLECTION`
* Profile MFE: :code:`ENABLE_LEARNER_RECORD_MFE`

Instead, the recommended way for a Tutor plugin to change MFE settings from Olive onwards is to use the :code:`openedx-lms-production-settings` and :code:`openedx-lms-development-settings` hooks to change :code:`MFE_CONFIG` or :code:`MFE_CONFIG_OVERRIDES` as needed.  For instance::

  MFE_CONFIG["PLATFORM_NAME"] = "My Awesome Platform"
  MFE_CONFIG_OVERRIDES["account"]["SITE_NAME"] = "My Awesome Site"

Also note that if you've maintained such plugin prior to Olive, the following hooks are no longer available after the upgrade::

* :code:`mfe-env-production`
* :code:`mfe-env-development`

You must instead migrate your MFE settings to the LMS settings hooks as described above.

2022-12-12 17:10 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +
I've offered a suggested change [below](https://github.com/openedx/edx-documentation/pull/2093/files#r1046104339).

2022-12-12 17:16 UTC, sarina requested changes

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +If you are not using Tutor, and have not turned on persistent grades in your installation yet, grades will disappear from learners' Progress pages and in Instructors' data downloads when you upgrade
If they run it after the upgrade, will there be a period where users won't see their grades?

I would think it would be advisable to run before, make sure everything with grades is working right, then do the olive upgrade.

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +The default expiration for JWT access tokens is now one hour. This default setting can be overriden by setting :code:`JWT_ACCESS_TOKEN_EXPIRE_SECONDS`.
This is in the Breaking Changes section but the text doesn't explain what is breaking or why I would override the default

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +Learner Experiences
This is now New Features, not Breaking Changes, right?

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +The Authentication MFE is responsible for the login, registration and password reset functionality. It is enabled by default in Olive and has all the same features as the legacy login and registratio
Do we know when the legacy experience wil be removed?

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +Authentication Micro-Frontend (MFE)
```suggestion
Authentication Micro-frontend (MFE)
```

for consistency with the rest

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +#. Code formatted in MFE do not appear formatted in in-line discussions
```suggestion
#. Code formatted in MFE does not appear formatted in in-line discussions
```

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +Known issues: Discussions MFE (rendered in Discussions tab) uses tinyMCE v5 which is a different text editor compared to the in-line discussions. As a result, there are some incompatibilities:
```suggestion
**Known issues**: Discussions MFE (rendered in Discussions tab) uses tinyMCE v5 which is a different text editor compared to the in-line discussions. As a result, there are some incompatibilities:
```

just emphasizing that more. Could also be a minor heading but I forget the next header down after `---`

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +The Discussions MFE is included in the Olive release and enabled by default. You can control which learners will see it with the waffle flag :code:`discussions.enable_discussions_mfe`. To configure c
do we know when the legacy experience will be deprecated?

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +- Even if the the Learner Records MFE is turned on, the old UI is still used for public links to records. This will be changed in the Palm release. (this may have been backported already)
```suggestion
- Even if the the Learner Records MFE is turned on, the old UI is still used for public links to records. This will be changed in the Palm release.
```

Reminder to remove this before publishing, whatever the outcome is

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +- The Learner records MFE is now available as an optional frontend for the Credentials application. See the `Learner Records MFE README`_ for configuration information.
What is the Learner Records MFE?

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +- tabs will now display in a consistent order: Course, Progress, Dates, Discussion, etc.
I thought this happened at least one if not more releases ago. I also recall seeing a list of the canonical ordering.

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +The Course Authoring Micro-frontend is included and enabled in the Olive release, but only the :ref:`pages-and-resources` feature is turned on.
enabled by default, or optionally enabled?

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +- makes emoticons easy to include
```suggestion
- makes emoticons easy to include,
```

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +Part of the :ref:`course-authoring-mfe` the new Text Editor includes updates that make it even easier to include text and images in your course content. Set the waffle flag :code:`new_core_editors.us
```suggestion
Part of the :ref:`course-authoring-mfe`, the new Text Editor includes updates that make it even easier to include text and images in your course content. Set the waffle flag :code:`new_core_editors.use_new_text_editor` to enable it. The newly updated editor:
```

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +Part of the :ref:`course-authoring-mfe`, the new video editor is not production ready. If you want to experiment with it, you can be enable it by setting the waffle flag :code:`new_core_editors.use_n
```suggestion
Part of the :ref:`course-authoring-mfe`, the new video editor is not production ready. If you want to experiment with it, you can enable it by setting the waffle flag :code:`new_core_editors.use_new_video_editor`
```

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +An email can now be sent out to discussion moderators when content (post/response/comment) is reported.  To use it, set the :code:`discussions.enable_reported_content_email_notifications` waffle flag
```suggestion
An email can now be sent out to discussion moderators when content (post/response/comment) is reported.  To use it, set the :code:`discussions.enable_reported_content_email_notifications` waffle flag.  See `the GitHub pull request <https://github.com/openedx/edx-platform/pull/30276>`_ for more details.
```

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +- upgraded TinyMCE version 4 to version 5.5.1.
Is that everywhere? Above you said the discussions MFE made it so that formatting changes from tinyMCE 5 wasn't going to be displayed in the inline discussions

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +Support for importing courses that use obsolete XML attributes has been removed. Courses with attributes :code:`slug`, :code:`name` in course tags, :code:`display_name` and :code:`id` in discussion t
```suggestion
Support for importing courses that use obsolete XML attributes has been removed. Courses with attributes :code:`slug`, :code:`name` in course tags, :code:`display_name` and :code:`id` in discussion tags and :code:`attempts` in problem tags, will no longer import properly. A simple import and export before upgrading will update the XML attributes. See `the GitHub pull request <https://github.com/openedx/public-engineering/issues/74>`_ for more details.
```

I'm pretty sure if you put in a raw URL, RST will not render it as clickable.

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +In order to make testing Open edX easier, `this course and its associated libraries`_ aim to expose as many Open edX Studio & courseware features as possible. It does so by providing example usages o
O
```suggestion
In order to make testing your Open edX installation easier, `this course and its associated libraries`_ aim to expose as many Open edX Studio & courseware features as possible. It does so by providing example usages of various block types and by enabling various features through Advanced Settings.
```

Per trademark rules, `Open edX` is an adjective and must not be used as a noun in any location.

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +As part of `OEP-55`_, the following filters were added in olive:
```suggestion
As part of `OEP-50`_, the following filters were added in Olive:
```

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +.. _OEP-55: https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0050-hooks-extension-framework.html
```suggestion
.. _OEP-50: https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0050-hooks-extension-framework.html
```

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +* added tracking event on learner search (in discussions)
what's the tracking event called?

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +* added many new discussion events, including :code:`edx.forum.thread.edited`, :code:`edx.forum.response.edited`, :code:`edx.forum.comment.edited`
do we have a list of all of them?

2022-12-12 17:16 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +* `Learner Record Micro-Frontend (MFE)`_
How is this in a pre-alpha state when it is mentioned above in the Learner Experiences section, with a lot of detail, and does not say "pre-alpha" up there?

2022-12-12 17:34 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +The Authentication MFE is responsible for the login, registration and password reset functionality. It is enabled by default in Olive and has all the same features as the legacy login and registratio
Great question.  Not a clue.

2022-12-12 17:40 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +* `Learner Record Micro-Frontend (MFE)`_
+1.  I wouldn't call it pre-alpha.  For two reasons:

1. It works and is currently maintained; just not supported by Tutor.
2. It is not likely to ever be part of Tutor, and thus, it won't evolve from alpha, to beta, then to the implicit inclusion in Tutor.

2022-12-12 17:44 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +* `Learner Record Micro-Frontend (MFE)`_
Why are we mentioniong it in the Learner Experiences section? When I read that my assumption was those are the supported MFEs, supported by Tutor and available to run

2022-12-12 17:48 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +* `Learner Record Micro-Frontend (MFE)`_
@sarina, long story short: it was a middle ground after lots of back-and-forth with 2U.  BTR/Tutor doesn't/won't support it as an official part of the release, but for deprecation purposes it _is_ part of the release, so we must mention it in the Release Notes somewhere.

It's certainly debatable where it should go. 🤷🏼‍♂️

2022-12-12 18:31 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +* `Learner Record Micro-Frontend (MFE)`_
I think it should go in a separate
```
Unsupported by Tutor
----------------------
```

section after Pre-Alpha. I insist that putting it in Learner Experiences makes it seem like a feature I am ready to use and is a part of Olive, not something _unsupported_ by Tutor, that will _never_ be supported by Tutor.

Also why does it matter to 2U whether or not this MFE is related to the release?

2022-12-12 19:19 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +* `Learner Record Micro-Frontend (MFE)`_
+1 to the separate section.

It matters to 2U because if it's not part of an Open edX release, they can't deprecate the feature that it replaces, and thus can't remove it in the next release.

2022-12-12 19:24 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +* `Learner Record Micro-Frontend (MFE)`_
But if they deprecate the feature this replaces, yet this is unusable... how does that work?

2022-12-12 21:09 UTC, ghassanmas commented on en_us/open_edx_release_notes/source/olive.rst
> +
Exactly what @arbrandes is saying here what we I think refer as breaking changes


So if in Nutmeg or earlies release you made use of `mfe-env-production` or/and `mfe-env-development` tutor patches, then you have to migrate them.  But now if you don't use them then probably there is no thing you need to do. And probably you will be able to upgrade to Olive without rebuilding your tutor-mfe image, unless you use other patche like `mfe-dockerfile-post-npm-install` . 

So again in summary let's take all the cases: 

 1. You use tutor-mfe while you **don't make use** of  A) (`mfe-env-production`, and `mfe-env-development`) , B) and `mfe-dockerfile-post-npm-install` 
    1. You don't need to do anything in this case and actually you suppose to be able to migrate to Olive without building the tutor-mfe image 
        
 1. You use tutor-mfe while you **do make use** of  A) (`mfe-env-production`, and `mfe-env-development`) , B) and **not** `mfe-dockerfile-post-npm-install` 
    1. You would need to migrate the patches as @arbrandes mention above but still you don't need to rebuild the image just like 1.i
    
   1. You use tutor-mfe while you **don't make use** of   (`mfe-env-production`, and.or  `mfe-env-development`) , but  **do make use** of  `mfe-dockerfile-post-npm-install` 
     i. You don't need to need to need to anything regarding migrating to patches, you still need to rebuild your tutor-mfe image, just like the case where you have to rebuild tutor openedx image in case you use `openedx-dockerfile-pre-assets` or simliar patches. 

  1. Also I think there is another case where migration or build might be needed,  if opreator where to override a settings per MFE, i.e. `--set tutor config save --set MFE_EXAMPLE_MFE_APP={'name': 'example', 're' env: {'production':{'key':name'}, {'key':name'} } 'repository': 'https://github.com/frontend-app-example', }` 
      1. If opreator override 'env' then you need to migrate them using spefically `MFE_CONFIG_OVERRIDES["example"]`
        1. in case for 'env'['production'] then use `openedx-lms-production-settings` and same for development
      1. if opreator to override `repository` then they need to rebuild the image, because by default tutor-mfe image uses default repo with the default openrealse branch, just like you need to rebuild the openedx image in case you have run your own fork. 


This my understanding of the changes and how it's affected different use cases with tutor-mfe. So in summary is it breaking change, short anwer as always **it depends**.

2022-12-12 21:23 UTC, kdmccormick commented on en_us/open_edx_release_notes/source/olive.rst
> +- The Learner records MFE is now available as an optional frontend for the Credentials application. See the `Learner Records MFE README`_ for configuration information.
+1, would love to see some more info here so that operators would know what they'd be changing by enabling the LRMFE. I have a vague understanding that the MFE is incrementally replacing some legacy pages from Crededentials (and LMS too?), but I don't know enough to write the blurb myself.

 @hurtstotouchfire would you be able to suggest a sentence or two on what the LRMFE adds to Olive?

2022-12-12 21:28 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +* `Learner Record Micro-Frontend (MFE)`_
The feature it replaces has never been included in an open release, and it does not have a Tutor plugin.

2022-12-12 21:31 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +Support for importing courses that use obsolete XML attributes has been removed. Courses with attributes :code:`slug`, :code:`name` in course tags, :code:`display_name` and :code:`id` in discussion t
works in the draft build, at https://edx--2093.org.readthedocs.build/projects/open-edx-release-notes/en/2093/olive.html#legacy-olx-attributes-translations-removed

![image](https://user-images.githubusercontent.com/430126/207158745-9abb3e21-c79c-40ff-aeba-8340d64ebe95.png)

but if you think your change reads better, I'm happy to commit your suggestion. Let me know.

2022-12-12 21:32 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +In order to make testing Open edX easier, `this course and its associated libraries`_ aim to expose as many Open edX Studio & courseware features as possible. It does so by providing example usages o
Oh wow. I'll keep that in mind.

2022-12-12 21:34 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +If you are not using Tutor, and have not turned on persistent grades in your installation yet, grades will disappear from learners' Progress pages and in Instructors' data downloads when you upgrade
Is it safe to assume that operators read the release notes before they upgrade? I just wanted to reassure them that all is not lost after the upgrade.

2022-12-12 21:35 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +Learner Experiences
Yes. Should that be clearer, somehow?

2022-12-12 21:38 UTC, kdmccormick commented on en_us/open_edx_release_notes/source/olive.rst
> +
@ghassanmas is it that complicated? The way I see it is:

Upgrading to a new release will automatically force the MFE image to be rebuild (or re-pulled) because the frontend-app repository URLs will change to point to the new release's tags. So, we can assume that every operator will re-build or pull the image at least *once*. We don't need to mention this in the release notes; it'll just happen.

Then, operators will need to change their settings to use runtime config, as a @arbrandes describes above. **This** is the breaking change, and it'll apply to ~100% of operators using tutor-mfe, since nobody is running the default settings in production.

Then, going forward, operators who *don't* patch any of `mfe-dockerfile-*` may choose to pull their images instead of building them. Operators who *do* patch any of `mfe-dockerfile-*` must continue building the mfe image... but this is nothing new, so I wouldn't call it a breaking change.

2022-12-12 21:41 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +- upgraded TinyMCE version 4 to version 5.5.1.
I think this refers specifically to Studio and not discussions. I'll see if I can reconstruct the scope of the change.

2022-12-12 21:44 UTC, kdmccormick commented on en_us/open_edx_release_notes/source/olive.rst
> +* `Learner Record Micro-Frontend (MFE)`_
^ This

BTR has been struggling to answer the question of "What is in a release?". For the purpose of deprecation, we made the ad-hoc decision that the old thing (Learner Records MFE) must be "as released" as the thing it is deprecating (Credentials) was. Both of them are tagged, but not run in Tutor by default.

(Side note: It's not that these things can't run in Tutor; it's that there's no officially supported Tutor plugin for them. A savvy operator could figure out how to run either of them.)

2022-12-12 21:48 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +* `Learner Record Micro-Frontend (MFE)`_
I am so confused I'm proabbyl gonna bow out of this, it makes no sense to me though.

If feature A has never been a part of Open edX release
and feature B was created to replace feature A

why would B need to be in the Open edX release at all, or block a team from removing Feature A?

2022-12-12 21:48 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +Support for importing courses that use obsolete XML attributes has been removed. Courses with attributes :code:`slug`, :code:`name` in course tags, :code:`display_name` and :code:`id` in discussion t
Ah nah it's fine

2022-12-12 21:49 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +Learner Experiences
I guess it'll be clear in the rendered RST, I just lost track in the raw.

2022-12-12 21:50 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +If you are not using Tutor, and have not turned on persistent grades in your installation yet, grades will disappear from learners' Progress pages and in Instructors' data downloads when you upgrade
"While we recommend this be run before the upgrade, to ensure learners experience no disruptions to their Progress pages, it will work if it is run after the upgrade."

Does that sound right and accurate?

2022-12-12 21:56 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +* `Learner Record Micro-Frontend (MFE)`_
You're not the only confused one.  It took us a while to hash it out, and I'm confused myself.

The core of the problem is that it's not clear what constitutes an Open edX release.  It's clearly not just what Tutor supports: we tagged 39 repositories today, and a significant fraction of them is not in Tutor.

On the other hand, what does it mean for something to be released but not installable by any supported means?

Yeah.  Not sure either.  I guess this is something to hash out via OEP-57, the upcoming OEP-61, the maintainers project, the Product Quality draft... And I'm still probably missing something, haha

2022-12-12 21:59 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +* `Learner Record Micro-Frontend (MFE)`_
Oh, and the specific reason 2U is concerned about inclusion is not only the DEPR process, but the [BTR MFE requirements checklist](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3561521275/Requirements+for+an+MFE), which in item 12 states that a new MFE must allow one full release cycle of deprecation before removal of a legacy feature it replaces.

2022-12-12 22:01 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +* `Learner Record Micro-Frontend (MFE)`_
(And the reason THAT's there is to avoid the whole ecommerce situation, where the payments MFE was introduced at the same release the legacy feature it replaced was dropped.)

2022-12-12 22:18 UTC, ghassanmas commented on en_us/open_edx_release_notes/source/olive.rst
> +
@kdmccormick I might been too explicit, there are of course things not realted to dynamic config, the reason I went to excplit is that I don't want opreators to confuse because it was **always the case that tutor-mfe image needed to rebuild** but now that is not the case.  

So my comment above is just a reflection, I didn't necessary meant we have to add literally as it's to the release docs.

2022-12-12 22:21 UTC, kdmccormick commented on en_us/open_edx_release_notes/source/olive.rst
> +
Got it. Now that you've spelled it all out, it would be good to add that operators who don't use the Dockerfile patches or change config can now just pull the image.

2022-12-13 02:01 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +The Learning Micro Frontend (MFE) is no longer optional, and must be run as part of your installation. It has been the default since the Maple release, with a setting that allowed for opting out. The
Ok, now I think I understand. Does this cover it now? 

https://edx--2093.org.readthedocs.build/projects/open-edx-release-notes/en/2093/olive.html#learning-mfe-is-now-required

2022-12-13 02:02 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +The default expiration for JWT access tokens is now one hour. This default setting can be overriden by setting :code:`JWT_ACCESS_TOKEN_EXPIRE_SECONDS`.
I added some more details, see https://edx--2093.org.readthedocs.build/projects/open-edx-release-notes/en/2093/olive.html#jwt-access-tokens-expire-in-1-hour

2022-12-13 02:12 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +- tabs will now display in a consistent order: Course, Progress, Dates, Discussion, etc.
You're right. My method for reviewing olive PRs picked this up because there were post-nutmeg comments on the PR. I'll remove it.

2022-12-13 02:15 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +An email can now be sent out to discussion moderators when content (post/response/comment) is reported.  To use it, set the :code:`discussions.enable_reported_content_email_notifications` waffle flag
the raw link works just as well

2022-12-13 02:22 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +The Authentication MFE is responsible for the login, registration and password reset functionality. It is enabled by default in Olive and has all the same features as the legacy login and registratio
I don't think the deprecations have been announced yet, but I'm adding a note that they could be removed "as early as the next release, Palm"

2022-12-13 02:44 UTC, pdpinch commented
@arbrandes @ghassanmas @regisb I added a brief section on the MFE runtime config to breaking changes. Let me know if it's too much. 

https://edx--2093.org.readthedocs.build/projects/open-edx-release-notes/en/2093/olive.html#mfe-settings-are-no-longer-supported-in-tutor-configuration

I also accepted Adolfo's "upgrade note"

https://edx--2093.org.readthedocs.build/projects/open-edx-release-notes/en/2093/olive.html#upgrade-note

2022-12-13 02:45 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +
see https://github.com/openedx/edx-documentation/pull/2093#issuecomment-1347668945

2022-12-13 02:53 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +* `Learner Record Micro-Frontend (MFE)`_
Okay, I changed "Pre Alpha" to "Unsupported in Tutor"

And I removed the section on the Learner Record MFE. It only contained a (duplicate) link to the readme and two known issues. I'm not opposed to saying something more about it. But, as I wrote it, it's more confusing than informative.

2022-12-13 14:21 UTC, arbrandes reviewed
Suggested fixes to my earlier suggestions.  Otherwise, looks great to me!

2022-12-13 14:21 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +Other Operator Experience changes
I missed a trailing newline in my earlier suggestion (and this actually breaks the render).

```suggestion

Other Operator Experience changes
```

2022-12-13 14:21 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +Where up until Nutmeg it was only possible to change a micro-frontend's settings at build time, it is now possible to do so at both server _and_ browser runtime via a new configuration mechanism.  In
Another mistake on my earlier suggestion: I got RST italics wrong.

```suggestion
Where up until Nutmeg it was only possible to change a micro-frontend's settings at build time, it is now possible to do so at both server *and* browser runtime via a new configuration mechanism.  In addition to the added convenience, this significantly reduces the frequency at which MFE container images need to be rebuilt.  Many operators will never have to build them to begin with, as pre-built ones can be (and are) provided, thus saving up precious time and resources on deployment.
```

2022-12-13 14:29 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +Other Operator Experience changes
I think stylistically you need a new line above  and below the title text too, at least this is the convention followed in this and other RST files

```
You must instead migrate your MFE settings to the LMS settings hooks as described above.

Other Operator Experience changes
------------------------------------

- fixed
```

2022-12-13 14:31 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +- upgraded TinyMCE version 4 to version 5.5.1.
I'd still like this addressed before I give approval, it confused me to read that tinyMCE 5 broke inline discussions yet that it's upgraded everywhere. If it's indeed the case that it was only upgraded everywhere in Studio, but not in LMS, I think it'd be good to note that explicitly (even though this is under the "Instructor Experience changes" section).

2022-12-13 14:31 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +Known issues: Discussions MFE (rendered in Discussions tab) uses tinyMCE v5 which is a different text editor compared to the in-line discussions. As a result, there are some incompatibilities:
Any thought on including this?

2022-12-13 15:03 UTC, kdmccormick commented on en_us/open_edx_release_notes/source/olive.rst
> +The Discussions MFE is included in the Olive release and enabled by default. You can control which learners will see it with the waffle flag :code:`discussions.enable_discussions_mfe`. To configure c
I see nothing on the [DEPR board](https://github.com/orgs/openedx/projects/9/views/4) for it 🤷🏻

2022-12-13 23:06 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +Part of the :ref:`course-authoring-mfe`, the new Text Editor includes updates that make it even easier to include text and images in your course content. Set the waffle flag :code:`new_core_editors.u
I would mention that the "HTML component" is now the "Text Component" in Studio. See https://openedx.atlassian.net/wiki/spaces/OEPM/blog/2022/10/21/3560571009/2U+New+Text+HTML+Editing+Experience

2022-12-13 23:12 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +.. _Removed Learner View in Insights, Data Pipeline and API: https://github.com/openedx/public-engineering/issues/36kl
```suggestion
.. _Removed Learner View in Insights, Data Pipeline and API: https://github.com/openedx/public-engineering/issues/36
```

I went to  https://github.com/openedx/public-engineering/issues/36 and it doesn't seem like it's removed. Last comment says there's a green light but "need to do it"

2022-12-13 23:13 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +.. _Removed dependency in ecommerce application on deprecated v1 catalog API: https://github.com/openedx/public-engineering/issues/61
I don't think this is done based on the discussions in https://github.com/openedx/public-engineering/issues/61

2022-12-13 23:22 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +- Android app support is currently limited to `Release 3.0.2 <https://github.com/openedx/edx-app-android/releases/tag/release%2F3.0.2>`_.
Do you know why this is, or what impact it might have? (decreased parity between apple and android maybe?)

2022-12-13 23:26 UTC, sarina commented
@pdpinch where do you use the `en_us/open_edx_release_notes/images/olive/page_and_resources_view.png` file? I want to know more about that change

2022-12-14 09:52 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +* `ORA Grading Micro-frontend (MFE)`_ `
Extraneous closing tick

```suggestion
* `ORA Grading Micro-frontend (MFE)`_
```

2022-12-14 10:34 UTC, arbrandes commented on en_us/open_edx_release_notes/source/olive.rst
> +- Android app support is currently limited to `Release 3.0.2 <https://github.com/openedx/edx-app-android/releases/tag/release%2F3.0.2>`_.
@sarina, more info [here](https://github.com/openedx/build-test-release-wg/issues/211#issuecomment-1344311500).

While we're on it, it would probably be a good idea to include all issues in [the Olive.2 milestone on the BTR board](https://github.com/orgs/openedx/projects/28/views/13) (including any that might be closed when the list is checked, as the fixes will only be included in the olive.2 tag).

2022-12-14 14:59 UTC, sarina commented
@pdpinch ignore https://github.com/openedx/edx-documentation/pull/2093#issuecomment-1350035993

I meant this file: [en_us/open_edx_release_notes/images/palm/new_ora_grading_experience.png](https://github.com/openedx/edx-documentation/pull/2093/files#diff-6440e03d0377086f43ef752f9d63f5a47123c48b4964fde59d4ada6e1a12db4a)

2022-12-14 15:02 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +- Android app support is currently limited to `Release 3.0.2 <https://github.com/openedx/edx-app-android/releases/tag/release%2F3.0.2>`_.
That sounds good. I guess I wish release notes said a bit more about impact when we're describing what "known issues" there are.

2022-12-14 15:10 UTC, kdmccormick approved these changes
As always, thanks for your work on these @pdpinch 😄 

Since the release has been announced for a day, unless there are any glaring issues, I vote for merging these ASAP and then bringing any remaining improvements to a follow-up PR.

2022-12-15 15:18 UTC, feanil reviewed
A few small suggestions but overall looks great! Thanks @pdpinch

2022-12-15 15:18 UTC, feanil commented on en_us/open_edx_release_notes/source/olive.rst
> +Also note that if you've maintained such a plugin prior to Olive, the following hooks are no longer available after the upgrade::
```suggestion
Also note that if you've maintained such a plugin prior to Olive, the following hooks are no longer available after the upgrade:
```
The double colon puts this in a code block but each item is already in a code block so you don't need to do that.

2022-12-15 15:18 UTC, feanil commented on en_us/open_edx_release_notes/source/olive.rst
> +- fixed a performance issue when using multiple themes when running in docker. Now by using LRU cache when searching themes,  the performance was improved.
```suggestion
-  A performance issue that occurs when using multiple themes in a docker environment was fixed by using an LRU cache when searching themes.
```

2022-12-18 22:25 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +.. _Removed Learner View in Insights, Data Pipeline and API: https://github.com/openedx/public-engineering/issues/36kl
I found three related PRs that seem to have removed this from the instructor-facing interfaces: 

- https://github.com/openedx/edx-analytics-data-api/pull/571
- https://github.com/openedx/edx-analytics-data-api-client/pull/89 
- https://github.com/openedx/edx-analytics-dashboard/pull/1332

I [commented on the DEPR ticket](https://github.com/openedx/public-engineering/issues/36#issuecomment-1356889564) to ask for more clarity, but I still think this has been removed.

2022-12-19 01:53 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +- Android app support is currently limited to `Release 3.0.2 <https://github.com/openedx/edx-app-android/releases/tag/release%2F3.0.2>`_.
The Release notes for the Android app are pretty sparse, but I summarized the release notes between 3.2.2 and 3.0.2

2022-12-19 02:19 UTC, pdpinch commented on en_us/open_edx_release_notes/source/olive.rst
> +.. _Removed dependency in ecommerce application on deprecated v1 catalog API: https://github.com/openedx/public-engineering/issues/61
I agree. Removed.

2022-12-19 02:24 UTC, merged

2022-12-19 02:24 UTC, openedx-webhooks commented
@pdpinch 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-documentation&entry.867055334=https://github.com/openedx/edx-documentation/pull/2093&entry.1484655318=https://github.com/pdpinch&entry.752974735=2022-11-20+17:01&entry.1917517419=2022-12-19+02:24&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->

2022-12-19 02:24 UTC, pdpinch commented
Thanks for the approval @kdmccormick -- I needed that before I could merge.

2022-12-19 13:15 UTC, sarina commented on en_us/open_edx_release_notes/source/olive.rst
> +.. _Removed Learner View in Insights, Data Pipeline and API: https://github.com/openedx/public-engineering/issues/36kl
It would be good to link these PRs on the DEPR ticket, because people like me looking to learn more will be confused

2022-12-19 13:16 UTC, sarina commented
@pdpinch I see you removed [en_us/open_edx_release_notes/images/palm/new_ora_grading_experience.png](https://github.com/openedx/edx-documentation/pull/2093/files#diff-6440e03d0377086f43ef752f9d63f5a47123c48b4964fde59d4ada6e1a12db4a) - is that because the change didn't go into the release? (I'm writing blog posts and this seems interesting, if included)