Update preface.rst
openedx-unsupported/edx-documentation pull request #2129
Opened 2023-04-06 15:55 UTC by ProductRyan

Add a description of your changes with links to any relevant material.
- updating basic info and links

### Date Needed (optional)
- N/A

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers
- @sarina 

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:.

- [ ] Subject matter expert:
- [ ] Subject matter expert:
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support:
- [ ] PM review:

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2023-04-06 16:50 UTC, sarina requested changes
Hey @ProductRyan this is great! Could you take a look at my comments and address them?

I'm not sure if you need it, but here's instructions on modifying your pull request: https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html

2023-04-06 16:50 UTC, sarina commented on en_us/shared/preface.rst
> +to use the edX learning management system. The Help Center is also available from withing the learning experinece by selecting the **Help** menu and from within your edX dashboard.
Typo: "withing"

The last part of this sentence reads awkwardly to me. You use "within" twice. Would it be accurate to say,

"The Help Center is also available from within the learning experience. From your edX dashboard, select the **Help** menu."

2023-04-06 16:50 UTC, sarina commented on en_us/shared/preface.rst
> +edX instance, extending the edX platform, and contributing to the Open edX project. In
Can you say "Open edX platform"?

2023-04-06 16:50 UTC, sarina commented on en_us/shared/preface.rst
> +addition, the Open edX Psite provides product announcements and other
Typo: Psite

2023-04-06 16:58 UTC, sarina commented on en_us/shared/preface.rst
> +The `Open edX Site`_ is the destination for learning about hosting an Open
Ah, this breaks the link that was formerly called "Open edX Portal". This is called Open edX Portal throughout this document (multiple times). So I wouldn't make this change right now; if you want to change it everywhere in this doc I'd make a new pull request.

2023-04-13 01:03 UTC, sarina commented
Hey @ProductRyan  - do you have time/capacity to address the changes?

2023-07-24 20:18 UTC, feanil commented
@ProductRyan checking back in, do you have time to address the change request?

2023-08-01 21:10 UTC, sarina requested changes

2023-08-01 21:10 UTC, sarina commented on en_us/shared/preface.rst
> +addition, the Open edX Psite provides product announcements and other
```suggestion
addition, the Open edX site provides product announcements and other
```

2023-08-01 21:10 UTC, sarina commented on en_us/shared/preface.rst
> +edX instance, extending the edX platform, and contributing to the Open edX project. In
```suggestion
edX instance, extending the Open edX platform, and contributing to the Open edX project. In
```

2023-08-01 21:10 UTC, sarina commented on en_us/shared/preface.rst
> +The `Open edX Site`_ is the destination for learning about hosting an Open
```suggestion
The `Open edX Portal`_ is the destination for learning about hosting an Open
```

2023-08-01 21:10 UTC, sarina commented on en_us/shared/preface.rst
> +to use the edX learning management system. The Help Center is also available from withing the learning experinece by selecting the **Help** menu and from within your edX dashboard.
```suggestion
to use the Open edX learning management system. On edx.org, the Help Center is also available from within the learning experience by selecting the **Help** menu from within your edX dashboard.
```

2023-08-01 21:17 UTC, sarina approved these changes

2023-08-01 21:24 UTC, merged