docs: add docs for Xpert course translations
openedx-unsupported/edx-documentation pull request #2266
Opened 2024-06-05 21:21 UTC by nsprenkle

Add documents for Xpert course translations
JIRA: https://2u-internal.atlassian.net/browse/AU-1998

### Date Needed (optional)

ASAP

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:.

- [ ] Product review: @Daniel-hershel 

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

2024-06-06 00:12 UTC, jristau1984 requested changes
Regrettably, the images will likely all need to be updated with new versions before launch.

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/course_features/xpert_translations/enabling_disabling_translations.rst
> +  - There is a waffle flag managed by edX internally to enable the translations UI in Studio for all of all of a Partner's Partner's courses
Double word, remove second "Partner's".

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/course_features/xpert_translations/enabling_disabling_translations.rst
> +     :alt: Stuio page showing video transcript edit menu
"Studio" is misspelled.

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/course_features/xpert_translations/enabling_disabling_translations.rst
> +  - Once enabled, the features availability for a course can be controlled from the “Pages & Resources” section of a course.
"feature" is possessive here, should have an apostrophe.

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/course_features/xpert_translations/feature_cost.rst
> +  - edX is planning to cover the costs of translation initially, but retains the right to deduct these costs from course revenue prior to the calculation of revenue share per the bullet below.
There likely needs to be some extended info about how this will be dependent on several factors that are outlined in partner agreements.

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/course_features/xpert_translations/feature_description.rst
> +   #. **Video transc1ript translations:** Machine generated transcripts produced produced from existing english transcripts, originally provided by content creators.
"transcript" has a typo.
"produced" is duplicated

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/course_features/xpert_translations/feature_description.rst
> +  Combined, these features support the concept of **Xpert Course Translation** - where on average ~85% of course content is expected to be available in the languages selected for V1 (note, currently
Not sure that the point-in-time detail needs to be here.

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/course_features/xpert_translations/feature_description.rst
> +     :alt: Stuio page showing link to Transcript settings
"Studio" has a typo.

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/course_features/xpert_translations/feature_description.rst
> +  If video transcript translations are enabled for a course, users can select from a list of available languages to view the transcript
"users" should be replaced with "learners"

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/course_features/xpert_translations/feature_description.rst
> +  If video transcript translations are enabled for a course, users can select from a list of available languages to view the transcript
This is also not correct.  Whether the feature is enabled or not, if the transcripts are attached to the video then they will show to the learner.

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/course_features/xpert_translations/feature_description.rst
> +  Once a learner selects a language for their translated transcript, that choice is persistent as the default for the rest of the videos in a course. Users can update their language preference at any
Nit: "persistent" could be replaced with "persisted"

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/course_features/xpert_translations/feature_description.rst
> +  Once a learner selects a language for their translated transcript, that choice is persistent as the default for the rest of the videos in a course. Users can update their language preference at any
Last sentence should be replaced with "Learners can update their transcript language at any time using the video player UI."

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/course_features/xpert_translations/feature_description.rst
> +  - An existing english transcript is required for translation into other languages
Nit: replace with "... for generating transcripts in other languages."

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/course_features/xpert_translations/feature_description.rst
> +  Users will be able to select a new icon on the unit page of a course (pictured below):
Nit: remove "new", as that is point-in-time and read the docs is long-lived.

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/course_features/xpert_translations/feature_description.rst
> +  This feature is currently limited to translating HTML (aka HTML (aka text)) blocks, and Spanish language.  We are anticipating a fast follow to enable the translation of problem blocks and offering
There is a double HTML string here, but I would also switch the text and html titles... We want to push the "Text" title for that block.

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/course_features/xpert_translations/feature_description.rst
> +  This feature is currently limited to translating HTML (aka HTML (aka text)) blocks, and Spanish language.  We are anticipating a fast follow to enable the translation of problem blocks and offering
I believe we should have these external docs just say something like "current languages are Spanish and Arabic.  More languages may be added in the future."

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/course_features/xpert_translations/translations_technology.rst
> +  - “Intellectual Property Rights. Except as expressly described in the Agreement, the Agreement does not grant either party any rights, implied or otherwise, to the other’s content or intellectual p
I think this should be a link, not a copy paste.  It can change over time, I don't want to have to remember to update this...

2024-06-06 00:12 UTC, jristau1984 commented on en_us/course_authors/source/images/xpert_transcript_settings_options.png
This should be replaced with one that only has two languages listed.

2024-06-07 16:03 UTC, nsprenkle commented
@jristau1984 , updated with @Daniel-hershel , ready for re-review 👀

2024-06-10 17:21 UTC, jristau1984 approved these changes
lgtm

2024-06-10 17:29 UTC, merged